#!/bin/sh
# This is a shell archive, meaning:
# 1. Remove everything above the #!/bin/sh line.
# 2. Save the resulting text in a file.
# 3. Execute the file with /bin/sh (not csh) to create the files:
#	hersh.or3
#	hersh.or4
# This archive created: Tue Mar 25 22:19:34 1986
export PATH; PATH=/bin:$PATH
echo shar: extracting "'hersh.or3'" '(28972 characters)'
if test -f 'hersh.or3'
then
	echo shar: over-writing existing file "'hersh.or3'"
fi
cat << \SHAR_EOF > 'hersh.or3'
 3001 73D_QGQQ RRGRQ RLGJFJR RKGKR RKGXG RWGXFZGYI RXGXR RYGYR RKLXL RKQ
XQ RMUNTLTL[M\W\X[WZ RMUMZN[V[WZWX RQTRUSWTWTVSUQT RIVHXGYGZHZIXIV RZV[W
\Y]Y]X\WZV
 3008 74D_KFKP RKFLGLP RLGWG RWGWP RVGWFXGXP RQGQO RRGRO RLKWK RLOWO RNP
NW RNPOPOW RTPTW RTPUPUW RISZSYRXS RGW]W[VZW RNYMZJ\H] RNYOZM[H] RTYVZY\
Z][][\Z[XZTY
 3042 84D_THTGUFSFSH RJGJWIZG\ RJGKHKWJZG\ RKH]H[GZH RGIHLILIKGI RGSGQJP
 RGSJP RML]L[KZL RTLTQSTRV RULUQTTRVPW RPPNON\ ROPO\ ROPZP RYPZO\P[R RZP
ZZY[ R[P[ZZ\Y[WZ RURVTWWXWXVWTUR
 3092 89D_IFQF RQFPHMLJNGO RQFRGPJNLKNGO RRGTJVLYN[O]N RRGUJXLZM]N RIHJI
KKLKLJKIIH RWFUI RWFXGUI RZIXL RZI[JXL RLOWOVNUO ROOORNVMXKZI[ RPOPROVNX
LZI[ RSOSZT[\[]Z\Y RTOTYUZ[Z\Y]W RGT\TZSYT
 3095 37D_TFRFQJ RSFRH RTFQJ RLJJIJ\ RKJK\ RKJYJ RXJYI[JZL RYJY\ RZJZ\ R
KRYR RKZYZ
 3097 72D_KFJJ RKFLGJJ RHIH\ RHIIJI\ RIJNJ RNJN[ RMJNIOJO[ RIRNR RIZNZ R
UFSKRM RUFVGUIRM RTJ[J RZJ[I]J\L R[J[XZZY[ R[Y[ZZ[ R\J\Z[\Z\Y[WZ RTPUQVS
WSWRVQTP
 3109 67D_RGSFQFQP RRGRP RKJIIIUHYG[ RJJJUIXG[ RJJ[J RYJZI\KYL RZIYL R[J
YLXM RJPWP RVPWOYQVS RWPTUQXM[ RXQVTRXOZM[J\ RNQOSQVTYW[[\][ RQVUYXZ][
 3113 38D_LHJGJZ RKHKZ RKHYH RXHYG[HZJ RYHYZ RZHZZ ROHOZ RPHPZ RTHTZ RUH
UZ RHZ]Z\Y[Z
 3127 30D_MHKGK\ RLHL\ RLHXH RWHXGZHYJ RXHX\ RYHY\ RLNXN RLTXT RLZXZ
 3128 52D_NGLFLT RMGMT RMGVG RUGVFXGWI RVGVT RWGWT RMKVK RMOVO RMSVS RGV
]V[UZV RMYJ[G\ RMYNZK[G\ RUYWZZ\[\[[YZUY
 3164 69D_JGWG RVGWFYHVI RWGVI RXGVISL RMJOKRNSNSMRLPKMJ RGN[N RZN[M]OZP
 R[NZP R\NZPXR RRNRXQZP[ RRYRZQ[ RSNSZR\Q\P[NZ RQNORLVJXGZ RQNROQQOTLWIY
GZ
 3168 60D_OFMFKJIM RNFLI ROFLJIM RLJ[JYHWJ RWJZI RQJQOPSNWLYI[G\ RRJROQS
OWMYJ[G\ RGP]P[NYP RYP\O RSPTTVXXZ[\][ RYZ[[ RSPTSVVYY][
 3169 62D_JFIJHMGO RJFKGJJILGO RJJQJPIOJ RLJLSKWIZG\ RMJMSLWJZG\ RGPRPQO
PP RNUOWPZQZQYPWNU RTITZ RTIUJUZ RUJ[J R[J[Z RZJ[I\J\Z RUY[Y
 3172 85D_IFHJGMFO RIFJGIJHLFO RHKPKOJNK RKKKRJVIXG[ RLKLRKVIYG[ RGQPQOP
NQ RLUNWOYPYPXNVLU RQG]G[FZG RRKRS RRKSLSS RSLZL RZLZS RYLZK[L[S RSRZR R
STTYUYUXST RZTX[ RZT[UX[ RQ[][\Z[[
 3176 47D_GH]H[FYH RYH\G RQHOMMQKTGY RRHPL RSHQLNQKUGY RPQNPN\ ROQO\ ROQ
YQ RXQYP[QZS RYQY\ RZQZ\ ROZYZ
 3180 64D_GGOGNFMG RJGINHR RKGJMIPGT RINIZ RINJOJZ RJOMO RMOMY RLOMNNONY
 RJXMX RSGSRRVQXO[ RTGTRSVQYO[M\ RWGW\ RXGX\ RPG]G[FZG RPQ]Q[PZQ
 3191101D_FGNGMFLG RIGHNGR RJGIMHPFT RHNHZ RHNIOIZ RIOLO RLOLY RKOLNMOMY
 RIXLX RUGVFTFTI RUGUI RNI]I[HZI RTJRO RTJUKRO ROO[N ROOPP[N RYL[N\P]P]O
\NYL RPRPVOYN[ RPRQRQVPYN[ RTRT[ RTRURU[ RXRXZY[][]W RXRYRYYZZ\Z]Y
 3192 84D_GGOGNFMG RJGINHR RKGJMIPGT RIOI[ RIOJPJ[ RJPMP RMPMZ RLPMONPNZ
 RJYMY RWGXFVFVN RWGWN RRHSKTKTJRH R[HYK R[H\IYK RRMR\ RRMSNS\ RSNZN RZN
ZZY[ RYNZM[N[ZZ\Y[WZ RSRZR RSVZV
 3200 96D_FGMGLFKG RHGGNFR RIGHLFR RGNGZ RGNHOHZ RHOKO RKOKY RJOKNLOLY R
HXKX ROFOTNYM[ ROFPGPTOXM[ RPGSG RSGSYRZ RRGSFTGTYS[QY RPMSM RPSSS RWFWT
VYU[ RWFXGXTWXU[ RXG[G R[G[YZZ RZG[F\G\Y[[YY RXM[M RXS[S
 3209123D_GGOGNFMG RJGINHR RKGJMIPGT RIOI[ RIOJPJ[ RJPMP RMPMZ RLPMONPNZ
 RJYMY RRFSJTJTIRF RYFWK RYFZGWK ROK]K\J[K RSKQR RSKTLQR ROQPRQTRTRSQROQ
 RUPQZ RUPVQQZ RPZUZ RPZQ[UZ RTXU[V[VZTX RZKXR RZK[LXR RVQWRXTYTYSXRVQ R
\PXZ R\P]QXZ RWZ\Z RWZX[\Z R[X\[][]Z[X
 3228 51D_JHYHWFUH RUHXG RGN]N[LYN RYN\M RQNQXPZO[ RQYQZP[ RRNRZQ\P\O[MZ
 RLQIWGZ RLQMRLTGZ RVRXTZW[Y\Y\X[VYTVR
 3264 54D_HHLGOFPG RHHPG RLGL\ RMGM\ RGLRLQKPL RLMKPITGW RLPJSGW RNQORPT
QTQSPRNQ RUIUU RUIVIVU R[F[YZZ R[F\F\Y[[ZZXY
 3265 61D_HHLGOFPG RHHPG RLGL\ RMGM\ RGLRLQKPL RLMKPITGW RLPJSGW RNQORPT
QTQSPRNQ RXFVFSY RWFVK RXFSY RPYZW RPYRZZW RXTZV\Y]Y]X[VXT
 3268 57D_HHLGOFPG RHHPG RLGL\ RMGM\ RGLRLQKPL RLMKPITGW RLPJSGW RNQORPT
QTQSPRNQ RTITZ RTIUJUZ RUJ[J R[J[Z RZJ[I\J\Z RUY[Y
 3271 72D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RWGXFVFVQUR RWGWQVSURSQ RRKPO RRKSLPO RZK[L\N]N]M\LZK R[RXVUYR[ R[R\S
WXTZR[O\
 3272 62D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RRHSITKUKUJTIRH RQNROSQTQTPSOQN RYGZFXFX\ RYGY\ RPV]T\S[T
 3273 76D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RVHWGUFUNTSSVQYN\ RVGVPUTTVRYN\ RVNWRXUZY\\][ RWRYV[Y][ RRMQOPPPQQQRO
RM R[LWQ R[L\MWQ
 3275 65D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RRG\G[FZG RVGV\ RWGW\ RSJRMQO RSJTKQO RYJZL[O\O\N[LYJ RQR]R[QZR
 3280 73D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RSFQKOO RSFTGSIOO RQL]L[KZL RVLVZU[ RWLWZV\U[SZ RSQRTPX RSQTRPX RYQ[T
\W]W]V[SYQ
 3285 75D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RRFRN RRFSGSN RSGZG RZGZN RYGZF[G[N RSMZM RQQ]Q[PZQ RVQV[ RWQW[ RQV\V
[UZV RP[][[ZZ[
 3294 92D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RPIUH[F]G RPIXH]G RQKRNSNSMQK RVKWNXNXMVK R\J[N R\J]K[N RQPQ\ RQPRPR\
 RUPU\ RUPVQV\ RVQ[Q R[Q[\ RZQ[P\Q\\ RVV[V RV[[[
 3295 86D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RRIVHZF[G RRI[G RVHV[ RWHW[ RQK]K\J[K RQMQT RQMRNRT RRN[N R[N[T RZN[M
\N\T RRQ[Q RQT\T RQW\W[VZW RP[][\Z[[
 3306 98D_GHMFNG RGHNG RJGJ\ RKGK\ RGLOLNKML RJOIRGV RJRGV RLQMRNTOTOSNR
LQ RVGWFUFUN RVGVN RPH]H[GZH RQK[KZJYK RPN]N[MZN RQPQZ RQPRQRZ RRQYQ RYQ
YZ RXQYPZQZZ RRTYT RRWYW RQZZZ RT[SZN] RT[N] RXZ[\\]]]]\[[XZ
 3313 60D_RIRGSFQFQI RIHHJGKGLHLIJIH RII\I RZI[H]JZK R[HZK R\IZKYL RMPLT
KVIY RNQLU RMPOQNSKWG[ RTNTPUTVVXY[[]Z RXX[Z RTPUSWVYX]Z
 3314 95D_RHRGSFQFQH RIGHIGJGKHKIIIG RIH\H RZH[G]IZJ R[GZJ R\HZJYK RNHNJ
MMKOIP ROHOJNMLOIPGP RTHTNUO\O]N\M RUHUMVN[N\M]K RPQQPOPOSNWMYK[I\ RPQPS
OWNYL[I\G\ RISTS RSSTRVSUU RTSTZU[\[]Z\Y RUSUYVZ[Z\Y]W
 3317 78D_RHRGSFQFQH RIGHIGJGKHKIIIG RIH\H RZH[G]IZJ R[GZJ R\HZJYK RNHNJ
MMKOIP ROHOJNMLOIPGP RTHTNUO\O]N\M RUHUMVN[N\M]K RHT\TZRXT RXT[S RQTQ[ R
RTR[ RG[][[YY[ RY[\Z
 3325 99D_RGRFSEQEQG RIFHHGIGJHJIHIF RIG\G RZG[F]HZI R[FZI R\GZIYJ RNGMJ
LL RNGOHNJLLJMHM RTGTLUM\M]L\K RUGUKVL[L\K\J RGP]P[OZP ROPNT RPPOR RQPNT
 RITYT RITKUYT RVRXSZU[U[TYSVR RQTQ[ RRTR[ RIX[XZWYX RG[][[ZZ[
 3343 39D_RGSFQFQL RRGRL RHL\LZJXL RXL[K RKOLRMXNWNUMRKO RWNTZ RWNXPTZ R
G[][[YY[ RY[\Z
 3366 64D_KFJJIMGR RLGKI RKFMGKKGR RJLRLPJNL RNLQK RLLL\ RMLM\ RUFTJSMQR
 RVGUI RUFWGUKQR RTL]L[JYL RYL\K RWLWXVZU[ RWYWZV[ RXLXZW\V\U[SZ
 3385 92D_LEJEIGGJ RLEGJ RJGQGPFOG RLGMJNJNILG RWEUETGRJ RWERJ RUG]G[FZG
 RWGXJYJYIWG RQLQ\ RRLR\ RILYL RYLYQ RXLYKZLZQ RIOHU RIOJPIU RJPYP RITZT
 RYTZS\TZV RZTYYXZ R[TZYY[XZVY RPTMWIZ RQUNWIZG[
 3396 79D_LEJEIGGJ RLEGJ RJGQGPFOG RLGMJNJNILG RWEUETGRJ RWERJ RUG]G[FZG
 RWGXJYJYIWG RRLSKQKQQ RRLRQ RJNZNYMXN RGQ]Q[PZQ RUQUZT[ RVQVZU\T[RZ RHT
\TZSYT RLVMWNYOYOXNWLV
 3397 75D_LEJEIGGJ RLEGJ RJGQGPFOG RLGMJNJNILG RWEUETGRJ RWERJ RUG]G[FZG
 RWGXJYJYIWG RRLSKQKQ\ RRLR\ RJMXM RXMXS RWMXLYMYS RGP]P[OZP RJSYS RIVZV
YUXV RGY]Y[XZY
 3415 88D_LEJEIGGJ RLEGJ RJGQGPFOG RLGMJNJNILG RWEUETGRJ RWERJ RUG]G[FZG
 RWGXJYJYIWG RKKKU RKKLLLU RLLXL RXLXU RWLXKYLYU RLOXO RLRXR RKUYU ROUOW
NZL\J] RPUPWOZM\J] RTUT] RUUU] RGX]X[WZX
 3416102D_LEJEIGGJ RLEGJ RJGQGPFOG RLGMJNJNILG RWEUETGRJ RWERJ RUG]G[FZG
 RWGXJYJYIWG RRLRKSJQJQL RIKHMGNGOHOIMIK RIL\L RZL[K]MZN R[KZN R\LZNYO R
KOK\ RKOLPL\ RLPVP RVPVT RUPVOWPWT RLTWT RLWXW RXWX\ RWWXVYWY\ RL[X[
 3458147D_LEJEIGGJ RLEGJ RJGQGPFOG RLGMJNJNILG RWEUETGRJ RWERJ RUG]G[FZG
 RWGXJYJYIWG RHMQMPLOM RMMMLLLLM RIMJPKPKOIM RNMMP RNMONMP RGPRPQOPP RIR
I\ RIRJSJ\ RJSOS ROSOZN[ RNSORPSPZO\N[LZ RJUOU RJWOW RTLTO RTLULUO RUM]M
\L[M RTO[O RZOZR R[O[R RUR[R RTQT[U\]\]Z]X RTQURUZV[\[]Z RUT[TZSYT RUV[V
ZUYV RUX[XZWYX
 3461 55D_RHSGQFQ\ RRGR\ RJILKMMNMNLMKJI RXHTO RXHYITO RGO]O[MYO RYO\N R
QOPRNULWHZ RQROUMWJYHZ RSPTSVVXX[Z]Y RTSWVZX]Y
 3468 70D_LGMFKFK\ RLGL\ RGHHLILIKGH ROHML ROHPIML RFNQNPMON RKOISGV RKQ
GV RMQNROTPTPSORMQ RYGZFXFX\ RYGY\ RSHTIUKVKVJUISH RRNSOTQUQUPTORN RQV]T
\S[T
 3471 74D_LGMFKFK\ RLGL\ RGHHLILIKGH ROHML ROHPIML RFNQNPMON RKOISGV RKQ
GV RMQNROTPTPSORMQ RWGXFVFVL RWGWL RRL\L[KZL RSNTVTYUYUWTRSN RZNXY RZN[O
XY RP[][\Z[[
 3472 75D_LGMFKFK\ RLGL\ RGHHLILIKGH ROHML ROHPIML RFNQNPMON RKOISGV RKQ
GV RMQNROTPTPSORMQ RWGXFVFVS RWGWS RWL\L[KZL RRRR\ RRRSSS\ RSSZS RZSZ\ R
YSZR[S[\ RS[Z[
 3492 60D_QFNK RQFRGNK RKILJNMOMOLNKKI RVIQP RVIWJQP RHQZP RHQJRZP RYMZO
[R\R\Q[OYM RQQQ\ RRQR\ RMTJXHZ RMTNULWHZ RUTWVYYZYZXYWUT
 3496109D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RSGSTRXQZ RTGTTSXQZO[ R
TKUQVTWVYY\[]Z RWVYX]Z ROGYG RYGWO RXGYFZGXO RXN]N R\M[QZTYVWY R[N\M]N\R
[TYWWYT[R\
 3509 97D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RWGXFVFVZW[\[]Z\Y RWGWY
XZ[Z\Y]W RQJWI[H]I RQJ]I RRMRU RRMSMSU RSTZT RZMZU RZM[M[U
 3510103D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RSGSY RSGTHTY RTHXG[F]G
 RTH]G RPYYX RPYQZYX RXGXPYVZY[[\\]\][\Y R[Z\[ RYGYPZV[Y\Y]V RTO]O\N[O
 3511 83D_RFSEQEQM RRFRM RHG\GZFYG RJJYJXIWJ RGM]M[LZM RQNOQ RQNROOQ RLP
MQNSOSORNQLP RVORU RVOWPRU RHUZU RHUJVZU RYSZT[V\V\U[TYS RQUQ] RRUR] RLX
JZG\ RLXMYG\ RVXYZ[\\\\[[ZYYVX
 3520 85D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RSFS[ RSFTGT[ RTGYG RYG
Y[ RXGYFZGZ[ RTMYM RTTYT RP[][\Z[[
 3521107D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RWFUFTISKQN RWFQN RTI\I
 R[HZJXMUQ RZI[H\IYMUQRS RTIUKWNZQ\R]Q RWNZP]Q RVSWTXVYVYUXTVS RSXWZZ\[\
[[YZSX
 3522 84D_JFHK RJFKGHK RGJHMIMILGJ RLJIQ RLJMKIQ RFQMQ RFQGRMQ RMONROROQ
MO RJQJ\ RKQK\ RHTGX RHTIUGX RKTLUMWNWNVMUKT RQGQ\ RQGRHR\ RRH[H R[H[\ R
ZH[G\H\\ RVHVZ RWHWZ RRQ[Q RRZ[Z
 3523102D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RSGZG RZGYJXLUP RYGZF[G
ZJXMUPRR RTHUKWNZP\Q]P RUKWMZO]P RWSXRVRV[ RWSW[ RSV[VZUYV RQ[][\Z[[
 3537110D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RVFUITKRN RVFWGVITLQO R
WGXJZM\O]N RWGXIZL]N RTOYOXNWO RQT]T\S[T RVTT[ RVTWUT[ RP[[Z RP[R\[Z RZW
[Y\\]\][\YZW
 3539111D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RVFTFSIRKPN RVFPN RTHZH
 RYGWK RXHYGZHWK RVLVR RWLWR RRKRZS[\[]Z\Y RRKSLSYTZ[Z\Y]W RSLZL RZLZS R
YLZK[L[S RSRZR
 3540 95D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RWGXFVFVQ RWGWQ RQK]K\J
[K RRQ\Q[PZQ RRTR\ RRTSUS\ RSUZU RZUZ\ RYUZT[U[\ RS[Z[
 3543105D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RTFTK RTFUGUK RUGZG RZG
ZK RYGZF[G[K RTK[K RSMS\ RSMTNT\ RTN[N R[N[ZZ[ RZN[M\N\Z[\Z[XZ RTR[R RTV
[V
 3544122D_JFHK RJFKGHK RGJHMIMILGJ RLJIQ RLJMKIQ RFQMQ RFQGRMQ RMONROROQ
MO RJQJ\ RKQK\ RHTGX RHTIUGX RKTLUMWNWNVMUKT RWGXFVFVM RWGWM RQI]I\H[I R
RM\M[LZM RROQQPRPSQSRQRO RRP[P RZP[O]Q[R R[P[R R\P[RZS RTSTUSXRZ RTSUSUU
TXRZP[ RXSXZY[\[]Z\Y RXSYSYYZZ[Z\Y]W
 3567127D_JFHK RJFKGHK RGJHMIMILGJ RLJIQ RLJMKIQ RFQMQ RFQGRMQ RMONROROQ
MO RJQJ\ RKQK\ RHTGX RHTIUGX RKTLUMWNWNVMUKT RSFQJOM RSFTGOM RXFYIZK\M]L
 RYI[K]L RUKSQ RUKVLSQ RQQZP RQQRRZP RYNZO[Q\Q\P[OYN RRURZS[Y[ZZYY RRUSU
SYTZXZYYYW RPXNZN[O[PX RUSVVWVWUUS R[V\Y]Y]X[V
 3579124D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RVFUFUL RVFUL RRIYI RYI
YL RXIYHZIYL RQL]L\K[L RSNSR RSNTOTR RTOZO RZOZR RYOZN[O[R RSR[R RWSW\ R
WSXSX\ RSTSX RSTTUTX RTU\U[TZU RPX]X[WZX
 3580129D_KFIK RKFLGIK RGJHKIMJMJLIKGJ RNJJQ RNJOKJQ RGQNQ RGQHRNQ RNOOR
PRPQNO RKQK\ RLQL\ RITGX RITJUGX RMTNUOWPWPVOUMT RWFVFUH RWFUH RRGRP RRG
SHSP RSHZH RZHZP RYHZG[H[P RSLZL RRP[P RVPVZU[ RWPWZV\U[SZ RQTUT RTSSVRX
 RTSUTTVRXPY RWPXTZW\Y]X RWPXSYU[W]X R\RYU R\R]SYU
 3581131D_JFHK RJFKGHK RGJHMIMILGJ RLJIQ RLJMKIQ RFQMQ RFQGRMQ RMONROROQ
MO RJQJ\ RKQK\ RHTGX RHTIUGX RKTLUMWNWNVMUKT RWHWGXFVFVH RPH]H\G[H RSITL
ULUKSI RYIXM RYIZJXM RRLQNPOPPQPRNRL RRM[M RZM[L]N[O R[M[O R\M[OZP RWPXO
VOV\ RWPW\ RQRQ[ RQRRSR[ RRS[S R[S[ZZ[ RZS[R\S\Z[\Z[XZ
 3597126D_JFHK RJFKGHK RGJHMIMILGJ RLJIQ RLJMKIQ RGQLQ RGQHRLQ RLPMRNRNQ
LP RJQJ\ RKQK\ RHUGY RHUIVGY RLUMXNXNWLU RRFOL RRFSGOL RUFVJWJWIUF RZFYK
 RZF[GYK RSKQPOT RSKTLQQOT RQQQ\ RROR\ RTL]L\K[L RXLXZ RYLY[ RUQUVTZS\ R
UQVQVVUYS\ RYS]S\R[S RVVWYX[Z\\\][ RWYXZZ[][
 3644 86D_HEHI RHEIFII RIFZF RZFZI RYFZE[F[I RNFNI ROFOI RTFTI RUFUI RHI
[I RQIPO RRIQL RSIPO RGL]L[KZL RMNMY RMNNONY RNOWO RWOWY RVOWNXOXY RNRWR
 RNUWU RNXWX RHOH\ RHOIOI\ RI[][[ZZ[
 3656 48D_LFMGNJOJOINGLF RWFUFTK RVFUH RWFTK RQKQ] RRKR] RGK]K[IYK RYK\J
 RIP[PYNWP RWPZO RGV]V[TYV RYV\U
 3658 67D_MENHOHOGME RUETH RUEVFTH RGH]H[GZH RQHQP RRHRP RJLZLYKXL RGP]P
[OZP RQQPUOWMYJ[G\ RQQRRQUPWNYK[G\ RGT]T[SZT RSTUXWZY[\\][ RSTUWWYYZ][
 3662 62D_MFNIOIOHMF RUFTI RUFVGTI RQIQQ RRIRQ RGI]I[HZI RJMZMYLXM RGQ]Q
[PZQ RNQMTLVJYH[ ROQNTMVKYH[ RSUS[ RTUT[ RNUZUYTXU RL[][[ZZ[
 3665 77D_LFMGNIOIOHNGLF RWFUFTI RWFTI RHI\IZHYI RQIQO RRIRO RILYLXKWL R
GO]O[NZO RNOLSJVGZ RNOOPMSJWGZ RORMQM\ RNRN\ RNRWR RVRWQYRXT RWRW\ RXRX\
 RNUWU RNXWX RN[W[
 3673 78D_GGOG RNGOFQGPI ROGOXNZM[ ROYOZN[ RPGPZO\N\M[KZ RHKILJNKNKMJLHK
 RGTNQ RGTHUNQ RQG[G RZG[F]G\I R[G[XZZY[ R[Y[ZZ[ R\G\Z[\Z\Y[WZ RTKULVNWN
WMVLTK RRTZQ RRTSUZQ
 3676108D_GGOG ROGOM RNGOFPGPM RLGJIGK RNGGK RMJIMGN RMJNKGN RSG[G R[G[M
 RZG[F\G\M RZGVISK RZGSK RYJUMSN RYJZKSN RRQRPSOQOQQ RGQ]Q[PZQ RMQKTIV R
OQMSIV RMSNTOVPVPUOTMS RWQUTSV RYQWSSV RWSXTYVZVZUYTWS RRXSWQWQ\ RRXR\ R
GY]Y[XZY
 3680115D_GFOF ROFOK RNFOEPFPK RIGLILHIG RGJNJ RGJHKNJ RSF[F R[F[K RZF[E
\F\K RUGXIXHUG RSJZJ RSJTKZJ RQMQS RRMRS RKLKS RKLLMLS RLMWM RWMWS RVMWL
XMXS RLPWP RKSXS RNSNY ROSOY RTSTY RUSUY RIV[VZUYV RGY]Y[XZY RO[MZJ\H] R
O[L\H] RUZW[Z][][\Y[UZ
 3683 64D_QGRFPFPN RQGQN RIIVIUHTI RGN]N[MZN RYGWJTNPRLUIW RYGZHVMRQNTIW
GX RPSQROQOZP[\[]Z\X R[Z\Z\Y RPRPYQZZZ\X]U RPVSUWSYRZS RPVUUXTZS
 3684 72D_PGQFOFOM RPGPM RJIUITHSI RGM]M[LZM RWGUJRNNRJUGW RWGXHTMORLTGW
 RPRNQMW RORNW RPRXPYQ RORPRYQ RNUXU RWUXTZUXW RXUWYVZT[ RWZV[U[ RYUXYW[
V\U\T[RZ
 3685 59D_QGRFPFPM RQGQM RIIUITHSI RGM]M[LZM RXGUKRNNQIT RXGYHTMPPMRITGU
 ROQMPM\ RNQN\ RNQXQ RWQXPZQYS RXQX\ RYQY\ RNVXV RN[X[
 3697 34D_HH\HZFXH RXH[G RLHLW RMHMW RWHW\ RXHX\ RMMWM RMRWR RGX]V[TYV R
YV\U
 3699 61D_GGTGRFQG RJGJX RKGKW RPGP\ RQGQ\ RKLPL RKQPQ RGXPV RGXHYPV RQJ
\J R[IZNYQWVUY RZJ[I\J[NZQXUUYR\ RTKUPVSWUYX\[]Z RUPWTYW]Z
 3719 67D_RFSEQEQS RRFRS RJGWG RVGWFYGXI RWGWM RXGXM RGJ]J[IZJ RJMXM RJP
YPXOWP RGS]S[RZS RMVKUK\ RLVL\ RLVWV RVVWUYVXX RWVW\ RXVX\ RLYWY RK\X\
 3724 78D_JIHHH\ RIII\ RIIZI RYIZH\I[K RZIZXYZX[ RZYZZY[ R[I[ZZ\Y\X[VZ R
RGSFQFPJNNLQ RRGQJPLNOLQJR RQKSLVNWOXOXNWMULQK RRPSOQOPROTLX RRPQROULXJY
 RQSSTVVWWXWXVWUUTQS
 3727 60D_RFPFOIMMKPHT RQFOJ RRFQHNMKQHT RGI]I[GYI RYI\H RMNM\ RNMN\ RNM
XM RWMXLZMYO RXMXWWZV[ RXYXZW[ RYMYZX\W\V[TZ RNQXQ RNUXU
 3749 86D_IFIUHYG[ RIFJGJUIXG[ RJGMG RMGMYLZ RLGMFNGNYM[KY RJMMM RJSMS R
TFRFQKPN RTFPN RSHZH RYHZG\H[J RZHZUYV R[H[UZWYVWU RQMVM RVMVS RUMVLWMWS
 RQQQZR[\[]Z\Y RQQRRRYSZ[Z\Y]W RRRVR
 3785 81D_KGLFJFJU RKGKU RPGQFOFOU RPGPU RGISIRHQI RKMOM RKQOQ RGUSURTQU
 RJWIYG\ RJWKXG\ ROWPXQZRZRYQXOW RUFUTTYS[ RUFVGVTUXTZR\ RVG[G R[G[ZZ[ R
ZG[F\G\Z[\Z[XZ RVM[M RVS[S
 3788 82D_MGNFLFLL RMGML RGIRIQHPI RHKHS RHKILIS RILPL RPLPS ROLPKQLQS R
IOPO RIRPR RLRL\ RMRM\ RGVRVQUPV RUFUSTWRZP\ RUFVGVSUWSZP\ RVG[G R[G[ZZ[
 RZG[F\G\Z[\Z[XZ RVL[L RVQ[Q
 3837 52D_KGIFI\ RJGJ\ RJG\GZEXG RXG[F RQGQM RRGRM RJMYM RXMYL[MZO RYMYU
 RZMZU RJTYT RQTQ[ RRTR[ RJ[][[YY[ RY[\Z
 3841 37D_REPEOH RREOH RLHJGJ\ RKHK\ RKHYH RXHYG[HZJ RYHY\ RZHZ\ RKNYN R
KTYT RKZYZ
 3845 55D_GG]G[EYG RYG\F RQGMO RQGRHMO RIOXN RIOKPXN RULXNZP[P[OZNXMUL R
RQSPQOQ[ RRPR[ RIU[UYSWU RWUZT RG[][[YY[ RY[\Z
 3855 50D_HIOHTGWFYH RQHXG RHIYH RQHQS RRHRS RGM]M[KYM RYM\L RMSKRK\ RLS
L\ RLSWS RVSWRYSXU RWSW\ RXSX\ RL[W[
 3856 62D_GILHOGQFSG RGINHSG RMHMS RNHNS RGMTMSLRM RIRI[ RIRJSJ[ RJSQS R
QSQ[ RPSQRRSR[ RJZQZ RWHXGVFVZW[\[]Z\X R[Z\Z\Y RWGWYXZZZ\X]U
 3860 82D_GHKGNFPG RGHPG RKGKS RLGLS RGMPMOLNM RHRH[ RHRISI[ RISNS RNSN[
 RMSNROSO[ RIZNZ RWGXFVFVJ RWGWJ RRJ\J[IZJ RSKTOUOUNSK RYKXO RYKZLXO RQP
]P\O[P RVPV\ RWPW\ RRU\U[TZU
 3863 68D_RFPFOI RRFOI RMIKHKSJWIYG\ RLILSKWIZG\ RLIWI RVIWHYIXK RWIWXVZ
U[ RWYWZV[ RXIXZW\V\U[SZ RPKQLRNSNSMRLPK RGP]P[NYP RYP\O RPRQSRUSUSTRSPR
 3865108D_MFLI RMFNGLI RIHIUHYG[ RIHJIJUIXG[ RJIPI RPIPZO[ ROIPHQIQZP\O[
MZ RLKMNNNNMLK RGQSO RGQHRSO RLSMVNVNULS RUFUJTMSO RUFVGVJUMSO RVGYG RYG
YMZN]N]J RXGYFZGZL[M\M]L RSQZQ RZQYTXVUZ RYQZP[QZTXWUZR\ RTRUUWXZZ\[]Z R
UUWWZY]Z
 3873 94D_MFLI RMFNGLI RIHIVHZG\ RIHJIJVIYG\ RJIPI RPIPZO[ ROIPHQIQZP\O[
MZ RLKMNNNNMLK RGQSO RGQHRSO RLSMVNVNULS RVGUKTNSP RVGWHVKUMSP RYGZK[N\P
]O RZK\N]O RTRT\ RTRUSU\ RUS[S R[S[\ RZS[R\S\\ RU[[[
 3885 63D_RGRFSEQEQG RMGKFKZ RLGLZ RLGWG RVGWFYGXI RWGWR RXGXR RLLWL RLQ
WQ RPQQTSWUYX[[\][ RPQQSSVTWWYYZ][ RG[SX RG[H\SX RXSTW RXSYTTW
 3889 66D_OFMFKJIM ROFKKGO RMIUI RTIUHWJTK RUITK RVITKRM RRMRR RSMSR RMM
KLKZL[\[]Z\X R[Z\Z\Y RLMLYMZZZ\X]U RLMYM RXMYL[MZO RYMYS RZMZS RLRYR
 3909 65D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RNLLPJSGW RNLOMMPJTGW
 RLQL[ RMPM[ RUNVMTLTZU[\[]Z\X R[Z\Z\Y RUMUYVZZZ\X]U RZOUS RZO[PUS
 3926 59D_OFPENENJ ROFOJ RUFVETETJ RUFUJ RGG]G[FZG RQKOOLSGX RQKRLQNNRKU
GX RGO]O[NZO RLSL\ RLSMTM\ RMTWT RWTW\ RVTWSXTX\ RM[W[
 3939 59D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RLKJJJT RKKKT RKKXK R
WKXJZKYM RXKXT RYKYT RKOXO RKSXS RQSQ\ RRSR\ RGW]W[VZW
 3940 77D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RQJPLNOKR RQJRKPNNPKR
GT RRKTNVPYR\S]R RTNWPYQ]R RRRSQQQQ\ RRRR\ RLTXTWSVT RMVLXJZ RMVNWMXJZH[
 RUVWWZZ[Z[YZXXWUV
 3956 73D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RKJJMHRGT RKJLKKMGT R
JOJ\ RKMK\ RML]L[KZL RYLYZX[ RZLZZY\X[VZ ROOOW ROOPPPW RPPTP RTPTW RSPTO
UPUW RPVTV
 3981 92D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RMJIOGQ RMJNKLMGQ RML
ZL RYLZK\L[N RZLZ[Y\ R[L[[Z]Y\W[ RROSNQNQ[ RROR[ RLOMPNROROQNPLO RVOTS R
VOWPTS RJTXTWSVT RPTKXHZ RQUNWHZ RTVUWVYWYWXVWTV
 4001 86D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RQJQP RQJRJRP RROWO R
WJWP RWJXJXP RHL\L[KZL RKKKS RKKLKLS RLR[RZQYR RQRQ\ RRRR\ RGU]U[TZU RPU
MXJZ RQVNXJZG[ RRUUXXZ[[]Z RSVVXYY]Z
 4002111D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RJKYK RVKWJYKVL RWJVL
 RVLSN RROSNQNQSPT RRORSQUPTNS RSNUQXT[V]U RUQXSZT]U RGONO RMNLPJSGV RLO
MNNOLRJTGV RZNVQ RZN[OVQ RJWXWWVVW RIYG[G\H\IY RMYN\O\O[MY RSYT\U\U[SY R
YYZZ[\\\\[[ZYY
 4074114D_OFPENENI ROFOI RUFVETETI RUFUI RGG]G[FZG RQIPL RQIRJPL RNKNS R
NKOLOS ROLTL RTLTS RSLTKULUS ROOTO RORTR RHKILJNKNKMJLHK RZKVO RZK[LVO R
GQMO RGQHRMO RWOYP[R\R\QZPWO RQRQ\ RRRR\ RGU]U[TZU RPUNWKYG[ RQVNXJZG[ R
SUUXXZ[[]Z RSUUWYY]Z
 4109 86D_RFSEQEQPRQ\Q]P\O RRFROSP[P\O\N RRGZGYFXG RIIIUHYG[ RIIJJJUIXG[
 RJJ\J RZJ[I]K[L R[I[L R\J[LZM RJNXMWLVM RMVNYOYOXMV RRUSTQTQ[ RRUR[ RVU
WTUTU[ RVUV[ RZVWZ RZV[WWZ RK[][\Z[[
 4115 47D_RGSFQFQZ RRGRZ RLKJJJT RKKKT RKKXK RWKXJZKYM RXKXT RYKYT RKSXS
 RG[YY RG[I\YY RWVYX\\]\][[YWV
 4205 45D_SEQEOI RSEOI RLIJHJZ RKIKZ RKIYI RXIYH[IZK RYIYZ RZIZZ ROIOZ R
PIPZ RTITZ RUIUZ RGZ]Z\Y[Z
 4213 54D_MFKHGK RMFNGGK RMKKNGS RMKNLGS RKOK\ RLNL\ ROG[GYEWG RWGZF ROM
]M[KYM RYM\L RXMXXWZV[ RXYXZW[ RYMYZX\W\V[TZ
 4214 66D_RGSFQFQK RRGRK RHK\KZIXK RXK[J RQKPMNPKTGX RQKRLPOMSKUGX RNQNZ
 ROPOY RJ[UW RJ[K\UW RSLTPUSVUXX[[]Z RYX[Z RTPURWUZX]Z RZOVT RZO[PVT
 4234 94D_MGNFLFLO RMGMO RGGHHIJJJJIIHGG RGMKL RGMHNKL RVGWFUFUN RVGVN R
OJ]J[IZJ RPN[NZMYN RRRRQSPQPQR RGR]R[QZR RPRNTJWGY RRRNUKWGY RRRSUUXWZ[\
][ RSUVXYZ][ RMVMZ RNUNZ RJ[TX RJ[K\TX RYTVW RYTZUVW
 4255116D_KGLFJFJJ RKGKJ RGJNJ RMILKJNGR RLJMINJKNGR RJOJ\ RKNK\ RNOKR R
NOOPKR RLRMSNUOUOTNSLR RUFSFQJ RUFQJ RSH]H[GZH RRJRQ RRJSKSQ RSKZK RZKZQ
 RYKZJ[K[Q RSNZN RRQ[Q RTRPX RTRUSPX RTT[T RZSYUWXUZS[P\ RYTZS[TYWWYT[P\
 RTTUWWZY[\\][ RUWWYYZ][
 4273 57D_GG]G[EYG RYG\F ROGOPNTMV RPGPPOSMVKX RSGSTTUWUXTWS RTGTSUTVTWS
WQ RJMHLH\ RIMI\ RIMZM RYMZL\M[O RZMZ\ R[M[\ RIZZZ
 4274 82D_GG]G[EYG RYG\F ROGOO RPGPO RTGTO RUGUO RJJJO RJJKKKO RKKYK RYK
YO RXKYJZKZO RJOZO RGS]S[QYS RYS\R RQOLV RQORPMVLV RVSTVQYN[K\ RVSWTRYO[
K\I\ RMVQWVYY[Z\[\[[ZZVXRWMV
 4284 61D_MGKFKT RLGLT RLGWG RVGWFYGXI RWGWT RXGXT RLKWK RLOWO RLSWS RNS
MWLYJ[H\ ROSNWMYK[H\G\ RSSS[T\\\][\Y R[[\[\Z RTSTZU[Z[\Y]V
 4301 72D_OFMFKJIM ROFKKGO RMHUH RTHUGWITJ RUHTJ RVHTJRL RMLKKKUJYI[ RLL
LVKYI[G\ RLLYL RXLYK[LZN RYLYXXZW[ RYYYZX[ RZLZZY\X\W[UZ RRLRV RSLSV RLQ
YQ RLVYV
 4306104D_JEHKGM RJEKFJHGM RJHOH RNGMK RMHNGOHMK RIJITHYG[ RIJJKJTIXG[ R
JKQK RQKQZP[ RPKQJRKRZQ\P[NZ RMKMS RNKNS RJOQO RJSQS RRG\G R\G[KZL R[G\F
]G\K[MYK RWGVKUM RXGWJUM RXNX\ RXNYNY\ RUOTT RUOVPTT RUQ\Q[PZQ RUV]V\U[V
 4309 44D_KGYGWFVG RHJ\JZIYJ RKMYMWLVM RKPYPWOVP RMTKSK\ RLTL\ RLTWT RVT
WSYTXV RWTW\ RXTX\ RL[W[
 4312 54D_HGPGOFNG RGJQJPIOJ RHMPMOLNM RHPPPOONP RHSH\ RHSITI\ RITOT ROT
O\ RNTOSPTP\ RI[O[ RXHYGWFW\ RXGX\ RSN]N\M[N
 4318 73D_HGNGMFLG RGJOJNIMJ RHMNMMLLM RHPNPMOLP RHSH[ RHSITI[ RITMT RMT
M[ RLTMSNTN[ RIZMZ RRHZH RYHZG\H[J RZHZP R[H[P RTORNRZS[\[]Z\Y RSOSYTZ[Z
\Y]W RSOZO
 4341 79D_HGMGLFKG RGJNJMILJ RHMMMLLKM RHPMPLOKP RHSH\ RHSITI\ RITLT RLT
L[ RKTLSMTM[ RIZLZ ROG]G[EYG RYG\F RVGV[ RWGW[ RSPTORNR[ RSOS[ RWP\PZNXP
 RXP[O RO[][[YY[ RY[\Z
 4358 83D_HGNGMFLG RGJOJNIMJ RHMNMMLLM RHPNPMOLP RHSH[ RHSITI[ RITMT RMT
M[ RLTMSNTN[ RIZMZ RQIUHXGZF\G RQIWH\G RVHVS RWHWS RQM]M[LZM RRRR[ RRRSS
S[ RSSZS RZSZ[ RYSZR[S[[ RSZZZ
 4374 92D_HGNGMFLG RGJOJNIMJ RHMNMMLLM RHPNPMOLP RHSH[ RHSITI[ RITMT RMT
M[ RLTMSNTN[ RIZMZ RPG]G[FZG RUGSP RVGTP RQKXK RXKWP RWKXJYKXP RPP]P[OZP
 RTTRSR[ RSTS[ RSTYT RXTYS[TZV RYTY[ RZTZ[ RSZYZ
 4375109D_HGNGMFLG RGJOJNIMJ RHMNMMLLM RHPNPMOLP RHSH[ RHSITI[ RITLT RLT
L[ RKTLSMTM[ RIZLZ RVGWFUFUM RVGVM RPI]I[HZI RQM[MYLXM RQOPQOROSPSQQQO R
QP[P RZP[O]Q[R R[P[R R\P[RZS RSSSURYQ[ RSSTSTUSXRZP\ RWSW[X\\\][\Z RWSXS
XZY[[[\Z]Y
 4384 88D_HGNGMFLG RGJOJNIMJ RHMNMMLLM RHPNPMOLP RHSH\ RHSITI[ RITMT RMT
M\ RLTMSNTN\ RI[M[ RTFSIQN RTFUGQN RYFWL RYFZGWL RRLR\ RSLS\ RRL]L[KZL R
WLW[ RXLX[ RSQ\Q[PZQ RSV\V[UZV RS[][[ZZ[
 4391103D_GGLGKFJG RFJMJLIKJ RGMLMKLJM RGPLPKOJP RGSG\ RGSHTH\ RHTKT RKT
K[ RJTKSLTL[ RHZKZ RUFSJPM RUFVGTJRLNN RVHXKZM\N]M RVHXJ[L]M RSNXNWMVN R
OPO\ ROPPQP\ RPQ[Q R[Q[ZZ[ RZQ[P\Q\Z[\YZ RSQS[ RTQT[ RWQW[ RXQX[ RPU[U
 4458 76D_NGLFKHIKGM RMGKI RNGKJGM RUFWGYIZK[K\J[IXGUF RZI[J RQJPLMPJRGS
 RQJRKPNNPKRGS RRKTNVPYR[S]R RRKUNXPZQ]R ROUMTM\ RNUN\ RNUVU RUUVTXUWW R
VUV\ RWUW\ RN[V[
 4465 55D_IG[GYEWG RWGZF RMLKKKS RLLLS RLLWL RVLWKYLXN RWLWS RXLXS RLRWR
 RLTMVNYOYOXNVLT RWTTZ RWTXUTZ RG[][[YY[ RY[\Z
 4472107D_PENELHJJ RPENGJJGL RNGVG RUFTHRK RTGUFVGRK RRKRO RSKSO RKJKO R
KJLKLO RLKYK RYKYO RXKYJZKZO RKOZO RQONQLR RSOOQLRHS RPQRTSWS[R]Q\O[ RPQ
QSRWR[Q\ RQSNULV RQTLVHW RRWLZ RRXLZH[ RSOTSVWXY[[]Z RTSVVXXZY]Z RZQVU R
ZQ[RVU
 4486 48D_MGKFKW RLGLW RLGXG RWGXFZGYI RXGXW RYGYW RLLXL RLQXQ RLVXV RNX
I[G\ RNXOYMZG\ RUXYZ\\]\][\ZYYUX
 4488 70D_PFNFLIHN RPFHN RNHVH RUHVGXIUJ RVHUJ RWHUJSL RNLLKLY RMLMY RML
YL RXLYK[LZN RYLYY RZLZY RMPYP RMTYT RMXYX RP[NZK\H] RP[M\H] RVZX[[]\]\\
Z[VZ
 4518 99D_IFIKHMGN RIFJGJKIMGN RJGPFQG RJGQG RJJRJQIPJ RMJMN RNJNN RTFTK
SMRN RTFUGUKTMRN RUG[F\G RUG\G RUJ]J\I[J RXJXN RYJYN RKOKY RKOLPLY RLPXP
 RXPXY RWPXOYPYY RLSXS RLVXV RKYYY ROZH] ROZP[H] RUZ[]\]\\Y[UZ
 4534 72D_RGSFQFQO RRGRO RIJ[JYHWJ RWJZI RGO]O[MYO RYO\N RNONRMVLXJZG\ R
OOORNVMXKZG\ RTOTXSZR[ RTZS[ RUOUZT\S\R[PZ RIRHUFX RIRJSHVFX RWRYS[V\X]X
]W\UZSWR
 4539 55D_RGSFQFQZ RRGRZ RHJ[JYHWJ RWJZI RGO]O[MYO RYO\N RRTZTXRVT RVTYS
 RLRKUIYG\ RLRMSLUJXG\ RKULWOZS[\[]Z RLWOYSZ]Z
 4543 90D_MGNFLFLX RMGMY RIIQIPHOI RGNRNQMPN RMSQSPROS RIQIUHYG[ RIQJQJU
IXG[ RJVKXMZP[\[]Z RKXMYPZ]Z RRG\G R\G[LZM R[G\F]G\L[NYL RVGULTN RWGVKUM
SO RSPSX RSPTQTX RTQ[Q R[Q[X RZQ[P\Q\X RTW[W
 4546 61D_NGLFLO RMGMO RMGXG RWGXFZGYI RXGXO RYGYO RMNXN RRNR[ RSNS[ RST
\TZRXT RXT[S RLRKUIYG\ RLRMSLUJXG\ RKULWOZS[\[]Z RLWOYSZ]Z
 4548 77D_HFHN RHFIGIN RIGNG RNGNN RMGNFOGON RIMNM RKMKY RLMLY RHQHY RHQ
IQIY RLRPROQNR RGYPX RGYHZPX RRFR[ RRFSGS[ RSG]G[FZG RSLZL RZLZU RYLZK[L
[U RSTZT RSZ]Z[YZZ
 4561102D_HFHN RHFIGIN RIGNG RNGNN RMGNFOGON RIMNM RKMKY RLMLY RHQHY RHQ
IQIY RLRPROQNR RGYPX RGYHZPX RWFUFTISKQN RWFQN RTI\I R[HZJXMUQ RZI[H\IYM
UQRS RTIUKWNZQ\R]Q RWNZP]Q RSSS\ RSSTTT\ RTTZT RZTZ\ RYTZS[T[\ RT[Z[
 4601 65D_SFQFPH RSFPH ROHMGMU RNHNT RNHXH RWHXGZHYJ RXHXXWZV[ RXYXZW[ R
YHYZX\W\V[TZ RNLXL RNPXP RHUXS RHUIVXS R\OXSSWNZ R\O]P[RWUTWNZK[G\
 4603 82D_NFLFKI RNFKI RIHIR RIHJIJR RJIPI RPIPZO[ ROIPHQIQZP\O[MZ RJLPL
 RJOPO RGRPR RGRHSPR RPQMUJX RPSNUJXGZ RZG[FYFYXXZW[ RYYYZX[ RZGZZY\X\W[
UZ RQL]L\K[L RSOTPURVRVQUPSO
 4608 51D_RGSFQFQ\ RRGR\ RHI\IZGXI RXI[H RLLJKJU RKLKU RKLXL RWLXKZLYN R
XLXU RYLYU RKPXP RKTXT RGX]X[VYX RYX\W
 4610 72D_MGNFLFL\ RMGM\ RGIRIQHPI RHLHT RHLIMIT RIMPM RPMPT ROMPLQMQT R
IPPP RISPS RGWRWQVPW RVGWFUFURTWSY RVGVRUVSYQ[ RRMYL RYLYZZ[][]W RXLYKZL
ZY[Z\Z]Y
 4615 74D_MGNFLFL\ RMGM\ RGIRIQHPI RHLHT RHLIMIT RIMPM RPMPT ROMPLQMQT R
IPPP RISPS RGWRWQVPW RSI\I[HZI RRP]P[OZP RWPUZ RWPXQUZ RRZ[Y RRZS[[Y RZV
[X\[][]Z\XZV
 4619 74D_LGMFKFK\ RLGL\ RGIPIOHNI RGKGS RGKHLHS RHLOL ROLOS RNLOKPLPS R
HOOO RHROR RGVPVOUNV RXGYFWFWZ RXGXZ RSKS\ RSKTLT\ RTL[L R[L[\ RZL[K\L\\
 RTS[S RTZ[Z
 4620 88D_MGNFLFL\ RMGM\ RGIRIQHPI RHLHT RHLIMIT RIMPM RPMPT ROMPLQMQT R
IPPP RISPS RGWRWQVPW RSGZG RZGYJXLUP RYGZF[GZJXMUPRR RTHUKWNZP\Q]P RUKWM
ZO]P RWSXRVRV[ RWSW[ RSV[VZUYV RQ[][\Z[[
 4623102D_MGNFLFL\ RMGM\ RGIRIQHPI RHLHT RHLIMIT RIMPM RPMPT ROMPLQMQT R
IPPP RISPS RGWRWQVPW RXIXGYFWFWI RSI]I\H[I RUKSN RUKVLSN RZK[L\N]N]M\LZK
 RZPYSWVTYQ[O\ RZP[QZSXVUYR[O\ RSRVP RSRTSVP RVPWTYX\\][ RVPWSXUZX][
 4630105D_LGMFKFK\ RLGL\ RGIPIOHNI RGKGS RGKHLHS RHLOL ROLOS RNLOKPLPS R
HOOO RHROR RGVPVOUNV RWFVHTKQN RWFXGVJTLQN RWGXIZL\N]M RXIZK]M RTNYNXMWN
 RRPR\ RRPSQS\ RSQ[Q R[Q[ZZ[ RZQ[P\Q\Z[\Z[YZ RUQU[ RVQV[ RXQX[ RYQY[ RSV
[V
 4633 98D_LGMFKFK\ RLGL\ RGIPIOHNI RGKGS RGKHLHS RHLOL ROLOS RNLOKPLPS R
HOOO RHROR RGVPVOUNV RRG]G\F[G RTJTP RTJUKUP RUKZK RZKZP RYKZJ[K[P RUOZO
 RSRS\ RSRTST\ RTS[S R[S[\ RZS[R\S\\ RWSW[ RXSX[ RTW[W RT[[[
 4646 53D_RGSFQFQI RRGRI RHI\IZGXI RXI[H RLJMLNPOPONNLLJ RVJTP RVJWKTP R
GQ]Q[OYQ RYQ\P RQQQ] RRQR] RIV[VYTWV RWVZU
 4660 71D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZ RLPLW RLWH[GZ RLWNZQ[\[
]Z RLWNYQZ]Z RPGTG RSGTFVGUI RTGTJSMQQNU RUGUJTMSOQRNU RUJVMWOYR\U]T RVM
XPZR]T
 4661 73D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z ROH[H RZH[G]H\J R[HZRYTXU RZSZTYU R\H\J[TZVYVXUVT RUHTLSORQPT R
VHULSPPTNV
 4671 67D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RRHPGPPOTNV RQHQPPSNV RRHVGYF[G RQHRH[G RQM]M[LZM RWMWW RXMXW
 4685 82D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RRFSITITHRF RZFXFWJ RZFWJ ROJ]J\I[J RUJUTTVSW RVJVTUVSWQW RPMPS
 RPMQMQS RQRZR RZMZS RZM[M[S
 4700 92D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKW RLPLW RKWGZ RLWH[GZ RLWNZ
Q[\[]Z RLWNYQZ]Z RVGWFUFUX RVGVX ROI]I[HZI RPLPQ RPKQLQQ RQLZL RZLZQ RYL
ZK[L[Q RPQ[Q RUQSTQV RUSTTQVOW RVSXT[W\W\V[UYTVS
 4701 82D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RVGWFUFUM RVGVM RSGQGPK RSGPK RQI[IZHYI ROM]M[LZM RQPQW RQPRQRW
 RRQYQ RYQYW RXQYPZQZW RRVYV
 4702 78D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RVGWFUFUW RVGVW ROH]H\G[H RPJPQ RPJQKQQ RQKZK RZKZQ RYKZJ[K[Q R
QNZN RPQ[Q ROT]T\S[T
 4703 96D_HGIHJJKJKIJHHG RGPJP RIPJOLPKR RJPJWGZH[KW RKPKW RKWMZP[\[]Z R
KWMYPZ]Z ROG[G RYGZF\HYH RZFYH R[GYHWI RSHTIUKVKVJUISH RQKOJOW RPKPW RPK
[K RZK[J]K\M R[K[UZV R\K\U[WZVXU RUKUW RVKVW RPO[O RPS[S
 4709 90D_HGIHJJKJKIJHHG RGPJP RIPJOLPKR RJPJWGZH[KW RKPKW RKWMZP[\[]Z R
KWMYPZ]Z RSFQFPINM RRFQH RSFNM RYFWFVJ RXFWH RYFVJ RPIPW RPIQJQW RQJ]J[I
ZJ RVJVV RWJWV RQN\N[MZN RQR\R[QZR RQV]V[UZV
 4721 88D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RVFWEUEUK RVFVK RQH[HZGYH ROK]K[JZK RRKSOTOTNRK RYKWO RYKZLWO R
OO]O[NZO RUOUX RVOVX RRRZRYQXR ROU]U[TZU
 4722 99D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKW RLPLW RKWGZ RLWH[GZ RLWNZ
Q[\[]Z RLWNYQZ]Z RPFPQOVNX RPFQGQQPUNX RQG\G R\G\J R[G\F]G]J RQJ]J RSJTN
UNUMSJ RYJXN RYJZKXN RVNVX RWNWX RQN]N\M[N RRQ\Q[PZQ RQT]T\S[T
 4723107D_HGIHJJKJKIJHHG RGPJP RIPJOLPKR RJPJWGZH[KW RKPKW RKWMZP[\[]Z R
KWMYPZ]Z RQFQN RQFRGRN RRGYG RYGYN RXGYFZGZN RUIUN RUIVJVN RVJYJ ROMOW R
OMPNPW RPN[N R[N[VZW RZN[M\N\V[XZWXV RSPSU RSPTQTU RTQWQ RWQWU RVQWPXQXU
 RSUXU
 4724 92D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RPFQGRISISHRGPF RXFWJ RXFYGWJ RNJ]J[IZJ RUJTM RWJTM RRMPLPW RQM
QW RQMYM RXMYL[MZO RYMYW RZMZW RQPYP RQSYS RQVYV
 4725 99D_HGIHJJKJKIJHHG RGPJP RIPJOLPKR RJPJWGZH[KW RKPKW RKWMZP[\[]Z R
KWMYPZ]Z RPFNHNIOIPF RPG[G RZG[F]H[H R[F[H R\G[HZI RVIWHUHUX RVIVX RPJ[J
ZIYJ RPLPS RPLQMQS RQMZM RZMZS RYMZL[M[S RQPZP RPS[S RNV]V[UZV
 4733105D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RVFWEUEUK RVFVK RQH[HZGYH ROK]K[JZK RQMQQ RQMRNRQ RRNYN RYNYQ R
XNYMZNZQ RQQZQ RUQUX RVQVX RUQRTOV RVRQUOV RVSXT[W\W\V[UYTVS R[RYT R[R\S
YT
 4750124D_IGJHKJLJLIKHIG RGPKP RJPKOMPLR RKPKWGZH[LW RLPLW RLWNZQ[\[]Z R
LWNYQZ]Z RSFSI RTFTI RWFWI RXFXI ROEOI ROEPFPI RPF[F R[F[I RZF[E\F\I ROI
\I RNL]L[KZL RPNPR RPNQOQR RQOZO RZOZR RYOZN[O[R RPR[R RURUX RVRVX RURRU
OW RVSQVOW RWTYU[W\W\VZUWT R[SYU R[S\TYU
 4789124D_GGSGRFQG RKGKNJR RLGLNKQIS RNGNQORQR ROGOPPQQQ RHKH[ RHKILI[ R
ILQL RQLQ[ RPLQKRLR[ RIVQV RIZQZ RWFVJ RWFXGVJ RSJ[J RSJTK[J R[H\K]K]J[H
 RVJVMUOTP RWJWMVOTPSP RYJYOZP]P]M RZJZO\O]N RVQUTTV RVQWRTV RVS\S R[RZT
XWUZ R[R\SZVXXUZS[ RVQWUYYZZ\[]Z RXWZY]Z
 4798128D_GGQGPFOG RJGJNIR RKGKNJQHS RMGMQNRPR RNGNPOQPQ RGKG[ RGKHLH[ R
HLPL RPLP[ ROLPKQLQ[ RHVPV RHZPZ RWEVH RWEXFVH RSGSP RSGTHTP RTH[H R[H[P
 RZH[G\H\P RWHWP RXHXP RTL[L RSP\P RTRTUSYR[ RTRURUUTXR[ RWQWZX[][]X RWQ
XQXYYZ\Z]Y R[RZRYU R[RYU RXU\U RXUYV\U R\T\V]V\T
SHAR_EOF
if test 28972 -ne "`wc -c 'hersh.or3'`"
then
	echo shar: error transmitting "'hersh.or3'" '(should have been 28972 characters)'
fi
echo shar: extracting "'hersh.or4'" '(25031 characters)'
if test -f 'hersh.or4'
then
	echo shar: over-writing existing file "'hersh.or4'"
fi
cat << \SHAR_EOF > 'hersh.or4'
 4809 86D_GHKGNFPG RGHPG RKGK\ RLGL\ RHJIMJMJLHJ ROIMM ROIPJMM RFNQNPMON
 RKOISGV RKQGV RMQNROTPTPSORMQ RSFSSRXQZ RSFTGTSSWQZO\ RTG[G R[G[O RZG[F
\G\O RTN[N RWNXSYVZX\[]Z RWNXRYU[X]Z
 4811 86D_IHQGWFYG RIHYG RQGQS RRGRS RLIMLNLNKLI RWIUL RWIXJUL RGM]M[LZM
 RPMNOJRGT RQNNPISGT RSMTOWR[T]S RTOWQYR]S RQUQ[ RRUR[ RMUKTK\ RLUL\ RLU
WU RVUWTYUXW RWUW\ RXUX\ RLXWX RL[W[
 4813 49D_LGJFJR RKGKR RKGXG RWGXFZGYI RXGXR RYGYR RQGQ[ RRGR[ RKLXL RKQ
XQ RIV[VYTWV RWVZU RG[][[YY[ RY[\Z
 4815 70D_SFQFPHNKKNHP RRFPI RSFPJMMJOHP RSGTIVLXN[P]O RYN[O RTIWLZN]O R
NOVOUNTO RQOQ[ RROR[ RISZSYRXS RKULWMZNZNYMWKU RXUUZ RXUYVUZ RG[][[YY[ R
Y[\Z
 4843100D_KEIJGN RKELFKHGN RMGNHOJPJPIOHMG RIMOMNLMM RKMKZ RLMLZ RGQPQOP
NQ RGSHWIWIVGS ROSMX ROSPTMX RGZPY RGZH[PY RWGXFVFVL RWGWL RRKRTQXPZ RRK
SLSTRWPZO[ RSL]L[KZL RXNUY RXNYOUY RSZ[X RSZT[[X RZV[X\[][]Z\XZV
 4844 97D_KEIJGN RKELFKHGN RMGNHOJPJPIOHMG RIMOMNLMM RKMKZ RLMLZ RGQPQOP
NQ RGSHWIWIVGS ROSMX ROSPTMX RGZPY RGZH[PY RWGXFVFVRUVSYQ[ RWGWRVVTYQ[N\
 RSHRLQN RSHTISKQN RSK\K[JZK RPQ]Q[PZQ RWRXVZZ\\][ RXVZY][
 4853101D_KEIJGN RKELFKHGN RMGNHOJPJPIOHMG RIMOMNLMM RKMKZ RLMLZ RGQPQOP
NQ RGSHWIWIVGS ROSMX ROSPTMX RGZPY RGZH[PY RRFR\ RRFSGS\ RSG[G R[G[ZZ[ R
ZG[F\G\Z[\Z[XZ RUKYKXJWK RUNUX RUNVOVX RVOXO RXOXW RWOXNYOYW RVVXV
 4855103D_KEIJGN RKELFKHGN RMGNHOJPJPIOHMG RIMOMNLMM RKMKZ RLMLZ RGQPQOP
NQ RGSHWIWIVGS ROSMX ROSPTMX RGZPY RGZH[PY RRFR[ RRFSGSZ RSGZG RZGZO RYG
ZF[G[O RSKZK RSO[O RWPWRXVZY\[]Z RWRXUZX]Z R\QYU R\Q]RYU RP[XX RP[Q\XX
 4883115D_IEFK RIEJFFK RJGLJMJMIJG RGMMMLLKM RIMIZ RJMJZ RFQNQMPLQ RFSGW
HWHVFS RMSKW RMSNTKW RGZMY RGZH[MY RQGOFO\ RPGP\ RPG[G RZG[F]G\I R[G[ZZ[
 R\G\Z[\Z[XZ RRHSLTLTKRH RXHWL RXHYIWL RQMZMYLXM RUMUW RVMVW RRPRX RRPSP
SX RSWXW RXPXX RXPYPYX
 4938 57D_MGKFKZ RLGLZ RLG[GYFXG RLJXJWIVJ RLMXMWLVM RGP]P[OZP RPQQTSWUY
X[[\][ RPQQSSVTWWYYZ][ RXRUV RXRYSUV RG[SX RG[H\SX
 4940 58D_HFH\ RHFIGI\ RIGOG ROGOP RNGOFPGPP RIKOK RIOOO RTFTP RTFUGUP R
UG[G R[G[XZZY[ R[Y[ZZ[ RZG[F\G\Z[\Z\Y[WZ RUK[K RUO[O
 4944 73D_HFH\ RHFIGI\ RIGOG ROGOP RNGOFPGPP RIKOK RIOOO RTFTP RTFUGUP R
UG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUK[K RUO[O RNRNZ RNROSOZ ROSUS RUSUZ RTSUR
VSVZ ROYUY
 4945 76D_HFH\ RHFIGI\ RIGOG ROGOM RNGOFPGPM RIJOJ RIMPM RTFTM RTFUGUM R
UG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUJ[J RTM[M RRORZQ[ RROSOSZR\Q[OZ RKRXRWQVR
 RQRMWKY RRSPUKY
 4949 76D_HFH\ RHFIGI\ RIGOG ROGOM RNGOFPGPM RIJOJ RIMPM RTFTM RTFUGUM R
UG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUJ[J RTM[M RNPNZ RNPOQOZ ROQUQ RUQUZ RTQUP
VQVZ ROUUU ROYUY
 4950 79D_HFH\ RHFIGI\ RIGOG ROGOM RNGOFPGPM RIJOJ RIMPM RTFTM RTFUGUM R
UG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUJ[J RTM[M RMPXPWOVP ROPOUNXMZ RPPPUOXMZK[
 RTPT[ RUPU[ RLTXTWSVT
 4958 98D_HFH\ RHFIGI\ RIGOG ROGOM RNGOFPGPM RIJOJ RIMPM RTFTM RTFUGUM R
UG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUJ[J RTM[M RMONPORPRPQOPMO RUOSS RUOVPSS R
LSXSWRVS RQSQUPXOZ RRSRUQXOZM[ RRTSWTYV[WZ RSWUYWZ RKVYVXUWV
 4959 82D_HFH\ RHFIGI\ RIGOG ROGOM RNGOFPGPM RIJOJ RIMPM RTFTM RTFUGUM R
UG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUJ[J RTM[M RLPXPWOVP RNPNZ ROPOZ RUPU[ RVP
V[ ROSUS ROVUV RLZXX RLZM[XX
 4987 82D_HFH[ RHFIGI[ RIGNG RMFKM RLGMFNGKM RKMLQLTKUJU RKMMQMTLVKVJUHT
 RQFQY RQFRGRX RRGYG RYGYO RXGYFZGZO RRKYK RROZO RUOVRWTYW\Z]Y RVRXUZW]Y
 RNYXW RNYOZXW R[QXT R[Q\RXT
 4993 89D_HFH[ RHFIGI[ RIGNG RMFKM RLGMFNGKM RKMLQLTKUJU RKMMQMTLVKVJUHT
 RUFSIPL RUFVGSJPLNM RUFWIXJZL\M]L RXJZK]L RRNYNXMWN RUNUYTZ RVNVYU[TZRY
 ROR\R[QZR RQUPWNZ RQURVNZ RYUZW[Z\Z\Y[WYU
 4994 92D_HFH[ RHFIGI[ RIGNG RMFKM RLGMFNGKM RKMLQLTKUJU RKMMQMTLVKVJUHT
 RUFSFRIPL RUFQKOM RRI[I RZHXKUNRP RYIZH[IXLTOPQ RTIUKWNZP\Q]P RUKWMZO]P
 RVQV\ RVQWQW\ RRRRW RRRSSSW RSS[SZRYS RNW]W[VZW
 5005 92D_HFH\ RHFIGI\ RIGNG RMFKM RLGMFNGKM RKMLQLTKUJU RKMMQMTLVKVJUHT
 RVGWFUFUM RVGVM RQI[IZHYI ROM]M\L[M RSMSORQQR RTMTOSQQRPR RWMWQXR\R]Q\P
 RXMXPYQ[Q\P\O RUSU[ RUSVSV[ RQV[VZUYV RO[][\Z[[
 5006 99D_HFH\ RHFIGI\ RIGNG RMFKM RLGMFNGKM RKMLQLTKUJU RKMMQMTLVKVJUHT
 RUFSIPL RUFVGSJPLNM RVGWIZL\M]L RXJZK]L RSLWLVKUL RPOXO RXOXR RWOXNYOYR
 RPR\R[QZR ROU]U[TZU RTURZ RVURZ ROZZY ROZP[ZY RYXZY[[\[\Z[YYX
 5012109D_HFH\ RHFIGI\ RIGNG RMFKM RLGMFNGKM RKMLQLTKUJU RKMMQMTLVKVJUHT
 RQFQN RQFRGRN RRGYG RYGYN RXGYFZGZN RRJYJ RRMYM ROP]P\O[P RQPPTOV RQPRQ
QSOV RQS\S RTSSVQXOY RUSTVRXOY RXSWVVXTZR[O\ RYSXVWXUZS[O\ R\S[ZZ[ R[S\R
]S\Z[\Z[XZ
 5030 86D_LGMFKFKRJVIX RLGLRKUIXGZ RGKQKPJOK ROPMX ROPPQMX RKYPX RKYLZPX
 RPVQYRYRXPV RUFTIRN RUFVGRN RYFXK RYFZGXK RTJT\ RTJUKU\ RUK]K\J[K RXKXZ
 RYKYZ RUP]P\O[P RUU]U\T[U RUZ]Z\Y[Z
 5038119D_KGLFJFJK RKGKK ROGPFNFNK ROGOK RGIRIQHPI RHLHP RHLIMIP RIMPM R
PMPP ROMPLQMQP RHPQP RLMLUKYJ[ RMMMVLYJ[H\ RHSQSPROS RGVRVQUPV RNXOYP[Q[
QZPYNX RUFTIRN RUFVGRN RYFXK RYFZGXK RTJT\ RTJUKU\ RXKXZ RYKYZ RUK]K\J[K
 RUP]P\O[P RUU]U\T[U RUZ]Z\Y[Z
 5040134D_MHMGNFLFLH RGHRHQGPH RJJOONP RKKMNNP RJPOKNJ RKOMLNJ RHJHP RHJ
IJIP RHPQP RPJPP RPJQJQP RLPKW RLPMQKW RJWNV RJWKXNV RNUNXOXOWNU RGRG\ R
GRHSH\ RHSQS RQSQZP[ RPSQRRSRZQ\P[NZ RUFTIRN RUFVGRN RYFXK RYFZGXK RTJT\
 RTJUKU\ RUK]K\J[K RXKXZ RYKYZ RUP]P\O[P RUU]U\T[U RUZ]Z\Y[Z
 5042 71D_GG]G[EYG RYG\F RQGQ\ RRGR\ RJLHKH\ RILI\ RILZL RYLZK\L[N RZLZZ
Y[ R[L[ZZ\Y[WZ RKNLOMQNQNPMOKN RTNUOVQWQWPVOTN RKTLUMWNWNVMUKT RTTUUVWWW
WVVUTT
 5044 66D_KGYGWFVG RQGQQ RRGRQ RIIHKGLGMHMIKII RIJ[J RZJ[I]K[L R[I[L R\J
[LZM RKMNM RUMXM RKPNP RUPXP RISYS RXSYR[SZU RYSY\ RZSZ\ RIWYW RI[Y[
 5046 78D_KGYGWFVG RQGQQ RRGRQ RIIHKGLGMHMIKII RIJ[J RZJ[I]K[L R[I[L R\J
[LZM RKMNM RUMXM RKPNP RUPXP RISZSYRXS RGV]V[UZV ROVN[ ROVPWN[ RI[WZ RI[
K\WZ RVXXZY\Z\Z[YZVX
 5048 94D_KGYGWFVG RQGQP RRGRP RIIHKGLGMHMIKII RIJ[J RZJ[I]K[L R[J[L R\J
[LZM RKMNM RUMXM RKPNP RUPXP RQPORLTHV RQPRQOSKUHV RRQVTXU[V]U RRQVSYT]U
 ROUTUSTRU RKXWX RWXWZV[ RVXWWXXXZW\V[TZ ROXO\ RPXP\
 5049 79D_KGYGWFVG RQGQQ RRGRQ RIIHKGLGMHMIKII RIJ[J RZJ[I]K[L R[I[L R\J
[LZM RKMNM RUMXM RKPNP RUPXP RLSJRJ\ RKSK\ RKSXS RWSXRZSYU RXSX\ RYSY\ R
QSQ[ RRSR[ RKWXW RK[X[
 5050 91D_KFYFWEVF RQFQP RRFRP RIHHJGKGLHLIJIH RII[I RZI[H]J[K R[I[K R\I
[KZL RKLNL RULXL RKONO RUOXO RLRJQJX RKRKX RKRXR RWRXQZRYT RXRXX RYRYX R
KUXU RJXYX RQRQ[R\\\][\Y R[[\[\Z RRRRZS[Z[\Y]V
 5055104D_KFYFWEVF RQFQN RRFRN RIHHJGKGLHLIJIH RII[I RZI[H]J[K R[H[K R\I
[KZL RKKNK RUKXK RKMNM RUMXM RIOIWHZG\ RIOJPJWIZG\ RJP[PYOXP RLRXRWQVR R
JT\TZSYT RNTN[ ROTOZ RSUTWVYY[\\][ RTWWYYZ][ RK[UY RK[L\UY RYVVX RYVZWVX
 5056 88D_KFYFWEVF RQFQN RRFRN RIHHJGKGLHLIJIH RII[I RZI[H]J[K R[I[K R\I
[KZL RKKNK RUKXK RKMNM RUMXM RJPXPWOVP RHS\SZRYS ROTO[ ROTPTP[ RSTS[ RST
TTT[ RIUKYLYLXIU RYUVZ RYUZVVZ RG[][[ZZ[
 5076 54D_RGSFQFQN RRGRN RIH[HYGXH RKKYKXJWK RGN]N[MZN RMQKPK\ RLQL\ RLQ
WQ RVQWPYQXS RWQWZV[ RXQXZW\V[TZ RLTWT RLWWW
 5077 97D_LGMFKFKN RLGLN RGHPHOGNH RIKOKNJMK RGNPNOMNN RHPH\ RHPIQI\ RIQ
NQ RNQNZM[ RMQNPOQOZN\LZ RITNT RIWNW RVFTFRK RVFRK RTHYH RXGUL RWHXGYHUL
 RUMUZT[ RVMVZU\T[RZ RQMYM RYMYV RXMYLZMZV RPQ]Q\P[Q RQUYU
 5080 59D_OGPFNFNRMVKYH\ ROGORNVLYH\ RUGVFTFT\ RUGU\ RGJNJ RUJ]J[HYJ RYJ
\I RHPNP RUP\PZNXP RXP[O RGVTS RGVHWTS RUV]V[TYV RYV\U
 5083106D_OFPENENLMO ROFOLNNLPJQ RUFVETETP RUFUP RGHNH RUH]H[GZH RGKNK R
UK]K[JZK RGNMN RGNHOMN RUN]N[MZN RGROR ROROZN[ RNROQPRPZO\N[LZ RKRGV RMR
GV RORJXG[ ROTMVG[ RSR[R R[R[ZZ[ RZR[Q\R\Z[\Z[XZ RWRSV RYRSV R[RVXS[ R[T
YVS[
 5087 56D_GG]G[EYG RYG\F RPGNL RRGNL RJLHKH\ RILI\ RILZL RYLZK\L[N RZLZ\
 R[L[\ RNLN[ ROLO[ RTLT[ RULU[ ROQTQ ROVTV RI[Z[
 5088 59D_NGOFMFML RNGNL RVGWFUFUL RVGVL RGI]I[HZI RMLVL RQLQ] RRLR] RLO
JNJU RKOKU RKOXO RWOXNZOYQ RXOXU RYOYU RKTXT RGX]X[WZX
 5110 58D_RHRGSFQFQH RHH[HYGXH RLHMJNMOMOLNJLH RVHTM RVHWITM RGM]M[LZM R
MQKPK\ RLQL\ RLQWQ RVQWPYQXS RWQW\ RXQX\ RLVWV RL[W[
 5138119D_MGNFLFLQ RMGMQ RHGJJKJKIHG RPGNJ RPGQHNJ RGKRKQJPK RKKJMHP RLL
HP RNMONPPQPQOPNNM RLRKWJY RLRMRLVKXIZG[ RGURUQTPU RNWOXPZQZQYPXNW RSG]G
\F[G RXGWK RXGYHWK RTJTW RTJUKUW RUK[K R[K[W RZK[J\K\W RUO[O RUS[S RTW\W
 RUYR\ RUYVZR\ RZY[Z\\]\][\ZZY
 5148 85D_KGIFIUHZG\ RJGJUIYG\ RJGYG RXGYF[GZI RYGYUZY[[\\]\]Z]X R[Z\[][
 RZGZU[Y\Z]Z RLKUIVJ RLKVJ RQKQZ RRJRY RMMMU RMMNNNU RNNUN RUNUU RTNUMVN
VU RNTUT RLZVY RLZM[VY RUWW[X[XZUW
 5152104D_GGTG RSGTFVGUI RTGTIULWOZQ\Q]P\O RUGUIVLXOZP[P\O]M RYGVK RYGZH
VK RWKYMZMZLWK RGMLKML RGMML RJLJTIYH[ RKLKTJXH[G\ RPJQIOIO\ RPJP\ RGRTR
 RSRTQVRUT RTRTTUWWZZ\\\][\Z RURUTVWXZZ[[[\Z]X RYRVV RYRZSVV RWVYXZXZWWV
 5154 82D_QFPHMLJNGO RQFRGPJNLKNGO RRGTJVLYN[O]N RRGUJXLZM]N RRORNSMQMQO
 RLNL\ RLNMOM[ RMOVO RVOVU RUOVNWOWU RMRVR RMUWU RQURWTZW\[]]\ RRWTYX[]\
 RI\SZ RI\J]SZ RXVUY RXVYWUY
 5186 60D_MFNGOIPIPHOGMF RUFTJ RUFVGTJ RGJ]J[HYJ RYJ\I RRJPN RRJSKPN RMN
KMK\ RLNL\ RLNXN RWNXMZNYP RXNX\ RYNY\ RLRXR RLVXV RLZXZ
 5188 71D_JHQGVFXG RJHXG RQGQS RRGRS RGK]K[IYK RYK\J RPKMNIQGR RQLMOJQGR
 RRKTMVOYQ[R]Q RTMWOYP]Q RNSLRL\ RMSM\ RMSVS RUSVRXSWU RVSV\ RWSW\ RMWVW
 RM[V[
 5191 74D_IFIT RIFJGJT RJG[GYFXG RQGQS RRGRS RJKZKYJXK RJOZOYNXO RJS[S R
ZS[R]S[U R[SZZY[ R\S[ZZ\Y[WZ RIWHYGZG[H[IYIW RLWM[N[NZLW RQVRZSZSYQV RUU
VVWXXXXWWVUU
 5220133D_HFHQ RHFIGIQ RIGQGPFOG RLGLP RMGMP RIJQJPIOJ RIMQMPLOM RIPPP R
PPPVOZN[ ROPPOQPQVPZO\N[LZ RHUGXHXHU RJUJXKWJU RLTMWNVLT RMROTOSMR RWFTJ
RL RWFXGVIRL RXGZJ\L]K RXGZI]K RUMZMYLXM RWMWTVXUZT[R\ RXMXTWXVZU[R\ RSO
SU RSOTPTU RTP[P R[P[U RZP[O\P\U RTT[T RXUYXZZ\\][ RYX[Z][
 5236 91D_NGLFLN RMGMN RMGWG RVGWFYGXI RWGWN RXGXN RQIQN RQIRJRN RRJWJ R
IMHOGPGQHQIOIM RIN\N RZN[M]O[P R[M[P R\N[PZQ RNQLPL\ RMQM\ RMQWQ RVQWPYQ
XS RWQWXVZU[ RWYWZV[ RXQXZW\V\U[SZ RMTWT RMWWW
 5248 75D_RHRFSEQEQH RGH]H[GZH RLJLN RLJMKMN RMKVK RVKVN RUKVJWKWN RLNWN
 RHPH\ RHPIQI\ RIQZQ RZQZZY[ RYQZP[Q[ZZ\Y[WZ RMSMX RMSNTNX RNTUT RUTUX R
TTUSVTVX RMXVX
 5276 89D_REPEOH RREOH RLHJGJQ RKHKQ RKHXH RWHXGZHYJ RXHXQ RYHYQ RQHQP R
RHRP RKLXL RKPXP RNQMVLXJZH[ RNQORNVMXKZH[G[ RRQRZS[\[]Z\Y RRQSQSYTZ[Z\Y
]W RXRWRVU RXRVU RUUYU RUUVVYU RYTZV[V[UYT
 5281 86D_PENELIJLGP RPELJGP RNHVH RTHUGWITJ RUGTJ RVHTJRL RMLKKKV RLLLV
 RLLYL RXLYK[LZN RYLYV RZLZV RRLRV RSLSV RLQYQ RKVZV RIXHZG[G\H\IZIX RMX
N\O\O[MX RSXT\U\U[SX RXXYY[\\\\[ZYXX
 5340 85D_SEQEPG RSEPG RMGKFKT RLGLT RLGWG RVGWFYGXI RWGWM RXGXM RLJWJ R
LMXM RLP[PYOXP RLS[S RZS[R]S[U R[SZZY[ R\S[ZZ\Y[WZ RIWHYGZG[H[IYIW RLWM[
N[NZLW RQVRZSZSYQV RUUVVWXXXXWWVUU
 5375 89D_SHSGTFRFRH RIGIUHZG\ RIGJHJUIYG\ RJH]H[GZH ROHOP RPHPP RUHUP R
VHVP RJL[L R[L[P RZL[K\L\P RJP\P ROQOZ ROQPQPZ RPUTUSTRU RK[UX RK[L\UX R
UQU[V\\\][\Z RUQVQVZW[[[\Z]X RVV[S\T RVV\T
 5385 64D_RGSFQFQO RRGRO RHI\IZHYI RILZLYKXL RGO]O[NZO RPPNRJUGW RPPQQNS
KUGW RNSXS RWRSVOYK[H\ RWRXSSWPYL[H\ RNSOUQXTZW[[\][ ROUQWTYWZ][
 5390 84D_SHSGTFRFRH RIGIVHZG\ RIGJHJVIYG\ RJH]H[GZH ROKPJNJN\ ROKO\ RJN
TNSMRN RNPMTLWKY RNTMVKY RPQQRRTSTSSRRPQ RXKYJWJW\ RXKX\ RTN]N[MZN RWPVT
UVSY RWTVVSY RXQYTZW\Z]Y RYT[W]Y
 5399 74D_OGPFNFNM ROGOM RUGVFTFTM RUGUM RHI\IZHYI RGM]M[LZM RQMQX RRMRX
 RLPJOJX RKPKX RKPXP RWPXOZPYR RXPXX RYPYX RKTXT RJXYX RNYG\ RNYOZG\ RUY
XZ\\]\][ZZUY
 5403 71D_QGQV RRGRV RLGJFJP RKGKP RKGXG RWGXFZGYI RXGXP RYGYP RKKXK RKO
XO RISZSYRXS RGV]V[UZV RIXHZG[G\H\IZIX RMXN\O\O[MX RSXT\U\U[SX RXXZZ[\\\
\[ZYXX
 5404 81D_QFQR RRFRR RJEJL RJEKFKL RKFXF RXFXL RWFXEYFYL RKIXI RJLYL RIO
ZOYNXO RGR]R[QZR RITGUGVHVIT RMTNVOVOUMT RTTUVVVVUTT RZT[V\V\UZT RQVQ[ R
QVRVR[ RJXZXYWXX RG[][[ZZ[
 5415102D_MGNFLFLM RMGMM RGISIQHPI RHMRMQLPM RIOIT RIOJPJT RJPOP ROPOT R
NPOOPPPT RITPT RIUJXKXKWIU ROUNX ROUPVNX RGZRX RGZH[RX RWGXFVFVQ RWGWQ R
RK]K[JZK RRQZQ RZQYTWWUYR[ RYQZP[QZTXWVYR[O\ RSRTUVXYZ\[]Z RTUVWYY]Z
 5421 83D_SEQEPG RSEPG RKFKM RKFLGLM RLGWG RWGWM RVGWFXGXM RLIWI RLKWK R
KMXM RQOQU RRORU RJOJU RKOKU RJOYO RXOXU RYOYU RKRXR RJUYU RNUNZM\L] ROU
OZN\L]J] RTUT] RUUU] RGX]X[WZX
 5428 87D_RFSEQEQK RRFRK RLHMGKGKK RLHLK RRHXHWGVH RGK]K[JZK RRNSMQMQY R
RNRY RLMMNNPOPOONNLM RVMTQ RVMWNTQ RJRYRXQWR RPRMVKX RQSOUKX RSTTUVXWXWW
VVST RHMH\ RHMIMI\ RI[Z[ RZMZ\ RZM[M[\
 5440 74D_RHRGSFQFQH RHH\HZGYH RLHNLOLOKLH RVHTL RVHWITL RGL]L[KZL RLOJN
JX RKOKX RKOXO RWOXNZOYQ RXOXX RYOYX RKSXS RKWXW RQOQ[R\\\][\Y R[[\[\Z R
RORZS[Z[\Y]V
 5445 85D_NELEJHGL RNEGL RMFSF RRFSEUGRH RSFRH RTFRHQI RJHJO RJHKIKO RKI
XI RXIXO RWIXHYIYO RKLXL RJOYO RQIQ[R\\\][\Z RRIRZS[[[\Z]X RIQIY RIQJRJY
 RJRYR RYRYY RXRYQZRZY RJUYU RJXYX
 6000 59D_OFQGQIPL RPGPRQV RKKMLRLUKXJ RUKVJXJ RSSTOUPSSPWNYLZJZIYIVJTLR
NQQPVPYQ[S\U\W[YY[V\T\ RKZJYJVKTMRQP RVPXQZS[U[WZYX[V\
 6001 34D_HHJIJKIMHP RIIIKHPHSIVJWLXMXMVNSOQ RJWLWMV RWLYM[P\S\UZTWU R[P
[SZT
 6002 39D_NEOFQGUG ROFTFUGQI RKMKNLOMOPMRL RKNLNOMRLTLWMXOXRWUUXRZN\ RTL
VMWOWRVUUWSYP[
 6003 45D_NEOFQGUG ROFTFUGQI RJMJNKOMORMULVM RJNMNRM RVMRPLVHZ RULRP RHZ
HYLVNURUSVTZU[\[ RW[ZZ[Z\[
 6004 62D_MFOGOINM RNGN[ RNTOZN[MYKXHW RHMJNNNQMSL RNNPMQLSL RHXLUQRTQVQ
YRZTZVYXWYUYSXRV RHXHWLU RVQXRYTYVXXWY RWKYK[L\MZMYN RYKZLZM
 6005 54D_NFPGPIOLMQH[ ROGOIMOKTH[ RHMHNIOJOMMOLRLTMUOURTVRZQ[P[PZOYMX R
HNJNMM RRLTNTRSVRXPZ RWMYN[P\R\T[SYT RZO[Q[S
 6006 46D_NFQGRKSNURXVWW RPGRK RURWW RLKNLQLTK RIOJPMQRQWPZO RWPYNZO RWW
UVRUNULVKWKYLZN[Q\W\ RN[V[W\
 6007 18D_TFVGVHNP RUGTINPNQSVUYV[ RNQVXWZV[
 6008 45D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQNOONQMZM\L RIUJWKX RVMZL[K\L RVF
XGXUWXUZR\ RWGXJ RXRWVUYR\
 6009 23D_MHOIRJTJWI ROITIVHWIQL RKSKULWNXRYYY RNXXXYY
 6010 49D_JKKLNMRMVLXKYJ RVLXJYJ RPFQIRKUOWRXT RPFQFQHRK RUOXRYTYU RYUXT
VSRRNRKSJUJWKYMZQ[U[ RJWKXMYQZVZU[
 6011 17D_LFNGMSMXNZ RMGLSLWMYNZP[S[VZYX[V
 6012 36D_RFTGTSSUQVOUNSNROPQOSPTRTVSZQ\ RSGTL RTVSYQ\ RHJJLMLVKZJ\K RIK
ML RVK\K
 6013 45D_LJNKNVOXPYRZZZ RMKNN RUZXYYYZZ RUGWHWTVVUURS RVHWK RWQVTUU RHN
JPLPPOUNYM[M\N RIOPO RUN\N
 6014 47D_NGPIVG ROHQHVGWH RWHTKNOJQ RVGUISKNO RIPKROP RJQOPUOZN[O RUO[O
 RUOSPQRPTPVQXRYUZYZ RQXTYXYYZ
 6015 48D_NFPGPINOMRKWI[ ROGOJNO RMRKVIYI[ RHMJNMNPMRLTK RRLSJTK RUNXN[O
YOWP RXNYO RRVSXTYVZ[Z RSXUY\Y[Z
 6016 44D_MFOGOIMNLRLTMU RNGNK RMNMU RHJKKOKSJUI RSJTHUI RMUOSRQUPXPZQ[S
[VZXWZS[O[ RXPYQZSZVYXWZ
 6017 26D_HLJNOLSKWKZL[M\O\R[TZUXVUWPX RIMOL RWKYLZM[O[RZTXV
 6018 35D_HIJKLKPJUIYH[H\I RIJPJ RUI\I RYIVJSLQOPRPUQXRYTZX[[[ RPUQWRXTY
XZZZ[[
 6019 29D_OFQGQQ RPGPMQQ RWNYPQQ RXOTPQQNRLSKUKWLYMZO[Z[ RLYNZYZZ[
 6020 63D_MFOGOIMOLRJWH[ RNGNJMO RLRJVHYH[ RHMJNLNOMQLSK RQLRJSK RVJXJZK
\MZLXM RXJZL RVOVQWTXVXXWZU[R[PZOXPVRUUUWV[Z RVQWVWYU[ RYXZZ[Z
 6021 42D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RSJVIYI[JYJWK RWIYJ RQS
QURWUX\X RQURVUWZW\X
 6022 69D_JILJLO RKJLOMRNTOVPW RNTPVPW RRGTHTJROOVMYKZIZHXHVISJQLOOMSLVL
YM[O\R\U[XZYXZVZTYSXSWTVVUXUZV\Y RSHSJRO RJZIXIUJRLO RVLXMZO[R[VZY RZV\X
\Y
 6023 60D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMNLMP ROMMPKSHWHVKSOOSL
VKXKZL[N[UZXYYWZUZSYRXRWSVUUWUYVZW\Z RXKYLZNZVYY RZW\Y\Z
 6024 42D_QHRJRMQPPRNULWJWIVHTHQINKKNIQHTHWIYJ[L\O\R[UYWWXTYQY RNULVJVIT
IQJMKK RWIZL[O[RZUWX
 6025 51D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTT
VU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L
 6026 52D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLY
OYRXTVUTVQ RVIXLYN[Q\SZSYT RUIXL RYNZQZS
 6027 53D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSY
RZ RIYLVOTRS RVSYT[V\XYX RIYIXLV RVSXTZV[X
 6028 17D_HPJRMM RIQNLPLUQYT[U\VZVXW RUQZV
 6029 61D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPO
SPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y
 6030 45D_RFTGTXSZQ[O[MZLXMVOUQUTVWXZ[ RSGTK RWXZZZ[ RHIJKSKZJ RIJNK RSK
WJYIZJ RMPOQSQWPYO RWPXNYO
 6031 44D_JGKIMIPHSFTG RKHPH RTGPMMSKVJWIWHVHTIRKQPQTRWS\U RSFPM RTR\T\U
 RVMXNXTWWUYSZP[ RWNWUVX
 6032 57D_MFOGOINMMQLTKVJWIWHVHTIRJQKQLRLWMZO[U[XZYYXXWVVRVNWMYM[N\P\Q[Q
YR RNGNM RLWMYOZUZWYXX RYM[O[Q RHKKLNLQKSJ RQKRISJ
 6033 61D_JILJLO RKJLOMRNTOVPW RNTPVPW RSGUHUJTMRRQTOWMYKZIZHYHWITJRLPON
RMVMYN[P\S\V[XZYXZU[R[ RTHTJRR RJZIYIVJSLP RVMXNZP[S[VZXXZ
 6034 42D_OFQGQIPM RPGPTQXRZT[X[ZZ[X[VZTXRUP RW[YZZXZUYS RLJMKPLSL RMKRK
SL RSLPMNNLPKRLTNUSU
 6035 48D_PFRGSHTJSKPJMJLKLMOTQ[ RRGSISK ROTRZQ[ RHNIPKPNNRLVKYK[L\N\P[R
ZSWTTTQS RIOKONN RYKZL[N[PZRYSWT
 6036 34D_HHJIJKIMHP RIIIKHPHSIVJWLXMXMVNSOQ RJWLWMV RWLYM[P\S\UZTWU R[P
[SZT
 6037 52D_HJJKJMIP RIKITJWKXKVLSMQONRKUJXJZK[L\N\Q[SYUWVTVRUPSOPOMPIQGSF
UFVHVSUWTYQ[ RITJVKV RZK[N[QZT RVSUVTXQ[
 6038 45D_NEOFQGUG ROFTFUGQI RJMJNKOMORMULVM RJNMNRM RVMRPLVHZ RULRP RHZ
HYLVNURUSVTZU[\[ RW[ZZ[Z\[
 6039 34D_PFSGSIRN RRGRXQZO[L[JZIYIWJVLUOURVVX[[ RRVWX[Z[[ RRNUNYM RUNWM
XLYM
 6040 42D_OFQFSGTHRHPI RQFRGRH RLLKNJRJTKUORQQTPWPYQZSZUYWWYUZQ[O[ RJRKT
LT RWPXQYSYUXWVYTZQ[
 6041 37D_LFNGNILM RMGMILMLPMSNTNROOQLSJUIWIXJYMYRXVVYS[O\ RLPMRNR RVIWJ
XMXRWVUYS[
 6042 50D_MGNIPIUG RNHPHUGVH RVHRKNPKU RUGRK RNPKSKU RKUMSPQSPVPXQYRZTZW
YYXZV[S[QZPYPXQWSWUXWZ RVPXRYTYWXYV[
 6043 49D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMOLMP ROMMPKSHWHVKSOOSL
VKWKYLZNYXYZZ[ RWKXLYNXXXZY[Z[[Z\X
 6044 42D_MGNIPIUG RNHPHUGVH RVHRKNPKU RUGRK RNPKSKU RKUMSPQSPVPXQYRZTZW
YYW[T\R\ RVPXRYTYWXZ
 6045 49D_MFOGOIM[ RNGN[M[LXKWIV RHLINKNOLOM RIMLMOLMP ROMMPKSHWHVKSNPQN
TMWMYNZO[Q[TZWXYVZS[ RWMYOZQZTYWVZ
 6046 52D_MGNIPITG RNHPHTGUH RUHQNMVLXKYIYHWHUISKQNORNVNYO[Q\S\V[XYZW[T[
RZQYQXRWTWVXXZ RTGQN RJYIWIUJR RZP[S[VZY
 6047 39D_NEOFQGUG ROFTFUGQI RKMKNLOMOPMRL RKNLNOMRLTLWMXOXRWUUXRZN\ RTL
VMWOWRVUUWSYP[
 6048 69D_LGMIOIQHTF RMHOHRGTFUG RUGQJMNJR RTFQJ RJRJPMNOMRLULWMXOXQWSUT
PTOSOQPPRPSQSSRTNUKWHZH[I[KW RJYLXNXPZQZSXVWYW[X\Y\[[ZYZ RNXPYQYSX RYW[Y
[Z
 6049 57D_PFRGRHPLNOKRHU RQGQHPL RKRHTHU RMPOOQOSPTRTV RQORPSRSWTV RIJLK
OKSJWI RSJVHWI R[O\QTRQSOTNVNXOZQ[Y[ R[PTR RT[XZY[
 6050 30D_QFSHPMLTH[ RRGPM RH[HYLTNRPQRQTRTWUYVZ RRQSRSWTYVZXZZY[W\T
 6055 60D_NFPGPIOLMQH[ ROGOIMOKTH[ RHMHNIOJOMMOLRLTMUOURTVRZQ[P[PZOYMX R
HNJNMM RRLTNTRSVRXPZ RWMYN[P\R\T[SYT RZO[Q[S RWHYJ RYF[H
 6056 52D_NFQGRKSNURXVWW RPGRK RURWW RLKNLQLTK RIOJPMQRQWPZO RWPYNZO RWW
UVRUNULVKWKYLZN[Q\W\ RN[V[W\ RWHYJ RYF[H
 6057 24D_TFVGVHNP RUGTINPNQSVUYV[ RNQVXWZV[ RYH[J R[F]H
 6058 51D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQNOONQMZM\L RIUJWKX RVMZL[K\L RVF
XGXUWXUZR\ RWGXJ RXRWVUYR\ R[G]I R]E_G
 6059 29D_MHOIRJTJWI ROITIVHWIQL RKSKULWNXRYYY RNXXXYY RYG[I R[E]G
 6060 55D_JKKLNMRMVLXKYJ RVLXJYJ RPFQIRKUOWRXT RPFQFQHRK RUOXRYTYU RYUXT
VSRRNRKSJUJWKYMZQ[U[ RJWKXMYQZVZU[ RZG\I R\E^G
 6061 23D_LFNGMSMXNZ RMGLSLWMYNZP[S[VZYX[V RSHUJ RUFWH
 6062 42D_RFTGTSSUQVOUNSNROPQOSPTRTVSZQ\ RSGTL RTVSYQ\ RHJJLMLVKZJ\K RIK
ML RVK\K RXFZH R[E]G
 6063 51D_LJNKNVOXPYRZZZ RMKNN RUZXYYYZZ RUGWHWTVVUURS RVHWK RWQVTUU RHN
JPLPPOUNYM[M\N RIOPO RUN\N RZH\J R\F^H
 6064 53D_NGPIVG ROHQHVGWH RWHTKNOJQ RVGUISKNO RIPKROP RJQOPUOZN[O RUO[O
 RUOSPQRPTPVQXRYUZYZ RQXTYXYYZ RZH\J R\F^H
 6065 54D_NFPGPINOMRKWI[ ROGOJNO RMRKVIYI[ RHMJNMNPMRLTK RRLSJTK RUNXN[O
YOWP RXNYO RRVSXTYVZ[Z RSXUY\Y[Z RXHZJ RZF\H
 6066 50D_MFOGOIMNLRLTMU RNGNK RMNMU RHJKKOKSJUI RSJTHUI RMUOSRQUPXPZQ[S
[VZXWZS[O[ RXPYQZSZVYXWZ RXIZK RZG\I
 6067 32D_HLJNOLSKWKZL[M\O\R[TZUXVUWPX RIMOL RWKYLZM[O[RZTXV RZH\J R\F^H

 6068 41D_HIJKLKPJUIYH[H\I RIJPJ RUI\I RYIVJSLQOPRPUQXRYTZX[[[ RPUQWRXTY
XZZZ[[ RZM\O R\K^M
 6069 35D_OFQGQQ RPGPMQQ RWNYPQQ RXOTPQQNRLSKUKWLYMZO[Z[ RLYNZYZZ[ RXIZK
 RZG\I
 6070 57D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTT
VU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L RZG\I R\E^G
 6071 58D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLY
OYRXTVUTVQ RVIXLYN[Q\SZSYT RUIXL RYNZQZS RYH[J R[F]H
 6072 59D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSY
RZ RIYLVOTRS RVSYT[V\XYX RIYIXLV RVSXTZV[X RWIYK RYG[I
 6073 23D_HPJRMM RIQNLPLUQYT[U\VZVXW RUQZV RUJWL RWHYJ
 6074 67D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPO
SPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y R[I]K R]G_I
 6075 61D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RUGWHWWVYTZRZPYOWPURTTT
VU[Y RVHWL RVU[X[Y RPMRNUNYM[L RYMZK[L R[EZFZH[I]I^H^F]E[E
 6076 62D_IGJHLIPI RJHOHPI RPIMKKMIPHSHVIXJYLZOZRYTWUUVQVMUIVI RHUIWJXLY
OYRXTVUTVQ RVIXLYN[Q\SZSYT RUIXL RYNZQZS RZFYGYIZJ\J]I]G\FZF
 6077 63D_PFQISJ RQHSITITJ RTJQKOLNMNOOPQQSRTSUUUWTYRZPZMYKW RQQSSTUTWSY
RZ RIYLVOTRS RVSYT[V\XYX RIYIXLV RVSXTZV[X RXGWHWJXKZK[J[HZGXG
 6078 27D_HPJRMM RIQNLPLUQYT[U\VZVXW RUQZV RVHUIUKVLXLYKYIXHVH
 6079 71D_IGKHKJJMIQ RJHJKIQIUJYKZKXLTMQ RIUJWKX RQGSHUHYG RUHWGXFYG RPO
SPVPYO[N RYOZM[N RUHWIWWVYTZRZPYOWPURTTTVU[Y RVIWM RVU[X[Y R\G[H[J\K^K_J
_H^G\G
 6100 36D_HGJIOHUGZF\H RIHOH RUG[G R\HZJVMTN R[GYJWLTN RRMTNTQSUQXN[ RRM
SNSQRUPY
 6101 22D_VFXHULRONRKT RWGVISMOQKT RSNUOU\ RSNTOT[U\
 6102 42D_PFSGSIRK RPFRGRK RJIKKKPLQ RLKLQ RLKYK RJIKJOK RUKXJZL RZLWRUU
RXOZM[ RYKXNVRSVPYM[
 6103 23D_QKSLSW RRLRW RJJLLXJZK RKKZK RHVJXZV\W RIW\W
 6104 35D_RFUGUYT[SYPW RTGTXSY RHLJNOMULZK\L RIMOM RUL\L RSMPQLUHX RTMRP
OSKVHX
 6105 41D_QFSHRKPPNTLWI[ RRGQJOPMUI[ RILKNOMTLXKZM RJMOM RTLYL RZMYSXWWY
U[TZRY RYLXSWWVYTZ
 6106 34D_OFRGT[ RQGS\T[ RJLLNPMTLXKZL RKMPM RTLZL RHRJTOSURZQ\R RISOS R
UR\R
 6107 34D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\ RXKWNURRV
OYK\
 6108 32D_NFPHNLLOJQHS ROGNJLNJQ RLOTNYM\N RTN\N RROTQRUPXNZL\ RSPRSPWNZ

 6109 24D_JJLLXJZL RKKYK RZLYOXV RYKXPXV RJVLXXVYW RKWYW
 6110 36D_LINJNOMS RMJMS RTFWGWLVQUTTVRYP[ RVGVLUQTURY RHMJOONUMZL\M RIN
ON RUM\M
 6111 28D_MGOHPIPJOJNHMG RHNJOKPKQJQIOHN RIXKZOXSUWQ[L RJYOWST[L
 6112 30D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RUSXUZWZXYXXVUS
 6113 35D_OGRHRJQS RQHQVRXTY[Y RVYZX[Y RHNJPOOUNZM\O RIOOO RUN[N R\OYQVT
 R[NVT
 6114 23D_IIKJLKLLKLJJII RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ
 6115 44D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\ RXKWNURRV
OYK\ RNPQQSRVTWUWVVVUTSR
 6116 36D_LJOJTIXG ROJRITHWFXG RPJSKSQRUPXM[ RRKRQQUOY RHNJPOOUNZM\N RIO
OO RUN\N
 6117 31D_IIKJLKLLKLJJII ROHQIRJRKQKPIOH RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ
 6118 32D_LFNHWFXG RMGXG RHNJPOOUNZM\N RIOOO RUN\N RSOSQRUPXM[ RRORQQUOY

 6119 17D_MFPGP\ ROGO[P\ RPOROUPVQVRURTPRO
 6120 28D_QFTGTLSQRTQVOYM[ RSGSLRQQUOY RHNJPOOUNZM\N RIOOO RUN\N
 6121 16D_LJNLWJXK RMKXK RHVJXZV\W RIW\W
 6122 32D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RMOPPTRWTYVYWXWVTTR

 6123 44D_PFRGSHSIRIQGPF RJLLNVLXN RKMWM RXNTRQTOUJW RWMUPSRPTJW RRSSTS\
 RRSR[S\ RXUZV[W[XZXYVXU
 6124 15D_WHYJVPSTPWMYKZ RXIWLTQQUNXKZ
 6125 20D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\U\V[VZRXN
 6126 25D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN
 6127 25D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY
 6128 15D_GQISPLQL[V RHRJQNN RUPZT\U[V
 6129 40D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\L RIMOM RUL\L RLSJVIWHWHVJULS
 RXS[U\V\W[WZUXS
 6130 31D_HLJNOMULZK\M RIMOM RUL[L R\MZOVRTS R[LYOWQTS RQRTTVVVWUWTUQR
 6131 28D_PFSGUHVIVJUJSHPF RMMPNROSPSQRQPOMM RNVSXUYVZV[U[SYPWNV
 6132 22D_RITKMW RSJMW RHWJYYV RIXYV RVSXUZX[X[WYUVS
 6133 25D_WHYJVPSTPWMYKZ RXIWLUPRTOWKZ RONSPVRXTXUWUVSTQQO
 6134 35D_LINKWIXJ RMJXJ RQKQVRXTY[Y RRKRMQS RVYZX[Y RHQJSORUQZP\Q RIROR
 RUQ\Q
 6135 31D_OFRGT[ RQGS\T[ RHLJNOMULZK\M RIMOM RUL[L R\MYPVRTS R[LZNWQTS
 6136 22D_VFXHULRONRKT RWGVISMOQKT RSNUOU\ RSNTOT[U\
 6137 24D_IJKLUJWL RJKVK RWLVOUV RVKUPUV RHVJXZV\W RIW\W
 6138 23D_QKSLSW RRLRW RJJLLXJZK RKKZK RHVJXZV\W RIW\W
 6139 30D_JJLLXJZL RKKYK RJPLRXP RKQXQ RJVLXXV RKWXW RZLYOYY RYKXPXY
 6140 30D_LFNHWFXG RMGXG RJMLOWMYO RKNXN RYOWRTUQWOXLY RXNWPUSSUPWLY
 6141 21D_LINJNOMS RMJMS RTFWGWQVUTXQ[ RVGVQUUTWQ[
 6142 31D_LJNKNNMRKUHX RMKMNLRKTHX RQISJSMRS RRJRVSXUXWWYU\Q RRVSWVWXV
 6143 21D_HIKJKMJS RJJJVKXNXQWTUXR[O RJVKWNWQVUTXR
 6144 30D_JJLLXJZL RKKYK RKKKZ RLLLXKZ RZLYOXV RYKXPXV RLXXVYW RLWYW
 6145 33D_JGKIKNLO RLILO RLIYI RJGKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPW
MY
 6146 31D_QFTGT[ RSGS\T[ RJJLLXJZK RKKZK RLLNMNR RMMMR RHQJSZQ\R RIR\R
 6147 42D_PFSGSIRK RPFRGRK RJIKKKPLQ RLKLQ RLKYK RJIKJOK RUKXJZL RZLWRUU
RXOZM[ RYKXNVRSVPYM[
 6148 30D_JJLLXJZL RKKYK RZLWNSQ RYKSQ RQPSQSW RRQRW RHVJXZV\W RIW\W
 6149 32D_JGLIYI RKHOI RUIXHZJ RLNNPVO RMOVO RZJWPUSRVOXMY RYIXLVPSTPWMY

 6150 20D_JHLIMJMKLKKIJH RIWKYOWSTWP[K RJXOVSS[K
 6155 47D_QFSHRKPPNTLWI[ RRGQJOPMUI[ RILKNOMTLXKZM RJMOM RTLYL RZMYSXWWY
U[TZRY RYLXSWWVYTZ RZH\J R\F^H
 6156 40D_OFRGT[ RQGS\T[ RJLLNPMTLXKZL RKMPM RTLZL RHRJTOSURZQ\R RISOS R
UR\R RZH\J R\F^H
 6157 40D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\ RXKWNURRV
OYK\ RYH[J R[F]H
 6158 38D_NFPHNLLOJQHS ROGNJLNJQ RLOTNYM\N RTN\N RROTQRUPXNZL\ RSPRSPWNZ
 RYH[J R[F]H
 6159 30D_JJLLXJZL RKKYK RZLYOXV RYKXPXV RJVLXXVYW RKWYW RZH\J R\F^H
 6160 42D_LINJNOMS RMJMS RTFWGWLVQUTTVRYP[ RVGVLUQTURY RHMJOONUMZL\M RIN
ON RUM\M RZH\J R\F^H
 6161 34D_MGOHPIPJOJNHMG RHNJOKPKQJQIOHN RIXKZOXSUWQ[L RJYOWST[L RVHXJ R
XFZH
 6162 36D_JILKWIYK RKJXJ RYKWNTQQSOTJV RXJWLUOSQPSJV RUSXUZWZXYXXVUS RZH
\J R\F^H
 6163 41D_OGRHRJQS RQHQVRXTY[Y RVYZX[Y RHNJPOOUNZM\O RIOOO RUN[N R\OYQVT
 R[NVT RYH[J R[F]H
 6164 29D_IIKJLKLLKLJJII RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ R[G]I R]E_G
 6165 50D_PFRHPLNOLQJS RQGPJNNLQ RQJSKXK RUKWJYL RYLVRSVPYM[K\ RXKWNURRV
OYK\ RNPQQSRVTWUWVVVUTSR RYH[J R[F]H
 6166 42D_LJOJTIXG ROJRITHWFXG RPJSKSQRUPXM[ RRKRQQUOY RHNJPOOUNZM\N RIO
OO RUN\N RZH\J R\F^H
 6167 37D_IIKJLKLLKLJJII ROHQIRJRKQKPIOH RXHZJWPTTQWNYLZ RYIXLVPSTPWLZ R
[G]I R]E_G
 6168 38D_LFNHWFXG RMGXG RHNJPOOUNZM\N RIOOO RUN\N RSOSQRUPXM[ RRORQQUOY
 RZH\J R\F^H
 6169 23D_MFPGP\ ROGO[P\ RPOROUPVQVRURTPRO RTHVJ RVFXH
 6170 26D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\U\V[VZRXN RYI[K R[G]I
 6171 31D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN RYI[K R[G]I
 6172 31D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY R[G]I R]E_G
 6173 21D_GQISPLQL[V RHRJQNN RUPZT\U[V RVJXL RXHZJ
 6174 46D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\L RIMOM RUL\L RLSJVIWHWHVJULS
 RXS[U\V\W[WZUXS RZG\I R\E^G
 6175 30D_LLNNMQLSJUHV RMMLQJU RVLXNZQ\U\V[VZRXN RZGYHYJZK\K]J]H\GZG
 6176 35D_IGLHLJKS RKHKVLXNYYY RQYUXWXYY RKROQRPXN RRPVNXN RZGYHYJZK\K]J
]H\GZG
 6177 35D_JGLIYI RKHOI RUIXHZJ RZJWPUSRVOXMY RYIXLVPSTPWMY R\E[F[H\I^I_H
_F^E\E
 6178 25D_GQISPLQL[V RHRJQNN RUPZT\U[V RWHVIVKWLYLZKZIYHWH
 6179 50D_PFSGSYR[QYOX RRGRXQY RHLJNOMULZK\L RIMOM RUL\L RLSJVIWHWHVJULS
 RXS[U\V\W[WZUXS R[EZFZH[I]I^H^F]E[E
 6200  6D_HYGZH[IZHY
 6201  8D_H[GZHYIZI\H^G_
 6202  8D_HOJQZP\Q RIP\Q

SHAR_EOF
if test 25031 -ne "`wc -c 'hersh.or4'`"
then
	echo shar: error transmitting "'hersh.or4'" '(should have been 25031 characters)'
fi
#	End of shell archive
exit 0

