#!/bin/sh
# This is a shell archive, meaning:
# 1. Remove everything above the #!/bin/sh line.
# 2. Save the resulting text in a file.
# 3. Execute the file with /bin/sh (not csh) to create the files:
#	hersh.or1
#	hersh.or2
# This archive created: Tue Mar 25 22:19:19 1986
export PATH; PATH=/bin:$PATH
echo shar: extracting "'hersh.or1'" '(26757 characters)'
if test -f 'hersh.or1'
then
	echo shar: over-writing existing file "'hersh.or1'"
fi
cat << \SHAR_EOF > 'hersh.or1'
    1  8D_GQ]QZOXQ RXQ[P
    7 51D_GG]G[EYG RYG\F RQGPNORNTLWJYG[ RRGQNPRNVLXIZG[ RQMYM RXMYL[MYP
 RYMXTWXVYTZQY RWYVZUZ RZMYTXXWZV[U[TZ
    8 24D_II[IYGWI RWIZH RKQYQWOUQ RUQXP RGZ]Z[XYZ RYZ\Y
    9 25D_GG]G[EYG RYG\F RQGQ[ RRGR[ RTMVNXQYSZSZRYPWNTMRM
   15 37D_IHZHXFVH RVHYG RQHNZ RRHOZ RIPVP RUPVOXPWR RVPUZ RWPWRVZ RGZ]Z
[XYZ RYZ\Y
   16 48D_GG]G[EYG RYG\F RQGQLPQNULXJZG\ RRGRMQROVLYI[G\ RSOTRVVXY[\][ R
YY[[ RSOUSXWZY][ RIN[NYLWN RWNZM
   17 38D_GG]G[EYG RYG\F RTJVITHRLOPKTGW RUITKQOMSIVGW RQOQ\ RRMR\ RWPYR
[U\U\TZRWPUO
   24 45D_GG]G[EYG RYG\F RYGYXXZW[ RYYYZX[ RZGZZY\X\W[UZ RKLKV RKLLMLV R
LMSM RSMSU RRMSLTMTU RLTST
   26 37D_IG[GYEWG RWGZF RQGQ] RRGR] RKKLMMPNPNOMMJJ RXJUP RXJYKUP RGR]R
[PYR RYR\Q
   27 38D_HG\GZEXG RXG[F RRGR[ RSGS[ RMPNOLNL[ RMOM[ RSP[PYNWP RWPZO RG[
][[YY[ RY[\Z
   33 42D_GG]G[EYG RYG\F RRGOM RRGSHOM RLMJLJ[ RKMK[ RKMXM RWMXLZMYO RXM
X[ RYMY[ RKSXS RKYXY
   34 62D_GG]G[EYG RYG\F RQGQV RRGRV RKLIKI\ RJLJ\ RJLYL RXLYK[LZN RYLYX
XZW[ RYYYZX[ RZLZZY\X\W[UZ RMOMW RMONONW RNVUV RUOUW RUOVOVW
   35 53D_GG]G[EYG RYG\F RQGQU RRGRU RLKJJJ\ RKKK\ RKKXK RWKXJZKYM RXKXX
WZV[ RXYXZW[ RYKYZX\W\V[TZ RKPXP RGU]U[TZU
   43 48D_NGN[ ROGO[ RTGT[ RUGU[ RGG]G[EYG\F RKMILIU RJMJU RJMYM RXMYL[M
ZO RYMYU RZMZU RJTYT RG[][[YY[\Z
   49 76D_GG]G[EYG RYG\F ROGMM RPGNM RMMRM RRMRWQX RQMRLSMSWRYQXOW RLOMP
NROROQNPLO RWNSR RWNXOSR RKURS RKULVRS RTSUTWWXWXVWUTS RHMH\ RHMIMI\ RI[
Z[ RZMZ\ RZM[M[\
   50 55D_GG]G[EYG RYG\F RQGQV RRGRV RLKLW RLKMLMW RMLVL RVLVW RULVKWLWW
 RMQVQ RMVVV RHKH\ RHKIKI\ RI[Z[ RZKZ\ RZK[K[\
   53 69D_LGJFJOITHV RKGKOJSIUGW RKGXG RWGXFZGYI RXGXM RYGYM RKLXL RULVN
XQ[S]R RVNXPZQ]R RMPMX RMPNQNX RNQUQ RUQUX RTQUPVQVX RNTUT RNWUW RH[\[ZZ
Y[
   54 67D_GG]G[EYG RYG\F RTGPJKMGO RVGPKLMGO RQJQP RRIRP RVKXLZN[N[MYLVK
 RGR]R[PYR RYR\Q RQRQ[ RRRR[ RMVNULUL[ RMVM[ RRVZVXUWV RG[][[YY[ RY[\Z
   58 86D_GG]G[EYG RYG\F RQGPJ RRGQI RSGQJ RMJKIKS RLJLS RLJWJ RVJWIYJXL
 RWJWS RXJXS RLMWM RLPWP RKSXS RNTKWGZ RNTOUKXGZ RNVXV RWUUWQZO[L\H] RWU
XVTYP[M\H] RNVQYT[W\[]]\ ROWRYTZW[]\
   62 86D_GG]G[EYG RYG\F ROGOS RPGPS RTGTS RUGUS RIJIO RIJJKJO RJKZK RZK
ZO RYKZJ[K[O RIO[O RGS]S[QYS RYS\R RMVM[N\V\W[VZ RMVNVNZO[U[VZVX RQURXSX
SWQU RJWIYHZH[I[JYJW RYW[Y\[][]Z\YYW
   81 32D_RHSGQFQ] RRGR] RJLHKHV RILIV RILZL RYLZK\L[N RZLZV R[L[V RIUZU

   82 55D_RHSGQFQLPPORMTJV RRGRMQPPRNTJV RRNSQTSVUWTUSSQ RJKHJH\ RIKI\ R
IKZK RYKZJ\K[M RZKZXYZX[ RZYZZY[ R[K[ZZ\Y\X[UZ
   92 33D_KGIFIV RJGJV RJGYG RXGYF[GZI RYGYV RZGZV RQGQ\ RRGR\ RJNYN RJU
YU
   96 48D_RHSGQFQ\ RRGR\ RGL]L[JYL RYL\K RPLMRJVGY RQMOQMTKVGY RSMTPURXV
[Y]X RYV[X RSMTOWSZV]X RMWVWUVTW
   97 41D_QFQ[ RQFRFR[ RJHJP RJHKHKP RKOXO RXHXP RXHYHYP RHSH\ RHSISI\ R
I[Z[ RZSZ\ RZS[S[\
  101 59D_SFQFPI RSFPI RJIHHH[ RIII[ RII[I RZI[H]I\K R[I[WZYYZ R[X[YZZ R
\I\Y[[Z[YZWY RNMNV RNMONOV RONUN RUNUV RTNUMVNVV ROUUU
  103 43D_OHPGNFN[ ROGO[ RUHVGTFT[ RUGU[ RJKHJH\ RIKI\ RIKZK RYKZJ\K[M R
ZKZ\ R[K[\ RISZS RI[Z[
  107 60D_QGQ\ RRGR\ RLGJFJP RKGKP RKGXG RWGXFZGYI RXGXP RYGYP RKKXK RKO
XO RGS]S[RZS RPSNVKYH[ RQTMXJZH[ RSSTVVYXZ[[]Z RTVVXXY]Z
  108 70D_RGSFQFQP RRGRP RIH[HYGXH RJLZLYKXL RHP\PZOYP RQPNSJVGX RQPRQNT
KVGX RRPSSTUVXXZ[\][ RYZ[[ RTUVWYY][ RMTMZ RNTNZ RI[UW RI[K\UW RXRUU RXR
YSUU
  130 74D_NFPGQHRHRGPFNF RKLQL RPLQKSLRN RQLQXPZO[ RQYQZP[ RRLRZQ\P\O[MZ
 RSLTOVSXV[Y]X RYV[X RSLUPXTZV]X RGPOP RLPMOOPMR RMOLRKTIWGY RNPMSKVGY R
ZLVP RZL[MVP
  131 70D_JHLJMLNLNKMJJH RHONO RLOMNOPMQ RMNLRJVGZ RNPLTJWGZ RRISGQFQXPZ
O[ RQYQZP[ RRGRZQ\P\O[MZ RSGSITNUQVSXV[Y]X RYV[X RSITMVQXTZV]X RZKVP RZK
[LVP
  132 39D_RHSGQFQ] RRGR] RJHKIMLNLNKMJJH RXHUM RXHYIUM RHO\OZMXO RXO[N R
GU]U[SYU RYU\T
  138 99D_IFJGKILILHKGIF RRFPFOIMNLPIUGX RQFOK RRFOLLQJTGX RGJUJ RTJUIWJ
VL RUJUN RVJVN RNNXN RWNXMZNYP RXNXS RYNYS RKS[S RZS[R]S[V R[SZZY[ R\S[Z
Z\Y[WZ RKVJXIYIZJZKXKV RNVOZPZPYNV RRVSYTYTXRV RUUVVWXXXXWWVUU
  139 61D_JFKGLJMJMILGJF ROFPGQJRJRIQGOF RWFUK RWFXGUK RLLJKJU RKLKU RKL
XL RWLXKZLYN RXLXU RYLYU RQLQ] RRLR] RKPXP RKTXT RGX]X[WZX
  146 40D_NIOHMGMRLVJYG\ RNHNRMVKYG\ RGNTM RSMTLVMUO RTMTZU[\[]Z\X R[Z\Z
\Y RUMUYVZZZ\X]U
  154 72D_OGOLNQMTLVJY RPGPLOQNTLWJYG[ RPLQPSTUWXZ[\][ RVWXY[[ RPLQORQTT
XX[Z][ RIGXG RUGVFXGWH RVGTN RWHUN RTN\N RYNZM\NZP RZMXRVUSXPZL\ R[NYRWU
TXQZO[L\
  156 26D_IJOITHXGZI RRIYH RIJZI RQIQ\ RRIR\ RGQ]Q[OYQ RYQ\P
  162 27D_QIQ] RRIR] RLEILHN RLEMFLHHN RKI[IYGWIZH RGQ]Q[OYQ\P
  166 50D_RHSGQFQPPROS RQQQRPS RRGRRQTPTOSMR RLIIPHR RLIMJLLHR RVIXKZN[N
[MYKVI RXPWRUURXOZM[ RXPYQVUSXPZM[I\
  173 65D_OFPENENRMVKYI[ ROFOSNVMXKZG\ RUFVETET\ RUFU\ RIHYH RXHYG[HZJ R
YHYN RZHZN RKMILHT RJMIT RJMYM RIR[R RZR[Q]R[U R[RZXYY R\R[XZZYYWX
  179 43D_RGSFQFQ\ RRGR\ RIJZJXHVJYI RGP]P[NYP\O RQPPSNVKYH[ RQSOVLYH[ R
RPTTVWXY[[]Z RTTWWZY]Z
  188 47D_LFJKGQ RLFMGLIINGQ RLI\IZGXI RXI[H RRIR\ RSIS\ RNOLNLU RMOMU R
MO[OYMWO RWOZN RGU]U[SYU RYU\T
  195 65D_JHWFYG RJHYG RPGML RRGML RKKMMNOOOONNMKK RVJQQ RVJWKQQ RHRYQ R
HRJSYQ RXOZQ[S\S\R[QXO RQRQ\ RRRR\ RLUKWIZ RLUMVIZ RVUXWYYZYZXYWVU
  196 61D_RGSFQFQ\ RRGR\ RGI]I[GYI RYI\H RLLJKJS RKLKS RKLXL RWLXKZLYN R
XLXS RYLYS RKRXR RPRNUJY RQSOUJYG[ RSRTTVWYY\Z]Y RTTVVYX]Y
  199 68D_HHHW RHHIIIV ROJOSNWLZJ\ ROJPJPSOWMZJ\ RIIPFQG RIIQG RKNLQMQMP
KN RGWLU RGWHXLU RTHT\ RTHUIU\ RUI[I R[I[XZY R[I[H\I\X[ZZYXX RWOXRYRYQWO
  202 63D_RHSGQFQ\ RRGR\ RIJ[JYHWJ RWJZI RKKLLMNNNNMMLKK RWKTP RWKXLTP R
GP]P[NYP RYP\O RQPPRNULWHZ RQROUMWJYHZ RSPTSVVXX[Z]Y RTSWVZX]Y
  211 52D_IHQGXFZG RIHZG RQGQ[ RRGR[ RHL\LZKYL RLLLV RMLMV RVLVV RWLWV R
GQ]Q[OYQ RYQ\P RHV\VZUYV RG[][[YY[ RY[\Z
  213 61D_RGSFQFQ\ RRGR\ RGH]H[GZH RLLJKJU RKLKU RKLXL RWLXKZLYN RXLXU R
YLYU RKPXP RKTXT RQTNWKYG[ RQVNXLYG[ RRTUXXZ[[]Z RRTUWYY]Z
  223 63D_IHQGWFYG RIHYG RQGQ\ RRGR\ RHK\K[JZK RLKLS RMKMS RVKVS RWKWS R
GO]O[NZO RHS\S[RZS RPSMWJYHZ RQTNWKYHZ RSSTUVWYY\Z]Y RTUWWYX]Y
  224 53D_QGQ[ RRGR[ RIHQGXFZG RIHZG RHK\KZJYK RJMJT RJMKNKT RKNXN RXNXT
 RWNXMYNYT RKQXQ RJTYT RHW\WZVYW RG[][[ZZ[
  230 81D_SEQEPG RSEPG RMGKFKT RLGLT RLGWG RVGWFYGXI RWGWM RXGXM RLJWJ R
LMXM RLP[PYOXP RLS[S RZS[R]S[U R[SZZY[ R\S[ZZ\Y[WZ RNUNZ RNUOUOZ RHVH[ R
HVIVI[ RIZTZ RTVT[ RTVUVU[
  260 37D_IGUG RRGTFVH RTFSHJTIVIXJZL[[[\Z[X RUGSI RZZ[Z[Y RVHTISJKTJVJX
KYMZYZ[X\U
  261 30D_MINHLGLZM[Y[ZZYX RXZYZYY RMHMYNZWZYXZU RHQNPSO[MXLWN RWNYM
  272 63D_RFSEQEQXPZO[ RQYQZP[ RRFRZQ\P\O[MZ RGH]H[GZH RJJJN RJJKKKN RKK
XK RXKXN RWKXJYKYN RJNYN RHQXQ RXQXX RWQXPYQYX RGT]T[SZT RHWXW
  273 16D_JJZJXHVJ RVJYI RGX]X[VYX RYX\W
  275 49D_IH[HYFWH RWHZG RGN]N[LYN RYN\M RNNNRMVLXJZH[ RONORNVMXKZH[G[ R
TNTZU[\[]Z\X R[Z\Z\Y RUNUYVZZZ\X]U
  283 43D_RISHQGQM RRHRM RGM]M[KYM RYM\L RMQLTJXH[ RNRMT RMQORMUJYH[ RTQ
VSYWZY[Z\Y[WXTTQ RYV[Y
  284 44D_RIRGSFQFQI RGI]I[HZI RRLSKQKQ\ RRLR\ RLOJNJ[ RKOK[ RKOXO RWOXN
ZOYQ RXOXYWZ RYOYYX[WZUY
  285 32D_OEPFQIRIRHQFOE RHJ\JZHXJ[I RQJQ[ RRJR[ RIR[RYPWRZQ RG[][[YY[\Z

  290 66D_RHRFSEQEQH RGH]H[GZH RMJKLGO RMJNKKMGO RUJXL[O\O\NYLUJ RUPWOUN
TQRTOWLYJZG[ RVOUQSTPWMYKZG[ RNNKPKR RNNKR RNNOQQTTWWY[[]Z RQTUWYY]Z
  295 69D_RGRFSEQEQG RGG]G[EYG RYG\F RLKJJJR RKKKR RKKXK RWKXJZKYM RXKXR
 RYKYR RKQXQ RQQQXPZO[ RQYQZP[ RRQRZQ\P\O[MZ RLTGY RLTMUGY RVTXVZY[Y[XZW
VT
  298 81D_RHRFSEQEQH RGH]H[GZH RLIKLIQGT RLIMJKNJPGT RJPJ\ RKNK\ RSIRLPP
NS RSITJSLQONS RSL[L RZLYOWSUVRYO[ RYLZK[LZOXSVVTXQZO[L\ RRNSOURVRVQUPRN
 RPPQSSVUXXZ[[]Z RSVVXYY]Z
  306 87D_RHRFSEQEQH RGH]H[GZH ROHNKLNJP RPHOKMNJPHQ RSHSNRO RTHTNSPROPN
 RJJGN RJJKKGN RWJXKZN[N[MZLWJ ROPKUGY ROPPQMTGY RNSXS RWRUURXOZM[ RVSWR
XSTWPZM[I\ RNSOUQXTZW[[\][ ROUQWTYWZ][
  319 91D_RHRFSEQEQH RHH\HZGYH RQHOM RQHRIOM RMLNMOOPOPNOMML RUKQQ RUKVL
QQ RLRUQ RLRMSUQ RUPVQWSXSXRWQUP RHJIKJMKMKLJKHJ RZJXM RZJ[KXM RKOHRIS R
KOIS RXOYP[S\S\R[QXO RRUSTQSQ\ RRTR\ RGV]V[UZV
  321 96D_RGRFSEQEQG RGG]G[FZG RMHNIOKPKPJOIMH RUHTK RUHVITK RJLHKH[ RIL
I[ RILZL RYLZK\L[N RZLZYYZ R[L[YZ[YZWY ROLNOMQ ROLPMOOMQKR RSLSPTQWQXPWO
 RTLTOUPVPWOWN RNSNZ RNSOTOZ ROTTT RTTTZ RSTTSUTUZ ROYTY
  339 39D_QFQLPQNULXJZG\ RRGRK RQFSGRNQROVLYI[G\ RSGSKTQUTVVXY[\][ RYY[[
 RSKTPVTXWZY][
  350 44D_MFKKIOGS RMFNGMIIPGS RKLK[ RLKL[ RTHUGSFSZT[\[]Z\X R[Z\Z\Y RTG
TYUZZZ\X]U R[KTQ R[K\LTQ
  352 50D_SFQFPHNKKNHP RRFPI RSFPJMMJOHP RSGTIVLXN[P]O RYN[O RTIWLZN]O R
MOVOUNTO RLTVT RUTVSXTVW RVTU\ RWTV\
  361 63D_LFKIINGR RLFMGKKGR RJMJ\ RKKK\ RUHVGTFTW RUGUW RPLQKOJOZP[\[]Z
\X R[Z\Z\Y RPKPYQZZZ\X]U RLRXKYK RXKYJ[KZM RYKYRXS RZKZRYTXSVR
  362 36D_MFIOGS RMFNGLKIPGS RKMK\ RLKL\ RVHWGUFU[ RVGV[ RON]N[LYN\M RP[
\[ZYX[[Z
  364 59D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RSGTFRFRKSQTTUVWYY[[\\\][\Z R
XYYZ[[\[ RSGSKTQUTWWYY[Z\Z]W RVFWGXIYIYHXGVF RKL]K[JZK
  383 60D_SFQFPHNKKNHP RRFPI RSFPJMMJOHP RSGTIVLXN[P]O RYN[O RTIWLZN]O R
MPWPVOUP RNTLSL\ RMTM\ RMTWT RVTWSYTXV RWTW\ RXTX\ RM[W[
  384 55D_SFQFPHNKKNHP RRFPI RSFPJMMJOHP RSGTIVLXN[P]O RYN[O RTIWLZN]O R
LPXPVOUP RQPQ[ RRPR[ RKUYUWTVU RG[][[YY[ RY[\Z
  401 57D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RUHVGTFTM RUGUM RNM\MZKXM RXM
[L ROPPRQVQXRXRVQSOP RYPVZ RYPZQVZ RN[][[YY[ RY[\Z
  403 52D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RVHWGUFU\ RVGV\ RQKOJOV RPKPV
 RPK[K RZK[J]K\M R[K[V R\K\V RPP[P RPU[U
  405 59D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RUHVGTFT\ RUGU\ RNL]L[KZL RTL
SORQPTNV RTOSQQTNVLW RULVOWQYT\W]V RVOXRZT]V RQWXWWVVW
  406 73D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RQHRHPGPX RQHQW RNXWU RNXOYWU
 RRHWGZF\G RRH\G RVHVMWSXVYX[[\\]\][\Y R[Z\[ RWGWMXSYVZX[Y\Y]V RQO]O[NZO
 RQ[X[WZV[
  407 52D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RRFQJOONQ RRFSGRJPNNQ RUKU\ R
VKV\ RQK]K[IYK\J RVQ]Q[OYQ\P RVW]W[UYW\V
  408 68D_SFQFPHNKKNHP RRFPI RSFPJMMJOHP RSGTIVLXN[P]O RYN[O RTIWLZN]O R
MOVOUNTO RQOQZP[ RRORZQ\P[NZ RIS[SYRXS RMVKXHZ RMVNWHZ RTVWXYZZZZYYXWWTV
  409 60D_KFILGQ RKFLGJLGQ RIMI\ RJLJ\ RMH]H[FYH RYH\G RZHZXYZX[ RZYZZY[
 R[H[ZZ\Y\X[VZ RNLNV RNLOMOV ROMUM RUMUU RTMULVMVU ROTUT
  422 58D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ ROG]G[FZG RSGS[ RTGT[ RWGW[ R
XGX[ RQOONO\ RPOP\ RPO[O RZO[N]O\Q R[O[\ R\O\\ RP[[[
  428 76D_LFKJIOGS RLFMGLJJNGS RJNJ[ RKLK[ RMGVGUFTG RPGOLNPMR RQGPLOOMR
 RPLUL RTKSQRTQVOY RSLTKULTQSTQWOYL[ ROPPQQSRSRRQQOP RWIWU RWIXIXU R[F[Y
ZZ R[F\F\Y[[ZZXY
  431 61D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RSGTFRFRT RSGST RXGYFWFWT RXG
XT RNL]L[KZL RNT]T[SZT RRVOZM\ RRVSWQYM\ RWVYX[\\\\[[YYWWV
  449 84D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RPHVGZF\G RPH\G RUHSL RUHVISL
 RPKQLRNSNSMRLPK RYKUQ RYKZLUQ ROR[Q RORPS[Q RZO[P\R]R]Q\PZO RURU\ RVRV\
 RQUPWNZ RQURVNZ RYU[W\Y]Y]X\WYU
  488 72D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RXEVEVK RWEVK RXEVK ROG]G[FZG
 RRJRX RRJSKSX RSKZK RZKZX RYKZJ[K[X RSOZO RSSZS RSWZW ROMPLNLN\ ROMO\ R
O[][[ZZ[
  509 75D_LFKJIOGS RLFMGLJJNGS RJNJ[ RKLK[ ROFOV ROFPGPV RPGSG RSGSV RRG
SFTGTV RPLSL RPQSQ ROVTV ROWM[ ROWPXM[ RSWT[U[UZSW RWHWU RWHXHXU R[F[YZZ
 R[F\F\Y[[ZZXY
  511 85D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RMG]G[FZG ROIOSNXMZ ROIPJPSOW
MZL[ RPJZJ RZJZN RYJZI[J[N RPN[N RRPR\ RRPSQS\ RSQ[Q R[Q[ZZ[ RZQ[P\Q\Z[\
Z[YZ RUQU[ RVQV[ RXQX[ RYQY[ RSU[U
  534 93D_LFKIINGR RLFMGJMGR RJMJ\ RKKK\ ROKPJNJNUOVRVSURT ROKOTPUQURTRR
 RRLOO RRLSMOO RSG]G\F[G RXGWK RYGWK RUJUW RUJVKVW RVK[K R[K[W RZK[J\K\W
 RVO[O RVS[S RUW\W RWZVYS[Q\ RWZQ\ RZY[Z\\]\][\ZZY
  540121D_LFKJIOGS RLFMGLJJNGS RJNJ\ RKLK\ RTFRFPIMM RTFMM RRHYH RWHXGYH
WI RXGWIUK RPJPO RPJQKQO RQKZK RZKZO RYKZJ[K[O RUKUO RVKVO RPO[O RUOPRNS
 RVOUPSQNS RSQTTUXUZT[ RSQUUVXVZU\T[RZ RTSQUNV RTTRUNV RUVQXNY RUWRXNY R
VPWTXVZY\[]Z RXVZX]Z R[RXU R[R\SXU
  551102D_LFKJIOGS RLFMGLJJNGS RJNJ[ RKLK[ RUHUGVFTFTH ROH[HZGYH RQHRKSK
SJQH RWHVK RXHVK RMK]K\J[K ROMOU ROMPNPU RPNYN RYNYU RXNYMZNZU RPQYQ RPT
YT RQVQZR[Y[ZZYY RQVRVRYSZXZYYYW ROWMYMZNZOW RTVUXVXVWTV R[W\Y]Y]X[W
  571 67D_SGTFRFRP RSGSP RMGLJKLIO RMGNHMJKMIO RLK[KYIWK RWKZJ RGP]P[NYP
 RYP\O RPPNVLYJ[H\ RPPQQPTOVMYK[H\ RTPT[U\\\][\Y R[[\[\Z RUPUZV[Z[\Y]V
  574 43D_RLQOOTMWJZG\ RRLSMRPPTNWLYI[G\ RLGUG RRGSFUGSI RSGSLTQUTVVXY[\
][ RYY[[ RSLTPVTXWZY][
  577 34D_MKMNLRJVGY RNLNNMQ RMKOLNPMSKVGY RUKVPWSYW[Y]X RYV[X RUKVOWRYU
[W]X
  578 58D_MGLIJLGO RMGNHLKJMGO RUFVHYL\O]N RVHYK]N RJOWO RVOWOYOXQ RWOVW
UYTZ RVXVYUZ RXOWYV[U[TZRY ROONTLXJZH[ ROOPPOTMXKZH[
  579 45D_MHLKJOHR RMHNILMIQGS RUHVKWMYP[R\Q RVKXNZP\Q RQONY RQORPNY RIZ
WY RIZK[WY RUVWXY[Z[ZZXXUV
  581 49D_NGOFMFMT RNGNT RVGWFUFUT RVGVT RHL\LZJXL RXL[K RGT]T[RYT RYT\S
 RNVLXG\ RNVOWLYG\ RTVWXZ[[[[ZZYTV
  588 64D_PGQFOFOV RPGPV RUGVFTFTV RUGUV RLJJIJV RKJKV RKJYJ RXJYI[JZL R
YJYV RZJZV RKPYP RGV]V\U[V ROYMXI[G\ ROYMZG\ RUXWYZ[[\\\\[[ZYYUX
  589 58D_MFNGOJPJPIOGMF RVFTK RVFWGTK RHK\KZIXK RXK[J ROKO[ RPKP[ RTKT[
 RUKU[ RJOKRLWMWMULRJO RZOWX RZO[PWX RG[][[YY[ RY[\Z
  590 50D_NGOFMFMV RNGNV RVGWFUFUV RVGVV RHJ\JZIYJ RNNUN RNRUR RGV]V[UZV
 RNXKZG\ RNXOYJ[G\ RUXXZZ\[\[[ZZXYUX
  595 69D_MFNGOIPIPHOGMF RVFTJ RVFWGTJ RGJ]J[HYJ RYJ\I RIMI\ RIMJNJ\ RJN
ON RONOZN[ RNNOMPNPZO\N[LZ RJROR RJVOV RTOTX RTOUOUX RZMZZY[ RZM[M[ZZ\Y[
WZ
  617 40D_KGIFI[ RJGJ[ RJGYG RXGYF[GZI RYGYWXYWZ RYXYYXZ RZGZYY[X[WZUY R
QGQP RRGRP RJPYP
  619 57D_JGHFH\ RIGI\ RIG[G RZG[F]G\I R[G[XZZY[ R[Y[ZZ[ R\G\Z[\Z\Y[WZ R
LKXKWJVK RNNNW RNNOOOW ROOUO RUOUW RTOUNVOVW ROVUV
  622 69D_LGJFJTIYH[ RKGKTJXIZG\ RKG[G RZG[F]G\I R[G[ZZ[ R\G\Z[\Z[XZ RSJ
TIRIRP RSJSP ROLWLVKUL RNPXPWOVP ROROY RORPSPY RPSUS RUSUY RTSURVSVY RPX
UX
  638 75D_HGIHJJKJKIJHHG RLMIUGUIVIYHZI[J[KZJYJULM RIZJZ RTFRFQIONNP RSF
QJ RTFNP RPL[L RZL[K]M[N R[L[N R\L[NYP RTLTPSTRVPY RULUPTTRWPYM[ RUPVTWV
YY\[]Z RWVYX]Z
  642 83D_HGIHJJKJKIJHHG RLMIUGUIVIYHZI[J[KZJYJULM RIZJZ RTFRFQIOMMP RSF
QJ RTFRJONMP RTFUIVKXN[P]O RYN[O RTFUHWKYM]O RQOVOUNTO RNSYS RXSYR[SZU R
YSYYXZ RZSZYY[XZVY RSSS\ RTST\
  665 41D_HGZG RYGZF\GZK RZGYVXYWZ RYXYYXZ R[GZYY[X[WZUY RQGQIPPOTMWKYH[
 RRGRKQQPTOVMXJZH[
  667 60D_KGLFJFJUKVOVPUOT RKGKTLUNUOTOR RGNQKOJOK ROGZG RYGZF\GZJ RZGYX
XZW[ RYYYZX[ R[GZZY\X\W[UZ RTGTMSSRVPYN[ RUGUMTSSVQYN[L\
  703 90D_NHNFOEMEMH RIGHIGJGKHKIIIG RIHRH RQHRGTIRJ RRHRJ RSHRJQK RMJMR
 RMJNJNR RJLRLQKPL RJOROQNPO RHRTRSQRR RITI[ RITJUJ[ RJUQU RQUQ[ RPUQTRU
R[ RJZQZ RVHVU RVHWHWU R[F[YZZ R[F\F\Y[[ZZXY
  715 44D_RHSGQFQJPQOTMWKYH[ RRGRKQQPTOVMXJZH[ RHLZL RYLZK\L[N RZLYVXYWZ
 RYXYYXZ R[L[NZYY[X[WZUY
  716 53D_LGMFKFKNJTIWG[ RLGLNKSJVIXG[ RGKPK RPKPTOYNZ ROKPJQKQTPYO[NZLY
 RTITZ RTIUJUZ RUJ[J R[J[Z RZJ[I\J\Z RUY[Y
  730 84D_HHPFQG RHHQG RLHL[ RMGMZ RGKRKQJPK RHMHT RHMINIT RINPN RPNPT R
ONPMQNQT RIQPQ RHTQT RGWRWQVPW RG[QZ RG[H\QZ RWHXGVFVSUXTZ RWGWSVWTZR\ R
SM[M R[M[VZZY[ RZM[L\M\V[ZZ\Y[WZ
  751 45D_OGPFNFN\ ROGO\ RGNNN RGXNU RGXHYNU RUHVGTFTZU[\[]Z\X R[Z\Z\Y R
UGUYVZZZ\X]U R[KUP R[K\LUP
  768 16D_RHSGQFQ\ RRGR\ RGO]O[MYO RYO\N
  770 40D_RHSGQFQR RRGRR RHL\LZJXL RXL[K RLRJQJ\ RKRK\ RKRXR RWRXQZRYT R
XRX\ RYRY\ RK[X[
  775 58D_TEREQK RSERH RTEQK RGG]G[FZG RPKNJNX ROKOX ROKYK RXKYJ[KZM RYK
YX RZKZX ROOYO ROSYS ROWYW RJNKMIMI\ RJNJ\ RJ[][[ZZ[
  778 67D_RGSFQFQL RRGRL RGH]H[GZH RJLHKH\ RILI\ RILZL RYLZK\L[N RZLZZY[
 R[L[ZZ\Y[WZ RNLOPPPPONL RULSQ RULVMSQ RLQXQWPVQ RQQQ[ RRQR[ RLUXUWTVU
  783 68D_SEQEPJ RREPJ RSEPJ RGG]G[FZG RMJKIKT RLJLT RLJWJ RVJWIYJXL RWJ
WT RXJXT RLMWM RLPWP RLSWS RGV]V[UZV RMXI[G\ RMXNYLZG\ RUXWYZ\[\[[ZZXYUX
  790 84D_LGMFKFKM RLGLM RGIQIPHOI RGLGT RGLHMHT RHMOM ROMOT RNMOLPMPT R
HPOP RHSOS RKSK\ RLSL\ RGWQWPVOW RXFWFVIUK RXFWHUKSM RXFYIZK\M]L RYI[K]L
 RTP\P[OZP RWPW\ RXPX\ RSU]U\T[U
  791 92D_IFJGKILILHKGIF RGIHJILJLJKIJGI RNIJOHOJPJRISJTKTLSKRKONI RJSKS
 RRFPJNM RRFSGNM RWFUJ RWFXGUJ RUJUS RVJVS RPJPS RQJQS RPJ\JZIYJ RQM[MZL
YM RQP[PZOYP RPS\SZRYS RRVSUQUQ\ RRVR\ RGW]W[VZW
  798 24D_RHSGQFQ[ RRGR[ RRP[PYNWP RWPZO RG[][[YY[ RY[\Z
  804 65D_RGSFQFQN RRGRN RRJ\JZIYJ RLNJMJV RKNKV RKNXN RWNXMZNYP RXNXV R
YNYV RKUXU RIXHZG[G\H\IZIX RMXN\O\O[MX RSXT\U\U[SX RXXZZ[\\\\[ZYXX
  817 58D_MGKFKOJUIXHZ RLGLOKTJWHZG[ RLG]G[FZG RLMYM RWMXLZNXO RXMWPVRTU
PYM[ RYNWRUURXOZM[J\ RPMPOQRRTTWVYY[[\][ RQRSUVXZZ][
  818 45D_LGJFJRIWHZG\ RKGKSJWIYG\ RKG]G[EYG RYG\F RTJUISIS[ RTJT[ RMP[P
YNWP RWPZO RK[][[YY[ RY[\Z
  825 76D_LGJFJUIYG\ RKGKUJXIZG\ RKG]G[FZG RTGSK RTGUHSK RQKOJOS RPKPS R
PKYK RXKYJ[KZM RYKYS RZKZS RPOYO ROSZS RTSTZS[ RUSUZT\S[QZ RPVMZ RPVQWMZ
 RXVZX[Z\Z\Y[XXV
  855 45D_IHXH RWHYG[IXK RXHVNTRRUPWMYG[ RYHWM RZHXMVQTTQWNYKZG[ RLKMMOP
RTVXYZ[[]Z RLKNNQRUVXXZY]Z
  859 71D_HGQG RNGOFQGOJ ROFNMMRLUJY RPGOMNQMTLVJYH[ RIKLONRPVQVQUPSMOIK
 RQG\G RYGZF\GZJ RZFYMXRWUUY R[GZMYQXTWVUYS[Q\ RTGTJUPVSWUYX\[]Z RTJUOVR
WTYW]Z
  868 24D_LJJIJZ RKJKZ RKXYX RKJYJ RXJYI[JZL RYJYZ RZJZZ
  878 46D_RITGRFPKNOLRIV RSGQLOOLSGX RGJ]J[HYJ RYJ\I RORMQM\ RNRN\ RNRYR
 RXRYQ[RZT RYRY\ RZRZ\ RN[Y[
  882 63D_NGLFLM RMGMM RMGWG RVGWFYGXI RWGWM RXGXM RMLWL RGP]P[NYP RYP\O
 RMPKW RNPLW RMTXT RWTXSZTXW RXTWXVZT[ RWZV[U[ RYTXYW[V\U\T[RZ
  885 88D_GIGU RGIHJHU RHJLJ RLJLT RKJLIMJMT RHSLS RQGQMPROUNWLZ RRGRMQR
PUNXLZI\ RRMSQUUWX[\][ RXX[[ RRMSPTRVUZY][ RNGYG RWGUN RVGWFYGXHVN RUN[N
 RZN[M]N[P R[NYRWUTXQZM\ R\NZRXUUXRZP[M\
  913 61D_HGHU RHGIHIU RIHLH RLHLT RKHLGMHMT RISLS RVGWFUFU\ RVGV\ RPK\K
ZJYK ROO]O[NZO RTORROVLY RUPSSPVLYJZ RVOWRXTZW\Y]X RXT[W]X
  923 72D_NGLFLO RMGMO RMGVG RUGVFXGWI RVGVO RWGWO RMNVN RJSHRH[ RISI[ R
ISNS RMSNRPSOU RNSN[ ROSO[ RIZNZ RVSTRT[ RUSU[ RUSZS RYSZR\S[U RZSZ[ R[S
[[ RUZZZ
  931 77D_LGMFKFKPJQ RLGLPKRIP RGIOINHMI RGMOL RGMHNOL RTHRGRMQQPS RSHSM
RPPS RTHYF[G RSHTH[G RSL]L[KZL RWLWR RXLXR RMUKTK\ RLUL\ RLUWU RVUWTYUXW
 RWUW\ RXUX\ RL[W[
  973 95D_HGHU RHGIHIU RIHLH RLHLT RKHLGMHMT RISLS RWEUETH RWETH RRHPGPQ
 RQHQQ RQHYH RXHYG[HZJ RYHYQ RZHZQ RQKYK RQNYN RPQZQ RTQSVRXPZL\ RTQURTV
SXQZO[L\ RXRYTZTZSXR ROV]V\U[V RVVWYY[[\][ RVVWXXYZZ][
  994113D_IFIM RIFJGJM RJGOG ROGOM RNGOFPGPM RJLOL RSFSM RSFTGTM RTGYG R
YGYM RXGYFZGZM RTLYL RQMOPLSIUGV RQMRNOQMSJUGV RGP]P[OZP RSPVSYU[V]U RTQ
WSYT]U RJUJ\ RJUKVK\ RKVOV ROVO\ RNVOUPVP\ RK[O[ RSUS\ RSUTVT\ RTVXV RXV
X\ RWVXUYVY\ RT[X[
 1025 49D_JIHHHZ RIIIZ RII[I RZI[H]I\K R[I[Z R\I\Z ROIONNRMT RPIPNOQMTKV
 RSISSTTXTYSXR RTITRUSWSXRXP RIY[Y
 1026 52D_JGHFH\ RIGI\ RIG[G RZG[F]G\I R[G[\ R\G\\ RRJSIQIQOPSNVLX RRJRO
QSOVLX RKMYMXLWM RTSVUWWXWXVWUTSRR RI[[[
 1028 45D_JGHFH[ RIGI[ RIG[G RZG[F]G\I R[G[[ R\G\[ RNKNV RNKOLOV ROLUL R
ULUV RTLUKVLVV ROUUU RIZ[Z
 1034 60D_JGHFH\ RIGI\ RIGZG RYGZF\G[I RZGZ\ R[G[\ RI[Z[ RLKMNNNNMLK RPI
QLRLRKPI RVJSPQSNW RVJWKVMTPQTNWLY RLQORRTVXWXWWUURSPRLQ
 1036 58D_JGHFH\ RIGI\ RIGZG RYGZF\G[I RZGZ\ R[G[\ RRJSIQIQQ RRJRQ RLLXL
WKVL RMPMX RMPNQNX RNQUQ RUQUX RTQUPVQVX RNWUW RI[Z[
 1037 51D_JGHFH\ RIGI\ RIG[G RZG[F]G\I R[G[\ R\G\\ RKKYKXJWK RQKQW RRKRW
 RLQXQWPVQ RKWYWXVWW RTSUUVUVTTS RI[[[
 1045 97D_JFHEH\ RIFI\ RIF[F RZF[E]F\H R[F[\ R\F\\ RQHPKMQKT RQHRIPMNPKT
 RLHMKNKNJLH RUHTK RUHVITK RLLXLWKVL RSLTOVRXTYS RTOVQYS RKOYOXNWO RNRSR
 RSRSU RRRSQTRTU RNTNXOYVYWXVW RNTOUOWPXUXVWVV ROUTU RI[[[
 1050 24D_RHSGQFQ[ RRGR[ RIP[PYNWP RWPZO RG[][[YY[ RY[\Z
 1051 47D_RGSFQFQR RRGRR RIL[LYJWL RWLZK RGR]R[PYR RYR\Q RQRL[ RQRRSL[ R
I[XZ RI[K\XZ RVVXXZ\[\[[ZYXWVV
 1055 49D_RFPFOIMMKPGU RQFOJ RRFPJNMKQGU RGI]I[GYI\H RLPMOKNK\ RLOL\ RUN
VMTLT[ RUMU[ RNR\RZQYR RL[][[YY[\Z
 1056 67D_KGLFJFJW RKGKV RGMOMNLMM RGWNV RGWHXNV RRISHQGQZR[\[]Z\X R[Z\Z
\Y RRHRYSZZZ\X]V RWHXGVFVW RWGWW RNPZK[K RZK[J]K\M R[K[RZS R\K\R[TZSXR
 1065 65D_KGLFJFJV RKGKU RGLNLMKLL RGVNU RGVHWNU RSFQKOO RSFTGSIOO RRJ[J
 RZJ[I]J[N R[JZWYYXZ RZXZYYZ R\J[YZ[Y[XZVY RROXOWNVO RPUXS RPUQVXS
 1077 63D_GGSGRFQG RJGJKIPHR RKGKKJOIQGS RNGNR ROGOR RJLSLRKQL RVGVO RVG
WGWO R[F[QZR R[F\F\Q[SZRXQ RRSSRQRQ[ RRSR[ RIV[VYUXV RG[][[ZZ[
 1098 71D_NFOEMEMQ RNFNQ RVFWEUEUQ RVFVQ RHH\HZGYH RNKUK RNNUN RGQ]Q[PZQ
 RMQLSJVGZ RMQNRGZ RUQVSXVZX\Y]X RVSXU[W]X RRTSSQSQ[ RRTR[ RNWVWUVTW RI[
[[YZX[
 1109 86D_KGLFJFJV RKGKU RGLNLMKLL RGVMU RGVHWMU RSGTFRFRK RSGSK RYGZFXF
XK RYGYK RNI]I\H[I RULRPOS RULVMTOOS RULWOYQ\S]R RWOZQ]R RSSXSWRVS RQUQ\
 RQURVR\ RRVYV RYVY\ RXVYUZVZ\ RR[Y[
 1113 97D_KGLFJFJV RKGKU RGLNLMKLL RGVMU RGVHWMU RQFQN RQFRGRN RRGYG RYG
YN RXGYFZGZN RRJYJ RRMYM ROP]P\O[P RQPPTOV RQPRQQSOV RQS\S R\S[ZZ[ R[S\R
]S\Z[\Z[XZ RTSSVQXOY RUSTVRXOY RXSWVVXTZR[O\ RYSXVWXUZS[O\
 1125 88D_KGLFJFJV RKGKU RGLNLMKLL RGVNU RGVHWNU RSFQKON RSFTGRJON RSI\I
[HZI RQLQR RQLRMRR RRMYM RYMYR RXMYLZMZR RRQYQ ROTO[ ROTPUP[ RPU[U R[U[[
 RZU[T\U\[ RSUS[ RTUT[ RWUW[ RXUX[ RN[][
 1135 98D_KGLFJFJU RKGKT RGLNLMKLL RGUNT RGUHVNT RVHVGWFUFUH ROH]H[GZH R
RISLTLTKRI RXIWM RXIYJWM RPM\M[LZM RPOPV RPOQPQV RQPYP RYPYV RXPYOZPZV R
QSYS RPVZV RSVRXPZL\ RTVSXQZO[L\ RVVV[W\\\][\Z RWVWZX[[[\Z]X
 1137 92D_KGLFJFJV RKGKV RGLNLMKLL RGVNU RGVHWNU RQFRGSITITHSGQF RZFXFWI
 RZFWI RUJUR RVJVR RQJOIOR RPJPR RPJ[J RZJ[I]J\L R[J[R R\J\R RPN[N ROR\R
 RQTQ\ RQTRUR\ RRUYU RYUY\ RXUYTZUZ\ RRXYX RR[Y[
 1160 24D_RHSGQFQ[ RRGR[ RGN]N[LYN RYN\M RI[[[YYW[ RW[ZZ
 1161 64D_QFOFMJKMGR RPFNI RQFOIKNGR ROIXI RWHUKROORKUHW RVIWHXIUMQQMTHW
 RNJPMSPWS[U]T RWR[T RPMTPXR]T RQTRUSWTWTVSUQT RMYQZT[V\W\W[SZMY
 1162 80D_KIMGKFJKIOHR RLGKKJNGT RKKQK RPJOONRLVJY ROKPJQKPOORNTLWH[ RJN
JQKULWNYPZT[\[]Z RJQKTLVNXPYTZ]Z RVGTFTQSTRV RUGUQTTQW RUGYG RXGYF[GZI R
YGYUZV]V]T]R RZGZT[U\U]T
 1163 62D_RFPFMJJM RRFNJJMGO ROIXI RWHTLRNNQJSGT RVIWHXISNOQKSGT ROIPKRN
UQXS[T]S RRNUPYR]S RLTL\ RLTMUM\ RMUVU RVUV\ RUUVTWUW\ RM[V[
 1167 48D_PIRGPFOJMNKQHT RQGPJNNLQHT RPJ[J RYJZI\KYM RZIXOVSSWOZM[ R[JYP
XRVUSXPZM[I\ ROMPNRQSSTSTRSPQNOM
 1168 66D_MFLJKMJOHR RMFNGMKLMJPGS RMKTK RQKRJTKSL RRKQOPROTMWJZG\ RSLRP
QSOVLYI[G\ RKOMQNSOSORNQKO RXHYGWFW\ RXGX\ RTKUNWQYS\U]T RTKUMXQ[S]T
 1169 81D_SFQFNIJL RSFOILKHM RPHXH RWHXGZIXJ RXHTLPOLQ RYIVLSNOPLQHR RNK
OLPNQNQMPLNK RUPSPPSMUKVHW RUPSRPTLVHW RSR[R RZR[Q]S[T R[RWVTXPZM[H\ R\S
YVVXRZN[H\ RQURVSXTXTWSVQU
 1170 67D_QGRFPFOHMKJNGP RQGOJLMIOGP RPHYH RWHXGZIWK RXHVKSOPRLUIW RYIUN
QRMUGX RNLOMPOQOQNPMNL RRSPRP\ RQSQ\ RQS[S RZS[R]S\U R[S[\ R\S\\ RQ[[[
 1171 46D_QFQLPQNULXJZG\ RRGRK RQFSGRNQROVLYI[G\ RGM]M[KYM RYM\L RSMTQUT
VVXY[\][ RYY[[ RSMTPVTXWZY][
 1172 54D_SGQFQLPQNULXJZG\ RRGRK RSGRNQROVLYI[G\ RGM]M[KYM RYM\L RSMTQUT
VVXY[\][ RYY[[ RSMTPVTXWZY][ RPVQWRZSZSYRWPV
 1185 54D_PFOJKV RQGPJ RPFRGQIONLV RGL]L[JYL RYL\K RVLUPSTQWOYL[H\ RWLVO
 RXLVQUSSVPYM[H\ RNTRUTVWX[[\[\Z[YXWVVSUNTLT
 1189 61D_LFKKIRHU RLFMGLKJRIU RGKPK RPKOPNSMUKXG\ ROKPJQKPPOSNULXJZG\ R
LUOXPZQZQYOWLUJT RTITZ RTIUJUZ RUJ[J R[J[Z RZJ[I\J\Z RUY[Y
 1208 80D_KFHT RKFLFIT RGKNK RNKMPLSJWG[ RMKNJOKNPMSLUJXG[ RKUMXN[O[OZMW
KUIS RVFSN RVFWGSN RQN[M RQNRO[M RYK[M\O]O]N\MYK RTSRRR[ RSSS[ RSSZS RYS
ZR\S[U RZSZ[ R[S[[ RSZZZ
 1264 41D_JGXG RWGXFZHWI RXGWI RYGWITK RSLTKRKRWQZP[NZ RRYRZQ[ RSLSZR\Q\
P[ RGQ]Q[OYQ RYQ\P
 1267 56D_GH]H[FYH\G ROIRGPFNKKQHV RQGNMLPHV RLPL\ RMNM\ RNLZL RYLZK\MYN
 RZLYN R[LYNVP RUPUZT[ RUPVPVZU\T[RZ ROT]T[RYT\S
 1271 86D_KFLGMININHMGKF RPFQGRISISHRGPF RYFWFVI RYFVI RIIHKGLGMHMIKII R
IJ[J RZJ[I]KZL R[JZL R\JZLYM RLNVN RUNVMXOUP RVNUP RWNUPRR RQRQXPZO[ RQY
QZP[ RQRRRRZQ\P\O[MZ RGT]T[RYT RYT\S
 1280 57D_RHRGSFQFQH RIHHJGKGLHLIJIG RIH[H RZH[G]IZJ R[HZJ R\HZJYK RKMYM
WKUMXL RQMQXPZO[ RQYQZP[ RRMRZQ\P\O[MZ RGS]S[QYS\R
 1281 70D_RHRGSFQFQH RIHHJGKGLHLIJIG RIH[H RZH[G]IZJ R[HZJ R\HZJYK RKLWL
 RVLWKYMVN RWLVN RXLVNSP RRQSPQPQXPZO[ RQYQZP[ RRQRZQ\P\O[MZ RGT]T[RYT R
YT\S
 1291 64D_RHRGSFQFQH RIHHJGKGLHLIJIG RIH[H RZH[G]IZJ R[HZJ R\HZJYK RRKSJ
QJQ[ RRKR[ RLOJNJ\ RKOK\ RKOXO RWOXNZOYQ RXOX\ RYOY\ RKUXU RK[X[
 1296 68D_RHRGSFQFQH RIHHJGKGLHLIJIG RIH[H RZH[G]I[J R[H[J R\H[JZK RIMZM
XLWM RQMQZ RRMRZ RRSZSXRWS RMOKTIXG[ RMONPLTJWG[ RKULWOZS[\[]Z RLWOYSZ]Z
 1297 73D_RHRGSFQFQH RIGHIGJGKHKIIIG RIH[H RZH[G]I[J R[H[J R\H[JZK RQJQQ
PUOWMYJ[G\ RRJRRQUPWNYK[G\ RSTUXWZY[\\][ RSTUWWYYZ][ RJLZLYKXL RJPZPYOXP
 RGT]T[SZT
 1300 75D_RHRGSFQFQH RIGHIGJGKHKIIIG RIH\H RZH[G]I[J R[G[J R\H[JZK RJLZL
YKXL RQLOP RQLRMOP RHQXP RHQJRXP RUNWOZR[R[QZPXOUN RRTSSQSQ[ RRTR[ RJVZV
YUXV RG[][[ZZ[
 1311101D_RHRGSFQFQH RIHHJGKGLHLIJIG RIH[H RZH[G]I[J R[H[J R\H[JZK RJLZL
YKXL RQLONKQ RSLOOKQHR ROOQRRVRXQZP[ RRYRZQ[ ROOQQRSSVSZR\Q\P[NZ RQQKU R
QRKUHV RRUOWKY RRVPWKYHZ RSMTQUTVVYY[Z]Y RTQUSWVZX]Y RZOVS RZO[PVS
 1316102D_RHRGSFQFQH RIGHIGJGKHKIIIG RIH[H RZH[G]I[J R[G[J R\H[JZK RMLMR
NSWSXRWQ RMLNLNQORVRWQWO RIMHOGPGQHQIOIM RPIQLRLRKPI RZN[O\Q]Q]P\OZN RVK
SNOQKS RVKWLSOPQKSGT RQUQ[ RQURUR[ RIVI\ RIVJVJ\ RJ[Y[ RYVY\ RYVZVZ\
 1322 95D_RHRGSFQFQH RIGHIGJGKHKIIIG RIH[H RZH[G]I[J R[H[J R\H[JZK ROKPJ
NJNR ROKOR RUKVJTJTR RUKUR RJLZLYKXL RJOZOYNXO RGR]R[QZR RNRJWGZ RNROSLV
GZ RURVUWWYY\Z]Y RVUXWZX]Y RQUSWTWTVQU ROYRZU\V\V[TZOY
 1354111D_IEJFKHLHLGKFIE RGLKL RJLKKMLLN RKLKQGTHULQ RLLLQ RLQNTPU\U]T R
LQNSPT]T RRESHTHTGRE RZEXEWH RZEWH ROH]H\G[H RUHTK RUHVITK RPJPR RPJQKQR
 RQKZK RZKZR RYKZJ[K[R RQMZM RQOZO RQQZQ RVUV[U\ RWUW[V]U\S[ RGX]X[WZX R
LYMZN\O\O[NZLY
 1355 40D_SHTGRFRWQZP[ RRYRZQ[ RSGSZR\Q\P[NZ RMLLPJTHW RMLNMMPLRJUHW RVM
XOZR[V\V\T[RYOVM
 1358 63D_RHSGQFQP RRGRP RJILKMNNNNMMKJI RXITO RXIYJTO RGP]P[NYP RYP\O R
OPORNVLYJ[H\ RPPPROVMYK[H\ RSPS[T\\\][\Y R[[\[\Z RTPTZU[Z[\Y]V
 1359 43D_KGLIMLNLNKMIKG RRHSGQFQN RRGRN RXGTM RXGYHTM RINYN RXNYM[NZP R
YNY[ RZNZ[ RITYT RIZYZ
 1364 93D_RGSFQFQJ RRGRJ RKFMININHKF RWFTJ RWFXGTJ RIIHKGLGMHMIKII RIJ[J
 RZJ[I]K[L R[I[L R\J[LZM RKLKQ RKLLMLQ RLMWM RWMWQ RVMWLXMXQ RKQXQ RQQQ\
 RRQR\ RJSJ[ RJSKTK[ RKTXT RXTXYWZ RWTXSYTYYX[WZUY
 1377 43D_MGKFKTJXIZ RLGLTKWIZG\ RLGWG RVGWFYGXI RWGWN RXGXN RLMWM RQNRQ
SSUVXY[[]Z RRQTTWWZY]Z
 1383 58D_JFJSIXHZ RJFKGKSJWHZG[ RKGZG RZGZK RYGZF[G[K RKK[K RMPTNWMYN R
MPYN RRORZS[\[]Z\Y RSOSYTZ[Z\Y]W RMTZRYQXR RLX[VZUYV
 1386 70D_LGJFJTIYH[ RKGKTJXH[G\ RKGZG RYGZF\G[I RZGZM R[G[M RKLZL RTNT[
 RTNUNU[ ROOOT ROOPOPT RPSYS RYOYT RYOZOZT RNVN\ RNVOVO\ RO[Z[ RZVZ\ RZV
[V[\
 1387 66D_LGJFJTIYH[ RKGKTJXH[G\ RKGZG RYGZF\G[I RZGZM R[G[M RKLZL RTNUM
SLSU RTMTU RKP]P[OZP RPUNTN\ ROUO\ ROUYU RXUYT[UZW RYUY\ RZUZ\ RO[Y[
 1402 92D_IFIVHZG\ RIFJGJVIYG\ RJG[G R[G[J RZG[F\G\J RJJ\J RQJRMSMSLQJ R
WJUM RWJXKUM RTMTS RUMUS RMLMS RMLNMNS RNM[M R[M[S RZM[L\M\S RNP[P RMS\S
 ROUO\ ROUPVP\ RPVYV RYVY\ RXVYUZVZ\ RPYYY RO\Z\
 1407 27D_RHSGQFQY RRGRY RJLKKIJI[ RJKJ[ RJYYY RZL[KYJY[ RZKZ[
 1418 80D_RERI RRESESI RJFJI RJFKFKI RJI[I RZFZI RZF[F[I RJLJUIYG\ RJLKM
KVJYG\ RKM\MZLYM RSOSRRVQXOZK\ RSOTOTRSVRXPZN[K\ RTRUUWXZ[\\][ RWXZZ][ R
PQNTNUOUPQ RZRYQUU RZRUU
 1431111D_QEQI RQERERI RIFII RIFJFJI RYFYI RYFZFZI RIIZI RKLIKIWHZG\ RJL
JWIZG\ RJLYL RXLYK[LZN RYLYUZY[[\\]\]Z]X R[Z\[][ RZLZU[Y\Z]Z RMOTNVO RMO
VO RQOQY RRORY RMQMV RMQNRNV RNRUR RURUV RTRUQVRVV RMVVV RLZUY RLZN[UY R
TXUYV[W[WZVYTX
 1447 28D_KHLGJFJUIYG\ RKGKVJYG\ RSITHRGRY RSHSY R[H\GZFZ\ R[G[\
 1451 22D_IH[HYFWH RWHZG RQHQZ RRHRZ RGZ]Z[XYZ RYZ\Y
 1455 45D_QISGQFOLMQKUG[ RRGQJOOMSKVG[ RGJ]J[HYJ RYJ\I RMR[RYPWR RWRZQ R
SRS[ RTRT[ RK[][[YY[ RY[\Z
 1459 76D_GIOINHMI RKIKU RLILT RGUOT RGUHVOT RPG]G[FZG RVGUK RVGWHUK RSK
QJQW RRKRW RRKZK RYKZJ\K[M RZKZW R[K[W RROZO RRSZS RQW[W RSXO[M\ RSXTYRZ
M\ RXX\\]\][\ZXX
 1466 79D_JFKGLIMIMHLGJF RQHSGQFOKMOKR RRGPKNNKRHU RWGVFTJ RWGTJ RHJ\JZI
YJ RTKUMWPYR\T]S RUMXP[R]S RGN]N[MZN RNRUR RURUW RTRUQVRVW RNVUV RMUMZN[
Z[[ZZY RMUNVNYOZYZZYZW
 1468 58D_PFNJKOHS RPFQGMMJQGT RFJ]J[HYJ RYJ\I RSMTLRLR\ RSMS\ RMPKOKZ R
LPLZ RLPYP RXPYO[PZR RYPYVXXWY RYWYXXY RZPZXYZXZWYUX
 1469 66D_LHMGKFK\ RLGL\ RGJGW RGJHKHW RHKOK ROKOUNV RNKOJPKPUOWMU RSFST
RXQZO\ RSFTGTTSXRZO\ RTGYG RYGYZZ[][]Y]W RXGYFZGZY[Z\Z]Y RUNWRXRXQUN
 1484 85D_LHMGKFK\ RLGL\ RGJGW RGJHKHW RHKOK ROKOUNV RNKOJPKPUOWMU RRG]G
\F[G RTJTP RTJUKUP RUKZK RZKZP RYKZJ[K[P RUOZO RWSW[ RXSX[ RSRS\ RSRTST\
 RTS[S R[S[\ RZS[R\S\\ RTW[W RT[[[
 1492 22D_IG[GYEWG RWGZF RQGQ] RRGR] RGP]P[NYP RYP\O
 1496129D_RGSFQFQORTTXW[Y\\\][\Z RRGROSTUXWZY[[[\Z]W RKFJJ RKFLGJJ RHIJL
KLKKHI RNIJO RNIOJJO RGONO RGOHPNO RNMOPPPPONM RWFVJ RWFXGVJ RTIVLWLWKTI
 RZIVO RZI[JVO RSOZO RSOTPZO RZM[P\P\OZM RVPWRXRXQVP RGS]S[RZS RKSKVJYH\
 RLSLVKYH\ RLVMWNYOYOXNWLV RXUUXRZN\ RXUYVXWUYQ[N\
SHAR_EOF
if test 26757 -ne "`wc -c 'hersh.or1'`"
then
	echo shar: error transmitting "'hersh.or1'" '(should have been 26757 characters)'
fi
echo shar: extracting "'hersh.or2'" '(27782 characters)'
if test -f 'hersh.or2'
then
	echo shar: over-writing existing file "'hersh.or2'"
fi
cat << \SHAR_EOF > 'hersh.or2'
 1504 65D_SISGTFRFRI RKIIHITHYG[ RJIJTIXG[ RJI]I[GYI RYI\H RRPSOQNQZR[X[
YZXY RRORYSZWZXYXW RNTMVLWLXMXNVNT RTLUMVOWOWNVMTL RZT[U\W]W]V\UZT
 1508 74D_SHSGTFRFRH RKHIGITHYG[ RJHJTIXG[ RJH]H[GZH RPLNKNX ROLOX RPLYJ
[K RNLOL[K RUKUQVUXXZZ\[]Z\Y RZY\Z RVKVQWUYX[Y\Y]W ROQ]Q[PZQ RKYTV RKYLZ
TV RO[W[VZU[
 1511 72D_SHSGTFRFRH RIGIUHYG[ RIGJHJUIXG[ RJH]H[GZH ROIOQ ROIPIPQ RUIUQ
 RUIVIVQ RJL]L[KZL RPPUP RMSYS ROSQVSXVZX[\\][ RSXUYXZ][ RXRTVPYM[ RXRYS
TWQYM[J\
 1514 92D_SHSGTFRFRH RIGIUHYG[ RIGJHJUIXG[ RJH]H[GZH RJKPK ROJMR RNKOJPK
NR RMRRR RQQPUOWMZ RPRQQRRQUOXMZJ\ RMTLULW RMTLW RMTNWPZS[\[]Z RNWPYSZ]Z
 RSLWKZJ\K RSL\K RWKWW RXKXW RSQ]Q\P[Q RSW]W\V[W
 1515 78D_SHSGTFRFRH RHGHUGYF[ RHGIHIUHXF[ RIH]H[GZH RSKTJRJR[ RSKS[ RNK
MNLPJS RNKOLNNLQJS RMPNQOSPSPROQMP RXKWNVPTS RXKYLXNVQTS RXPYQZS[S[RZQXP
 RKV[VZUYV RI[][[ZZ[
 1556 60D_SGTFRFRKSQTTUVWYY[[\\\][\Z RXYYZ[[\[ RSGSKTQUTWWYY[Z\Z]W RVFWG
XIYIYHXGVF RGK]K[JZK RGPPPOONP RKPKY RLPLY RGZRW RGZH[RW
 1560 49D_IGXG RWGXFZGYI RXGXN RYGYN RKMXM RLMJLIT RKMJT RJSZS RYSZR\SZU
 RZSXYWZU[ RXZW[V[ R[SYYX[W\V\U[RZ
 1562 57D_HGPG ROGPFRGQI RPGPM RQGQM RJLPL RIKHR RIKJKIR RIQQQ RPQQPSQQT
 RQQOYNZL[ ROZN[M[ RRQPYO[N\M\L[JZ RZH[GYFY\ RZGZ\
 1567 85D_GGLG RLGLM RKGLFMGMM RGKGS RGKHLHS RHLLL RHRLR RLRKZJ[ RKRLQMR
LZK\J[HZ RPHPUOZN\ RPHQIQUPYN\ RQIZF\G RQI\G RZGZT[Z\\][ RZT[X\Z][ RUJUZ
 RUJVJVY RRZXY RRZS[XY RXWY[Z[ZZXW
 1568 86D_GGLG RLGLM RKGLFMGMM RGKGS RGKHLHS RHLLL RHRLR RLRKZJ[ RKRLQMR
LZK\J[HZ RVGWFUFUJ RVGVJ RPJ]J[IZJ RUJRQ RUJVKRQ RPPRRSTTTTSSRPP RYOS[ R
YOZPS[ RO[[Z RO[Q\[Z RYX[Z\\]\][\ZYX
 1571103D_HGLG RLGLM RKGLFMGMM RILLL RHKHS RHKILIS RIRLR RLRKZJ[ RKRLQMR
LZK\J[HZ RUFSL RUFVGSL ROL[K ROLQM[K RYI[K\M]M]L\KYI RULU[ RVLVZ RRPPOPV
 RQPQV RQPZP RYPZO\P[R RZPZV R[P[V RQUZU RO[[Z RO[Q\[Z RYX[Z\\]\][\ZYX
 1575 90D_HGMG RMGMM RLGMFNGNM RILML RHKHS RHKILIS RIRMR RMRLZK[ RLRMQNR
MZL\K[IZ RQFRISISHQF RUFVIWIWHUF R[FXK R[F\GXK RQKQU RQKRLRU RRL[L R[L[U
 RZL[K\L\U RVLV\ RWLW\ RRP[P RRT[T RPX]X[WZX
 1582 89D_MHNGLFLTKXJZH\ RMGMULXKZH\ RINHPGQGRHRIPIM RQGYG RYGYM RXGYFZG
ZM RQJYJ RQMZM RQOPQOROSPSQQQO RQP[P RZP[O]Q[R R[P[R R\P[RZS RUPU\ RVPV\
 RQTQ[ RQTRUR[ RRUYU RYUYYXZ RXUYTZUZYY[WY
 1589 62D_KGKSJWIYG\ RLGLSKWIZG\ RPGPZQ[ RQGQ[ RHGUGTFSG RHOUOTNSO R\FYI
VK R\F]G\HYJVK R\MYPVRTS R\M]N\OYQWRTS R\TYWUZ R\T]U\VYXUZR[
 1598 89D_LFHJ RLFMGHJ RLKIPGS RLKMLJPGS RJPJ\ RKOK\ RRGPFPKONNO RQGQKPN
NO RQGVG RUGVFXGWI RVGVMWN\N]M\L RWGWLXM[M\L]J RNQWQ RWQVSTVQYN[ RXQVT R
VQWPYQVUSXPZL\ RPQQSSVUXXZ[[]Z RQSTVWXYY]Z
 1602 68D_LFHJ RLFMGHJ RLKIPGS RLKMLJPGS RJPJ\ RKOK\ ROG[G RZFYHVLRP RYG
ZF[GXKUNRPOR RRHSKUNWPYQ\R]Q RUNYP]Q RUSVRTRT[ RUSU[ ROU[UZTYU RM[][[ZZ[
 1604 95D_LFHJ RLFMGHJ RLKIPGS RLKMLIQGS RJPJ\ RKOK\ RVGWFUFUP RVGVP RRJ
PIPSOWNYL\ RQJQSPWNZL\ RQJ[J RZJ[I]K[L R[J[L R\J[LZN RQPYP RYPXSVVSYP[ R
ZPYR RXPYO[PZRXUUXRZN\ RSPTTVXY[[\][ RYZ[[ RTTVWXYZZ][
 1610100D_LFHJ RLFMGHJ RLKIPGS RLKMLJPGS RJPJ[ RKOK[ RSFQJ RSFTGQJ ROIPJ
QLRLRKQJOI RXHSO RXHYISO RNOZN RNOOPZN RYLZM[O\O\N[MYL RSQRSOWK[ RSQTRRU
OXK[ RTR[R RZQYSWVUXRZO[ RZQ[RYUVXSZO[ RTRUUWXYZ[[]Z RTRUTWWZY]Z
 1613 77D_LFHJ RLFMGHJ RLKIPGS RLKMLJPGS RJPJ\ RKOK\ RQFRGSJTJTISGQF RYF
WK RYFZGWK ROL]L[KZL RULUZ RVLVZ RVR[RZQYR RPPPUOYN[ RPPQPQUPXN[M\ RQVRX
TZW[\[]Z RRXTYWZ]Z
 1614 69D_LFHJ RLFMGHJ RLKIPGS RLKMLJPGS RJPJ\ RKOK\ RVGWFUFUZ RVGVZ RPI
\IZHYI RON]N[MZN RVS[SZRYS RPQPUOYN[ RPQQQQUPXN[M\ RQVRXTZW[\[]Z RRXTYWZ
]Z
 1621 77D_KFGJ RKFLGGJ RKKIOGR RKKLLGR RIPI\ RJOJ\ RRGSFQFQ\ RRGR\ RUGVI
WIWHUG RMLWLVKUL RLWNTOQOONONQMULW RTOUTUVVVVTUQTO RWH]H\G[H RWN]N\M[N R
ZNZZY[ R[N[ZZ\Y[WZ
 1628 84D_KFGJ RKFLGGJ RKKIOGR RKKLLGR RIPI\ RJOJ\ ROFMK ROFPGMK ROHUHTG
SH RQHQX RRHRX RMMVMULTM RRRURTQSR RNQNY RNQOQOY RLYUW RLYMZUW RWGW\ RWG
XHX\ RXH[H R[H[WZX RZH[G\H\W[YYW
 1631113D_JFFJ RJFKGFJ RJKHOFR RJKKLFR RHPH\ RIOI\ RPFPM RPFQFQM RMHMN R
MHNHNN RNMSM RSHSN RSHTHTN RLQUQTPSQ RNQNTMXLZ ROQOTNWLZ RRQRX RSQSX RPY
VV RPYQZVV RXFWJUP RXFYGWLUP RWM]M\L[M R[MZRYUXWVZ R\M[RZUXXVZS\ RWMWPXT
YWZY\\][ RXTYV[Y][
 1638 94D_KFGJ RKFLGGJ RKKGR RKKLLGR RIOI\ RJNJ\ RNHTFUG RNHUG RQGQZ RRG
RZ RMJWJVIUJ RMLMS RMLNMNS RNMUM RUMUS RTMULVMVS RNPUP RMSVS RMVWVVUUV R
MZVY RMZN[VY RWG]G\F[G RWM]M\L[M RZMZZY[ R[M[ZZ\Y[WZ
 1641107D_KFGJ RKFLGGJ RKKIOGR RKKLLGR RIPI\ RJOJ\ RQFOFNIMK RQFMK ROHUH
 RTGQK RTGUHQK RQLQVPYO[ RRLRVQYO[M\ RMKMS RMKNLNS RNLUL RULUS RTLUKVLVS
 RNOUO RNRUR RLVWVVUUV RRXSYT[U[UZTYRX RWH]H\G[H RWN]N\M[N RZNZZY[ R[N[Z
Z\Y[WZ
 1645 56D_OMPLNKNZO[W[XZWX RVZWZWY ROLOYPZUZWXXU RPGRHTJUJUITHPG RSHTI R
JPISGVGWHWIVJSJP RITHV RXOZQ[S\U]U]T\RZPXO R[R\T
 1666 57D_KGLFJFJ\ RKGK\ RHLGNFOFPGPHNHL RLJMKNMOMOLNKLJ RWGXFVFV[ RWGW[
 RSIRLPQOS RSITJRNOS RSL\L[KZL RRS\S[RZS RN[][[ZZ[
 1683 61D_KGLFJFJ\ RKGK\ RHLGNFOFPGPHNHL RLJMKNMOMOLNKLJ ROG]G[FZG RSKQJ
QX RRKRX RRKZK RYKZJ\K[M RZKZX R[K[X RRQZQ RRWZW RO[][[ZZ[
 1710112D_SFTERERJSNUQWSYT\U]T\S RXS[T\T RSFSJTNVQWRZS\S]Q RVEWGXGXFVE R
GI]I[HZI RXLVOSRPT RXLYMVPRSPT RIKIP RIKJLJP RJLNL RNLNP RMLNKOLOP RJONO
 RGSOR RGSHTOR RMVM[N\V\W[VZ RMVNVNZO[U[VZVX RJWIYHZH[I[JYJW RQVRXSXSWQV
 RYWZX[Z\Z\Y[XYW
 1728 92D_MGNFLFLT RMGMT RHJQJPIOJ RLJKMJOHR RLMJPHR RONPPQPQOON RTFTT R
TFUGUT RUG[G R[G[T RZG[F\G\T RUK[K RUO[O RUS[S RMVM[N\V\W[VZ RMVNVNZO[U[
VZVX RQURXSXSWQU RJWIYHZH[I[JYJW RZW[X\Z]Z]Y\XZW
 1731120D_TFUESESJTNVQYT\U]T\S RYS[T\T RTFTJUNWQXRZS\S]Q RWEXGYGYFWE RKI
IHIOHSGU RJIJOIRGU RJI]I[HZI RZMXPUSRU RZM[NXQTTRU RLLQLPKOL RLNLS RLNMO
MS RMOPO RPOPS ROOPNQOQS RLSQS RMVM[N\V\W[VZ RMVNVNZO[U[VZVX RJWIYHZH[I[
JYJW RQVRXSXSWQV RYWZX[Z\Z\Y[XYW
 1743133D_MFKFJH RMFJH RGHPH RGHHIPH ROFPGQIRIRHQGOF RIJIT RIJJKJT RJKOK
 ROKOSNT RNKOJPKPSOUNTLS RJNON RJQOQ RUGVFTFTKUL\L]K\J RUGUJVK[K\J]H RUI
YGZH RUIZH RUOVNTNTSUT\T]S\R RUOURVS[S\R]P RUQYOZP RUQZP RMWM[N\W\X[WZ R
MWNWNZO[V[WZWX RJWIXGYGZHZIYJW RQWSYTYTXQW RZW[X\Z]Z]Y\XZW
 1756103D_KGLFJFJ\ RKGK\ RHLGNFOFPGPHNHL RLKMLNNONOMNLLK RUGUM RVGVM RQF
QM RQFRGRM RRGYG RYGYM RXGYFZGZM ROJ]J\I[J RQMZM RSPQOQY RRPRY RRPYP RXP
YO[PZR RYPYY RZPZY RRSYS RRVYV RQYZY RT[RZO\M] RT[Q\M] RXZZ[\]]]]\[[XZ
 1794 61D_RGSFQFQKRQSTTVVYX[Z\[\\[[Z RWYXZZ[[[ RRGRKSQTTVWXYZZ[Z\W RUFVI
WIWHUF RHK\KZIXK RXK[J RZNXNWQVSTVQYN[ RYNWR RZNXRVUSXPZL\
 1799 84D_KKIJITHYG[ RJKJTIXG[ RJK]K[JZK RJONO RNONVMW RMONNOOOVNXMWKV R
SGTFRFRKSQTTUVWYY[[\\\][\Z RXYYZ[[\[ RSGSKTQUTWWYY[Z\Z]W RVFWGXIYIYHXGVF
 RYQ[OYNXQWSUVRYO[ RZOYRWUTXQZM\
 1802 88D_SGTFRFRKSQTTUVWYY[[\\\][\Z RXYYZ[[\[ RSGSKTQUTWWYY[Z\Z]W RVFWG
XIYIYHXGVF RGK]K[JZK RIMIU RIMJNJU RJNNN RNNNT RMNNMONOT RJSNS RGZPW RGZ
H[PW R[NYNXQWSUVRYO[ RZNXR R[NYRWUTXQZM\
 1817 38D_GG]G[EYG RYG\F RMLKKKSJWIYG\ RLLLSKWIZG\ RLLXL RWLXKZLYN RXLXS
 RYLYS RLRXR
 1823 86D_GG]G[FZG RIIIUHYG[ RIIJJJUIXG[ RJJ[J R[J[N RZJ[I\J\N RJN\N RJQ
RQ RRQRZQ[ RQQRPSQSZR\Q[OZ RLSMUNUNTLS RLXQV RLXMYQV RSQ[Q R[Q[ZZ[ RZQ[P
\Q\Z[\Z[XZ RUSVUWUWTUS RUXZV RUXVYZV
 1827 44D_JIRHVGXFZH RTHYG RJIZH RRHRXQZP[ RRYRZQ[ RSHSZR\Q\P[MZ RIN[NYL
WN RWNZM RHS]S[QYS RYS\R
 1855 58D_KGLFJFJZI[ RKGKZJ\I[GZ RGKOKNJMK RGROP RGRHSOP RTHRGRRQVPXN[ R
SHSRRVPYN[L\ RTHXGZF\G RSHTH\G RSP]P[OZP RXPX\ RYPY\
 1885 54D_LGMFKFKZJ[ RLGLZK\J[HZ RGKPKOJNK RGQOO RGQHROO RQFQV RQFRGRV R
RG[G R[G[V RZG[F\G\V RVGV\ RWGW\ RRN[N RRU[U
 1903 65D_KGLFJFJZI[ RKGKZJ\I[GZ RGKOKNJMK RGROP RGRHSOP RVGWFUFUP RVGVP
 RQK[KZJYK ROP]P[OZP RXPXZW[ RYPYZX\W[UZ RNT]T[SZT RPVQWRYSYSXRWPV
 1904 71D_LGMFKFKZJ[ RLGLZK\J[HZ RHKOKNJMK RHQOO RHQIROO RRGSFQFQNRO\O]N
\M RRGRMSN[N\M]K RRJYGZH RRJZH RQRQ\ RQRRSR\ RRSZS RZSZ\ RYSZR[S[\ RRWZW
 RR[Z[
 1914 95D_KGLFJFJZI[ RKGKZJ\I[GZ RGKNKMJLK RGQNO RGQHRNO RNGTG RSFPO RRG
SFTGQO RPOTO RTOSSQWOZ RSOTNUOTSSUQXM\ RORNSNUOR RORPVQXSZV[\[]Z RORPUQW
SYVZ]Z RUIXH[F]G RUI]G RXHXV RYHYV RUO]O\N[O RUV]V\U[V
 1920 84D_KGLFJFJYIZ RKGKYJ[IZGY RGKNKMJLK RGQNO RGQHRNO RRGPFPROVNXL[ R
QGQRPVNYL[ RQG]G[FZG RQKYKXJWK RQO]O[NZO RTOTY RUOUX RRYYW RRYSZYW RXOXR
YVZX\Z]Y RXRYU[X]Y R\RZU R\R]SZU
 1942 91D_KGLFJFJYIZ RKGKYJ[IZGY RGKOKNJMK RGQNO RGQHRNO RQGQRPVOXM[ RQG
RHRRQVOYM[ RRHWG[F]G RRH]G RRK[K R[K[O RZK[J\K\O RRO\O RVOVTUWSZ RWOWTVW
SZQ[ RXPYRZRZQXP RRT]T\S[T RWTXWZZ\[]Z RXWZY]Z
 1951 90D_KGLFJFJZI[ RKGKZJ\I[GZ RGKNKMJLK RGQNO RGQHRNO RVGWFUFUI RVGVI
 RPI\I[HZI RRJSNTNTMRJ RXJWO RXJYKWO RNO]O\N[O RTPPW RTPUPQW RNS]S[RZS R
XSWUUXR[ RXSYTWWUYR[O\ RSWVXYZ[\\\\[YYWXSWPW
 1987104D_KGLFJFJZI[ RKGKZJ\I[GZ RGKNKMJLK RGRMP RGRHSMP RVGWFUFUI RVGVI
 ROI]I[HZI RRJSMTMTLRJ RXJWN RXJYKWN RQNOMO\ RPNP\ RPN[N RZN[M]N\P R[N[Z
Z[ R\N\Z[\Z[XZ RUNUT RVNVT RRQYQXPWQ RSTSX RTTTX RSTXT RWTWX RXTXX RSXXX
 2039 56D_RGSFQFQN RRGRN RGI]I[GYI RYI\H RJNWN RVNWMYOVQ RWNVQTTQWNYJ[ R
XOWQUTRWOYMZJ[G\ RMNMONRPUSXVZX[[\][ RPUTXVYYZ][
 2044 78D_LGMFKFKQ RLGLQ RGKQKPJOK RHPHY RHPIQIY RIQNQ RNQNY RMQNPOQOY R
IXNX RUFTISKQN RUFVGUISLQN RSK\K[JZK RYKXOWRUVSY RYKZLYPWTTXRZO\ RSLSOTS
UUWXYZ[[]Z RUUWWZY]Z
 2052104D_LGMFKFKM RLGLM RIIOINHMI RGMRMQLPM RQFOJLOIS RQFRGQIOLKQGU RHP
PP ROPPORQOR RPPOR RQPORMS RLSLZK[ RLSMSMZL\K[IZ RIVQU RIVJWQU RVFTKRO R
VFWGVIRO RTM]M\L[M RZMYRXUVXTZQ\ R[MZRYUWXUZQ\ RTMUQVTWVYY\\][ RVTXWZY][
 2056 95D_KGLFJFJN RKGKN ROGPFNFNN ROGON RHIRIQHPI RGNSNRMQN RIPI\ RIPJQ
J\ RJQOQ ROQOZN[ RNQOPPQPZO\N[LZ RJTOT RJWOW RWFVITNSP RWFXGVKSP RTN]N\M
[N RZNYRXUWWUZ R[NZRYUWXUZR\ RUOVTWWXYZ[\\][ RVTXXZZ][
 2057117D_MGNFLFLQ RMGMQ RHGJJKJKIHG RPGNJ RPGQHNJ RGKSKRJQK RKKJMHP RLL
HP RNMONPPQPQOPNNM RLSIX RLSMSJX RGUSURTQU RPUOWMYJ[H\ RQUPWNYK[H\ RKWNY
P[Q[QZPYNXKW RUFTKSN RUFVGUJRP RUK]K\J[K R[KZPYSXUVXTZQ\ R\K[PZSYUWXUZQ\
 RTLUQVTWVYY\\][ RVTXWZY][
 2064 59D_RGSFQFQJ RRGRJ RGJ]J[HYJ RYJ\I RWLXKVJUNTQSSQVNYK[H\ RWKVN RWL
VOTSRVOYL[H\G\ RMJMMNPORQUTXWZ[\][ RXZ[[ RNPPSSVVXXY][
 2067 66D_MGNFLFLJ RMGMJ RGJSJRIQJ RPKNPKUIX RPKQLOPMSIXGZ RHLLQNTPXQXQW
PUMQHL RZG[FYFYXXZW[ RYYYZX[ RZGZZY\X\W[UZ RRM]M\L[M RSPTQUSVSVRUQSP
 2074 81D_NFLFJIFN RNFFN RMGOHRKSKSJRIPHMG RIMQMPLOM RLMLZK[ RMMMZL\K[IZ
 RGQRQQPPQ RISGX RISJTGX ROTPUQWRWRVQUOT RZG[FYFY\ RZGZ\ RTHUIVKWKWJVITH
 RSNTOUQVQVPUOSN RRV]S\R[S
 2080 88D_MHMGNFLFLH RGHSHRGQH RIIJMKMKLII ROINM ROIPJNM RGNSNRMQN RLNL\
 RMNM\ RHRRRQQPR RLQKTJVHY RLTJWHY RNTOUPWQWQVPUNT RUGUSTWRZP\ RUGVHVSUW
SZP\ RVH[F]G RVH]G RVO]O\N[O RZOZ\ R[O[\
 2082 60D_RGSFQFQK RRGRK RGK]K[IYK RYK\J RQKPPOSNULXJZG\ RQKRLQPPSNWLYI[
G\ RQP\P RYPZO\PZS RZPYVXYWZU[ RXZW[V[ R[PZVYYX[W\V\U[RZ
 2083 76D_LHMGKFKNJUIXG\ RLGLOKTJWIYG\ RGKPKOJNK RLOOO ROOOVNZM[ RNOONPO
PVOZN\M[KZ RWFVKUNTP RWFXGWKVMTPRR RXIYL[P\R]Q RYL[O]Q RVRWSXUYUYTXSVR R
UXWYZ\[\[[ZZXYUX
 2084 82D_LHMGKFKNJUIXG\ RLGLOKTJWIYG\ RGKPKOJNK RLOOO ROOOVNZM[ RNOONPO
PVOZN\M[KZ RVFTFRKQM RUFTH RVFTIQM RSK]K[JZK RYKXPWTUX RZKYPXSWUUXSZQ[ R
TKTMURVUXXZZ\[]Z RURVTXWZY]Z
 2097 27D_MHKGK\ RLHL\ RLZXZ RLHXH RWHXGZHYJ RXHX\ RYHY\ RLQXQ
 2100 39D_LGJFJR RKGKR RKGXG RWGXFZGYI RXGXR RYGYR RKLXL RKQXQ RQQQ] RRQ
R] RGV]V[TYV\U
 2107 86D_MGKFKP RLGLP RLGWG RVGWFYGXI RWGWP RXGXP RLKWK RLOWO RNOLRIU R
NOOPLSIUGV RLSYS ROSMVKX ROSPTNVKXHY RTSSUPYM[J\ RTSUTSWQYN[J\H\ RXSYR[S
YU RYSWYVZT[ RWZV[U[ RZSXYW[V\U\T[RZ
 2108 53D_OGPFNFNO ROGOO RUGVFTFTO RUGUO RIJ[JYIXJ RGO]O[NZO RMSKRK\ RLS
L\ RLSWS RVSWRYSXU RWSW\ RXSX\ RLWWW RL[W[
 2110 58D_HFHU RHFIGIU RIGNG RNGNT RMGNFOGOT RIMNM RISNS RTFTSSWRYO\ RTF
UGUSTWRZO\ RUG[G R[G[ZZ[ RZG[F\G\Z[\Z[XZ RUM[M RUS[S
 2119 57D_HFHX RHFIGIX RIGMG RMGMX RLGMFNGNX RIOMO RIWMW RRFPLON RRFSGRI
ON RQJ]J[HYJ\I RUJU\ RVJV\ RVP]P[NYP\O RVV]V[TYV\U
 2121 60D_MGKFKN RLGLN RLGXG RWGXFZGYI RXGXN RYGYN RLJXJ RLMXM RROR[ RRO
SOS[ RLPKSJUHX RLPMQLSJVHX RLRZRYQXR RLVZVYUXV RG[][[ZZ[
 2122 70D_RFPFOIMNJSGW RQFOJ RRFOLLQIUGW RHH[HYGXH RIKYKXJWK RSLTNVQXS[U
]T RYS[T RTNVPYR]T RGN]N[MZN RLRL\ RLRMSM\ RMSVS RVSV\ RUSVRWSW\ RMWVW R
M[V[
 2126 65D_HFHW RHFIGIW RIGMG RMGMV RLGMFNGNV RINMN RIUMU RUGVFTFTN RUGUN
 RPJ[JYIXJ RNN]N[MZN RWNWZV[ RXNXZW\V[TZ RNR]R[QZR RQTRUSWTWTVSUQT
 2137 81D_NGLFLP RMGMP RMGWG RVGWFYGXI RWGWP RXGXP RMKWK RMOWO RKSIRI\ R
JSJ\ RJSOS RNSORQSPU ROSO\ RPSP\ RJWOW RJ[O[ RVSTRT\ RUSU\ RUSZS RYSZR\S
[U RZSZ\ R[S[\ RUWZW RU[Z[
 2138 77D_KEKL RKELFLL RLFWF RWFWL RVFWEXFXL RLIWI RKLXL RPLPR RQLQR RIO
TOSNRO RGR]R[QZR RXMSQNTJV RXMYNVPQSMUJVGW RLTL\ RLTMUM\ RMUWU RWUW\ RVU
WTXUX\ RMXWX RM[W[
 2141 66D_KEKL RKELFLL RLFWF RWFWL RVFWEXFXL RLIWI RKLXL RHN\NZMYN RQPQ[
 RRPR[ RKPKV RLPLV RKPXP RWPWV RXPXV RLSWS RKVXV RIX[XZWYX RG[][[ZZ[
 2143 75D_HFHW RHFIGIW RIGMG RMGMV RLGMFNGNV RINMN RIUMU RWFXEVEVN RWFWN
 RQH\H[GZH RRK[KZJYK RPN]N\M[N RRPR\ RRPSQS\ RSQZQ RZQZZY[ RYQZP[Q[ZZ\Y[
WZ RSTZT RSWZW
 2146 84D_LELL RLEMFML RMFVF RVFVL RUFVEWFWL RMIVI RLLWL RGO]O[NZO RJOJY
 RKOKY RGZOX RGZH[OX RPOP\ RQOQ\ RKRPR RKUPU RSR\R R[QZTXWUZR\ RZR[Q\R[T
YWWYT[R\ RTSUVWYY[[\][ RUVWXZZ][
 2154 80D_HFHX RHFIGIX RIGMG RMGMX RLGMFNGNX RIOMO RIWMW RVIVGWFUFUI RPI
\I[HZI RRJSMTMTLRJ RXIWN RXIYJWN ROO]O[NZO RSSQRQ\ RRSR\ RRSYS RXSYR[SZU
 RYSY\ RZSZ\ RRWYW RR[Y[
 2160102D_KEKJ RKELFLJ RLFWF RWFWJ RVFWEXFXJ RLHWH RKJXJ RKLYLXKWL RQLQR
 RRLRR RIMHOGPGQHQIOIM RIN[N RZN[M]O[P R[M[P R\N[PZQ RKPNP RUPXP RKRNR R
URXR RITZTYSXT RGW]W[VZW ROWN[ ROWPXN[ RI[XZ RI[K\XZ RWYXZY\Z\Z[YZWY
 2164115D_IFIM RIFJGJM RJGOG ROGOM RNGOFPGPM RJJOJ RIMPM RGPRPQOPP RLPLX
 RMPMY RMTQTPSOT RISIUHYG[ RISJSJUIXG[ RJVKXMZP[\[]Z RKXMYPZ]Z RSG]G\F[G
 RWGVK RWGXHVK RTJTT RTJUKUT RUKZK RZKZT RYKZJ[K[T RUNZN RUQZQ RTT[T RUU
RX RUUVVRX RYU\X]X]WYU
 2169 45D_OGMFMNLTKWIZG\ RNGNNMTLWJZG\ RNGXG RWGXFZGYI RXGXXWZV[ RXYXZW[
 RYGYZX\W\V[TZ RNMXM RMSXS
 2170 43D_RHSGQFQ\ RRGR\ RGL]L[JYL RYL\K RPLMRJVGY RQMOQMTKVGY RSMTPURXV
[Y]X RYV[X RSMTOWSZV]X
 2194 64D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLPMQNSOSORNQLP RTH
RGRRQVPXN[ RSHSRRVPYN[L\ RTHXGZF\G RSHTH\G RSP]P[OZP RXPX\ RYPY\
 2210 66D_MHNGLFL\ RMGM\ RHLQLPKOL RLLKPJRGV RLPJSGV RNPOQPSQSQRPQNP RWH
XGVFV\ RWGW\ RQL]L[KZL RVLUPSUQX RVPTTRWPY RWMXQYTZV\Y]X RWMXPZT\W]X
 2211 78D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLOMPNROROQNPLO RVG
WFUFUO RVGVO ROK]K[JZK RPOZO RZOYRWUTXQZ R[OZQ RYOZN\O[QXUVWSYQZN[ RQPRS
TVVXYZ[[]Z RTVWXYY]Z
 2212 72D_KGLFJFJ[ RKGK[ RGKOKNJMK RJLIPHSGU RJPIRGU RLOMPNROROQNPLO RTG
RMQO RTGUHSLQO RXFYJZL\O]N RXFYI[L]N RVORZ RVOWPRZ ROZZX ROZP[ZX RZV[X\[
][]Z\XZV
 2233 86D_KGLFJFJ\ RKGK\ RGKNKMJLK RJLIPHSGU RJPIRGU RKOLPMRNRNQMPKO ROG
OV ROGPHPV RPHTFUG RPHUG RSISVRYP[N\ RSITITVSYQ[N\ RNVST RNVOWST RWHW\ R
WHXIX\ RXI[I R[I[VZW RZI[H\I\V[XZWXV
 2236 59D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLOMPNROROQNPLO RSF
TGUIVIVHUGSF RPK]K[JZK RUKU[ RVKV[ RQS[SZRYS RO[][[ZZ[
 2241 57D_LHMGKFK\ RLGL\ RGLPLOKNL RKNJQISGV RKQITGV RMPNQOSPSPROQMP RSG
S\ RSGTHT\ RTH[H R[H[\ RZH[G\H\\ RTN[N RTT[T RTZ[Z
 2254 89D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLPMQNSOSORNQLP RWG
XFVFVJ RWGWJ RQJ]J\I[J RUJSO RUJVKSO RQNROSQTQTPSOQN RYNWQTTQV RYNZOVSSU
OW R\RZUWXTZ R\R]SYWVYR[O\ RYX[Z\\]\][\ZYX
 2256 91D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLOMPNROROQNPLO ROF
PGQJRJRIQGOF RTFUGVJWJWIVGTF R\FZK R\F]GZK RTMQW RTMUMRW RPQ]Q\P[Q RYQXT
WVUYS[Q\ RYQZRXVVYT[Q\P\ RTVWWZY\[][]ZZXXWTVRV
 2261 80D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLPMQNSOSORNQLP RQF
QY RQFRGRX RRGYG RYGYO RXGYFZGZO RRKYK RROZO RUOVRWTYW\Z]Y RVRXUZW]Y RNY
XW RNYOZXW R[QXT R[Q\RXT
 2264100D_JGKFIFI\ RJGJ\ RGKMKLJKK RIOHSGU RIRGU RJPKQLSMSMRLQJP RXGYFWF
WNXUYXZZ[[\[]Z\Y RZY[Z\Z RXGXNYUZX[Y\Y]W RZF[H\H\GZF RMK]K[JZK R[NZRYUWY
 R[N\O[RYVWYU[S\ ROMOTNXMZ ROMPMPTOWMZL[ RRMRY RRMSMSY RMRVRUQTR
 2301 92D_RGSFQFQP RRGRP RHI\IZHYI RQIOKLMHO RRJOLKNHO RRITLWNZO\N RRITK
XM\N RMRNQLQL\ RMRM\ RGTQTPSOT RLTIXGZ RMVJXGZ RNVOXPXPWNV RWRXQVQV\ RWR
W\ RQT]T\S[T RVTSXQZ RVVTXQZ RWTXVZX\Y]X RXVZW]X
 2303 85D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RKOLPMRNRNQMPKO RYF
WFVL RXFWI RYFVL RQI]I\H[I RTKTX RTKULUX RUL[L R[L[X RZL[K\L\X RUP[P RUT
[T RTX\X RQORNPNP\ RQOQ\ RQ[][[ZZ[
 2305107D_IGJFHFH\ RIGI\ RFLLLKKJL RHOGSFU RHRFU RIPJQKSLSLRKQIP RMG]G[F
ZG RRGPL RSGQL RQKUK RUKUVTW RTKUJVKVVUXTWRV RNNNT RNNOOOT ROORO RRORS R
QORNSOSS ROSSS RVM]M R\L[QZTYV R[M\L]M\Q[SYVXW RXMXNYR[V\W]V RYR[U]V RM[
][[ZZ[
 2313 87D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLOMPNROROQNPLO RWF
UFTHRK RWFPM RQH]H[GZH RRK[KZJYK RVKVN RWKWN RQN]N[MZN RRPR\ RRPSQS\ RSQ
ZQ RZQZZY[ RYQZP[Q[ZZ\Y[WZ RSTZT RSWZW
 2324 94D_QEPH RQERFPH RNGNQ RNGOHOQ ROHTH RTHTQ RSHTGUHUQ ROLTL ROPTP R
HGIHJJKJKIJHHG RZGVK RZG[HVK RGOMM RGOHPMM RWNYO[Q\Q\PZOWN RRSSRQRQ\ RRS
R\ RGU]U[TZU RPUMXJZ RQVNXJZG[ RRTUXXZ[[]Z RSVVXYY]Z
 2343 95D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RKOLPMRNRNQMPKO RTG
UFSFSN RTGTN RXGYFWFWN RXGXN RPH\H[GZH RQK[KZJYK RON]N\M[N RUNUW RVNVW R
PPP\ RPPQQQ\ RQQZQ RZQZZY[ RYQZP[Q[ZZ\Y[WZ RQTZT ROW\W
 2359101D_JGKFIFI\ RJGJ\ RGLMLLKKL RIOHSGU RIRGU RJPKQLSMSMRLQJP RNG]G[F
ZG RSGSP RTGTP RWGWP RXGXP ROJOP ROJPKPP RPK[K R[K[P RZK[J\K\P ROP\P RQS
ZSYRXS RNV]V[UZV RUVU[T\ RVVV[U]T\R[ RPXN[ RPXQYN[ RYXZY[[\[\Z[YYX
 2361103D_KGLFJFJ\ RKGK\ RGKOKNJMK RJLIPHSGU RJPIRGU RLOMPNROROQNPLO RUG
VFTFTL RUGUL RYGZFXFXL RYGYL RQI]I\H[I RQL]L\K[L RQNQX RQNRORX RRO[O R[O
[X RZO[N\O\X RVLVW RWLWW RRS[S RRW[W RTYQ[O\ RTYUZS[O\ RXYZZ\\]\][[ZXY
 2378124D_JGKFIFI\ RJGJ\ RGLMLLKKL RIOHSGU RIRGU RJPKQLSMSMRLQJP RPHTGXF
ZG RPHZG RTGRKPN RTGUHQMOO ROJ\J[IZJ RWJXLZO\P]O RXLZN]O RRMRR RRMSNSR R
SNXN RXNXR RWNXMYNYR RSQXQ ROSO\ ROSPTP\ RPT[T R[T[ZZ[ RZT[S\T\Z[\Z[XZ R
SVSZ RSVTWTZ RTWWW RWWWZ RVWWVXWXZ RSZXZ
 2379156D_IGJFHFH\ RIGI\ RFLLLKKJL RHOGSFU RHRFU RIPJQKSLSLRKQIP RUGVFTF
TRUWVYX[Z\\\][\Z RUGURVWWYXZZ[[[\Z]X ROFNJ ROFPGNJ RMINLOLOKMI RQINO RQI
RJNO RLOQO RLOMPQO RQMRPSPSOQM RYFXJ RYFZGXJ RWIXLYLYKWI R[IXO R[I\JXO R
VO[O RVOWP[O R[M\P]P]O[M RWPXRYRYQWP ROS]S[RZS ROSOUNYM[ RPSPUOXM[ RPUQV
RXSXSWRVPU RZUWXTZP\ RZU[VWYS[P\
 2412 60D_OFMFLIINGQ RNFMH ROFKLGQ RKK[K RYKZJ\LYM RZJYM R[KYMXN RQKPPOS
NULXJZG\ RRKQPPSOUMXKZG\ RSKTPUSWWYZ[\][ RYY[[ RUSWVZY][
 2429 32D_SHTGRFR[ RSGS[ RMONNLML[ RMNM[ RSP[PYNWP RWPZO RG[][[YY[ RY[\Z

 2430 55D_NGOFMFMX RNGNX RJLKKIKIY RJLJY RNNRNQMPN RGYSW RGYHZSW RUGVFTF
TZU[\[]Z\X R[Z\Z\Y RUGUYVZZZ\X]U R[KUQ R[K\LUQ
 2435 95D_HKHY RHKIKIY RKFKY RKFLFLX RLNNNMMLN RFYOX RFYGZOX ROFOYPZSZSW
 ROFPFPXQYRYSX RRKPN RRKSLPN RWFVITNSP RWFXGWISP R[FYK R[F\GYK RULU\ RVL
V\ RUL]L\K[L RYLY[ RZLZ[ RVQ]Q\P[Q RVV]V\U[V RV[][\Z[[
 2436114D_MFNELELS RMFMS RGGRGQFPG RHIHM RHIIJIM RIJPJ RPJPM ROJPIQJQM R
HMQM RKMIPGR RLNGR RNOOPPRQRQQPPNO RUFTJSL RUFVGUISL RUI]I\H[I RZIYLXNVQ
 RZI[JZLXOVQTR RUIVLWNYP\R]Q RWNZP]Q RHU\UZTYU RRUR[ RSUS[ RSXYXXWWX RLX
L[ RLXMXM[ RG[][[ZZ[
 2438 62D_GGRGQFPG RLGKLJOIQ RMGLLKNIQGS RLLPL RPLOQNTLWJYG[ ROLPKQLPQOT
NVLXIZG[ RJPLRMTNTNSMRJP RUIUU RUIVIVU R[F[YZZ R[F\F\Y[[ZZXY
 2439 72D_GG]G[EYG RYG\F RLGKLJOIQ RMGLLKNIQGS RLLPL RPLOQNTLWJYG[ ROLPK
QLPQOTNVLXIZG[ RJPLRMTNTNSMRJP RTGTZU[\[]Z\X R[Z\Z\Y RUGUYVZZZ\X]U RZMUQ
 RZM[NUQ
 2466 57D_LGJFIY RKGJY RKGXG RWGXFZGYI RXGWXVZU[ RWYWZV[ RYGXZW\V\U[SZ R
PIQJRLSLSKRJPI RGO]O[NZO ROQPRQTRTRSQROQ RJW]W[VZW
 2467 61D_NFLFJJGN RNFKJGN RLH]H[GZH RMLKKJY RLLKY RLLYL RXLYK[LYO RYLXX
WZV[ RXYXZW[ RZLYZX\W\V[TZ RRLQX RSLRX RGR]R\Q[R RKX]X\W[X
 2470 54D_KHLGJFJY RKGKY RKOPOONNO RGZQW RIZLY RGZI[QW RTHUGSFSZT[\[]Z\X
 R[Z\Z\Y RTGTYUZZZ\X]U RTPWNYL[M RXNYM RTP[M
 2473 37D_GINHTGXFZG RGIZG RPHPZQ[\[]Z\X R[Z\Z\Y RQHQYRZZZ\X]U RHN[LYKXL
 RGT]R[QZR
 2478 51D_LHJGJY RKHKX RLHRGWFYG RKHLHYG RGYSV RGYIZSV RRGRPSUTXW[Z\\\][
\Z RSGSPTUUXWZZ[[[\Z]W RKO\OZMXO RXO[N
 2480 69D_OFMFLHJKGO ROFKKGO RLI\IZHYI RLLZLXKWL RJOXO RWOXNZOYQ RXOXTYX
[[\\]\][\Y R[Z\[ RYOYTZX[Y\Y]V RTQOVKYG[ RTQURRUNXJZG[ RIRLTPWSZTZTYRWMT
IR
 2482 66D_RISGQFQWPZO[MZ RQYQZP[ RRGRZQ\P\O[ RHLML RLLMKOLNN RMLMMLQKTJV
GZ RNLNNMRLTJWGZ RSGSITNUQVSXV[Y]X RYV[X RSITMVQXTZV]X RZKVP RZK[LVP
 2503 75D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RRGPFPTOXNZ RQGQTPWNZM[ RQGYG RXGYF[GZI RYGYO RZGZO RQNYN RUNUQVUWWYY\[
]Z RUQVTWVYX]Z
 2507 78D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RRFPKOM RRFSGRIOM RRI\I[HZI RPLZLYKXL ROOXO RWOXNZOYQ RXOXTYX[[\\]\][\Y
 R[Z\[ RYOYTZX[Y\Y]V
 2509 77D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RUGVFTFTQSURWPYM[ RUGUQTUSWQYM[ ROJYJ RYJYQ RXJYIZJZQ RNQ]Q\P[Q RUQVUWW
YY\[]Z RUQVTWVYX]Z
 2529102D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RVGWFUFUP RVGVP RRJPIPSOWNYL\ RQJQSPWNZL\ RQJ[J RZJ[I]K[L R[J[L R\J[LZN
 RQPYP RYPXSVVSYP[ RZPYR RXPYO[PZRXUUXRZN\ RSPTTVXY[[\][ RTTVWXYZZ][
 2530 75D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RMH]H[FYH\G RZHZXYZX[ RZYZZY[ R[H[ZZ\Y\X[VZ ROLOU ROLPMPU RPMUM RUMUU R
TMULVMVU RPTUT
 2534 67D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RVGWFUFUZ RVGVZ RQLOKO[ RPLP[ RPL[L RZL[K]L\N R[L[[ R\L\[ RPS[S RPZ[Z
 2535 72D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RUHVGTFTR RUGUR ROL[LZKYL RNR]R[QZR RTSQZ RTSUTQZ RMZYY RMZO[YY RXWYX[[
\[\Z[YXW
 2553 86D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RRFPJNM RRFSGNM RQI]I[HZI RRMPLOX RQMPX RQMZM RYMZL\MZP RZMYZX[ R[MZZY\
X[VZ RUMTW RVMUW RNR]R\Q[R RPW]W\V[W
 2565 91D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 ROGZG RYGZF\HYI RZGYI R[GYIVK RRITKUMVLTJPH RUMU\ RVMV\ RQMOLO\ RPMP\ R
PM[M RZM[L]M\O R[M[ZZ[ R\M\Z[\Z[XZ RPQ[Q RPU[U
 2573 84D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RNG]G[FZG RSGSNRQPS RTGTNSQPS RWGWQXR[R RXGXPYQ[Q RQLOKO[ RPLP[ RPL[L R
ZL[K]L\N R[L[[ R\L\[ RPV[V RPZ[Z
 2576 96D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RUIUGVFTFTI RNI]I[HZI RTJRO RTJUKRO ROO[N ROOPP[N RYL[N\P]P]O\NYL RPRPV
OYM[ RPRQRQVPYM[ RTRT[ RTRURU[ RXRXZY[][]W RXRYRYYZZ\Z]Y
 2599107D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RVGWFUFUI RVGVI ROI]I\H[I RQJOOMS RQJRKQMMS ROPO[ RPNP[ RWIVLTPRS RWIXJ
WMUPRS RVN\N R[MZQXUUY R[M\N[QZSXVUYR[ RVPWQXSYSYRXQVP RTRUUWXZZ\[]Z RUU
WWZY]Z
 2629103D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RQFQP RQFRGRP RRGYG RYGYP RXGYFZGZP RUKUP RUKVLVP RVLYL ROOO\ ROOPPP\ R
PP[P R[P[ZZ[ RZP[O\P\Z[\Z[XZ RSSSX RSSTTTX RTTWT RWTWX RVTWSXTXX RSXXX
 2631 91D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RRGPFPP RQGQP RQGZG RYGZF\G[I RZGZP R[G[P RQKZK RQOZO RSRS[ RSRTRT[ RWR
W[ RWRXRX[ ROUPYQYQXOU R[UYY R[U\VYY RN[][[ZZ[
 2632 90D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 ROFOV ROFPGPV RPGSG RSGSV RRGSFTGTV RPLSL RPQSQ ROVTV ROWM[ ROWPXM[ RSW
T[U[UZSW RWHWU RWHXHXU R[F[YZZ R[F\F\Y[[ZZXY
 2634 92D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RRGPFPO RQGQO RQGZG RYGZF\G[I RZGZO R[G[O RQKZK RPO[O RORO[ RORPSP[ RPS
[S R[S[[ RZS[R\S\[ RSSS[ RTST[ RWSW[ RXSX[ RN[][
 2637114D_GFHGIIJIJHIGGF RFLGMHOIOINHMFL RLNHVFVHWHYGZH[I[JZIYIVLN RHZIZ
 RMJMTLYK[ RMJNKNTMXK[ RNK]K[JZK RXGYFWFWOXUYXZZ\\]\]X RXGXOYUZX[Z][ R[F
\H]H]G[F RPOUOTNSO RPRPX RPRQSQX RQSTS RTSTW RSSTRUSUW RQWUW R\N[RZTXWVY
S[ R\N]O\R[TYWWYS[P\
 2655 99D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RUHUGVFTFTH ROH[HZGYH RQHRLSLSKQH RWHVM RWHXIVM RNM]M[LZM ROOOW ROOPPPW
 RPPYP RYPYW RXPYOZPZW RPSYS RPVYV RTPTZU[\[]Z\Y RUPUYVZ[Z\Y]W
 2656101D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RNENRMWLY RNEOFORNVLY ROF]F[EZF RVFUJ RWFUJ RRIRS RRISJSS RSJZJ RZJZS R
YJZI[J[S RSNZN RSRZR RVRVYUZ RWRWYV[UZSY RRUOZ RRUSVOZ RZU\Y]Y]XZU
 2659116D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RVHVGWFUFUH RPGOINJNKOKPIPG RPH[H RZH[G]I[J R[H[J R\H[JZK RRLOO RRLSMOO
 RXLYMZO[O[NZMXL RUOSRQT RUOVPTRQTOU RVPYS\U]T RWQZS]T RQUQ\ RQURVR\ RRV
YV RYVY\ RXVYUZVZ\ RR[Y[
 2702112D_HFIGJIKIKHJGHF RGLHMIOJOJNIMGL RMNIVGVIWIYHZI[J[KZJYJVMN RIZJZ
 RRGSFQFQM RRGRM RNJUJTISJ RNLNS RNLOMOS ROMTM RTMTS RSMTLUMUS ROPTP RNS
US RQSQ[ RRSR[ RNVUVTUSV RWFWUVYU[ RWFXGXUWXU[ RXG[G R[G[YZZ RZG[F\G\Y[[
ZZYY RXM[M RXS[S
 2743 55D_QFQLPQNULXJZG\ RRGRK RQFSGRNQROVLYI[G\ RSGSKTQUTVVXY[\][ RYY[[
 RSKTPVTXWZY][ RLLKOIQIRJRKQLNLL RZLUQ RZL[MUQ
 2745 61D_MGNFLFLRKVIYG[ RMGMRLVJYG[ RILHNGOGPHPINIK RPJMN RPJQKMN RMTNU
PXQXQWPVMT RRH]H[FYH RYH\G RWHWWVYUZ RWXWYVZ RXHXYW[V[UZSY
 2750 70D_LGMFKFKSJWIY RLGLSKVIYG[ RILHNGOGPHPINIL ROKMN ROKPLMN RLUMVNX
OXOWNVLU RQG]G[FZG RTLRKRSQXPZ RSLSSRWPZN\ RSLZL RYLZK\L[N RZLZS R[L[S R
SRZR
 2770107D_KFJJIMGQ RKFLGKJINGQ RKJPJ RPJOMMQJU ROJPIQJPMOOMRJUGW RKLMNNN
NMKL RIOJPKRLRLQKPIO RVGWFUFUMTQSSQUOV RVGVNUQTSRUOV RXHYJZJZIXH RPM]M[L
ZM RVNWQYT\V]U RWQYS]U RIXHZG[G\H\IZIX RMXN\O\O[MX RSXT\U\U[SX RXXZZ[\\\
\[ZYXX
 2772 98D_KGLFJFJSIXHZ RKGKSJWHZG[ RHLGNFOFPGPHNHL RNJKN RNJOKKN RLUMVNX
OXOWNVLU RVGWFUFUN RVGVN RPI\I[HZI RON]N\M[N RQKQS RQKRKRS RYKYS RYKZKZS
 ROS]S\R[S RSSSURXQZ RTSTUSXQZO[ RWSWZX[\[]Z\Y RXSXYYZ[Z\Y]W
 2773 77D_LFJFIIGM RLFJIGM RLHJGJV RKHKV RKH]H\G[H ROHOV RPHPV RTHTV RUH
UV RYHYV RZHZV RGO]O\N[O RGV]V\U[V RIXHZG[G\H\IZIX RMXN\O\O[MX RSXT\U\U[
SX RXXZZ[\\\\[ZYXX
 2797122D_MGNFLFLL RMGML RHIQIPHOI RGLRLQKPL RJLJMIOGQ RKLKMJOGQ RNLNOOP
RPRN ROLOOQORN RLQLV RLQMQMV RHSQSPROS RGVQV RGVHWQV RVGWFUFUQTTRV RVGVQ
UTRV RRIYI RYIYUZV]V]T]R RXIYHZIZU\U]T RTOVQWSXRVPTO RIXHZG[G\H\IZIX RMX
N\O\O[MX RSXT\U\U[SX RXXZZ[\\\\[ZYXX
 2807130D_KGLFJFJSIXHZ RKGKSJWHZG[ RHLGNFOFPGPHNHL RMJKM RMJNKKM RKVLYMY
MXKV RVGWFUFUQ RVGVQ RPGQHRJSJSIRHPG RZGXJ RZG[HXJ ROK]K\J[K RTKRMOO RUL
OO RVKYN[O\N RWLYM\N RPQOTNV RPQQRNV RPTTT RSSRVQXO[ RRTSSTTSVQYN\ ROVPX
QXQWOV RYRY\ RYRZRZ\ RTT]T\S[T RVTVX RWTWX RRX]X\W[X
 2808128D_KGLFJFJSIXHZ RKGKSJWHZG[ RHLGNFOFPGPHNHL RMJKM RMJNKKM RKVLYMY
MXKV RQFPKON RQFRGQJNP RQIUI RTHSMQS RSITHUISOQSOV RQKRMSMSLQK RONPQQQQP
ON RXGYFWFWNVRUTSV RXGXNWRVTSV RZH[J\J\IZH RTM]M[LZM RXNYRZT\V]U RYR[T]U
 RPXO[O\P\PX RSXS\T\T[SX RVXW\X\X[VX RYX[\\\\[YX
 2829122D_JGRFXEZF RJGZF RKHLIMKNKNJMIKH RPHQKRKRJPH RVGUK RVGWHUK RIJHL
GMGNHNILIJ RIK[K RZK[J]L[M R[K[M R\K[MZN RMMMQNRVRWQVP RMMNMNPOQUQVPVN R
PMROSOSNPM RKNIPIQJQKN RYNZQ[Q[PYN RNSJWGY RNSOTLVGY RMUXU RWTUVQYM[ RWT
XUTXPZM[I\ RMTOWPXSZV[[\][ RPXRYVZ][
 2832 64D_NGLIHL RNGOHHL RUGXI[L\L\KZIXHUG RNMJP RNMKQJP RNMOQQTTWWY[[]Z
 RNMOPQSSUVWZY]Z RVNVMXNWO RVNUQSTPWMYKZH[ RWNVP RWOVQTTQWNYLZH[
 2839 62D_LGMFKFK[ RLGL[ RGIHLILIKGI RGSKQ RGSHTKQ RUGVFTFTMSRRUQWOZ RUG
UMTRSUQXOZM[ RXFZH[H[GXF RNL]L[KZL RUMVQWTXVZY\[]Z RVQXUZX]Z
 2842 43D_KHLGJFJTIYH[ RKGKTJXH[G\ RSHTGRFRL RSGSL RKL]L[JYL RYL\K RKRTR
 RSRTQVRUT RTRT\ RURU\
 2848 44D_IG\GZEXG[F RTGTWSYRZ RTXTYSZ RUGUYT[S[RZPY RMGMO RNGNO RMO[OYM
WOZN RSOQRNUKW RTPPTMVIX
 2852 34D_RHSGQFQ] RRGR] RKGJJHOGQ RKGLHJLGQ RJLZLXJVL RVLYK RGS]S[QYS R
YS\R
 2857 74D_LGMFKFK[ RLGL[ RHIGQ RHIIJGQ RHLOLNKML RGUNQ RGUHVNQ RSFPMOO R
SFTGSIOO RQL[L R[L[TZYYZ RZL[K\L\T[YZ[YZWY RTLSORQPT RULTORRPT RXLWQUUSX
 RYLXQVUSXPZ
 2860 68D_MGNFLFL\ RMGM\ RIHGP RIHJIGP RILQLPKOL RGTQQ RGTHUQQ RWGXFVFVO
 RWGWO RRJ\J[IZJ RQO]O[NZO RXOXZW[ RYOYZX\W[UZ RQS]S[RZS RRUSVTXUXUWTVRU
 2868 54D_SGQFQLPQNULXJZG\ RRGRK RSGRNQROVLYI[G\ RVGWHXJYJYIXHVG RGM]M[K
YM RYM\L RSMTQUTVVXY[\][ RYY[[ RSMTPVTXWZY][
 2922 24D_HH\HZFXH[G RQHQ[ RRHR[ RIQ[QYOWQZP RG[][[YY[\Z
 2923 38D_HH\HZFXH RXH[G RQHQ[ RRHR[ RIQ[QYOWQ RWQZP RG[][[YY[ RY[\Z RUT
VUWWXWXVWUUT
 2937 59D_GGPGOFNG RKGKW RLGLV RHNONNMMN RGWPV RGWIXPV RWGXFVEVO RWFWO R
RI\I[HZI RQO]O[NZO RWRXQVPV[ RWQW[ RRU\U[TZU RQ[][[ZZ[
 2941 80D_GGPGOFNG RKGKW RLGLV RHNONNMMN RGWPV RGWHXPV RWGXFVFVZU[ RWGWZ
V\U[SZ RZF[H\H\GZF RPK]K\J[K RQNROSQTQTPSOQN RWKXQYUZW\Z]Y RXQYT[W]Y RPV
VT RPVQWVT R[NYR R[N\OYR
 2942 63D_GGPGOFNG RKGKW RLGLV RHNONNMMN RGWPV RGWIXPV RVGV[ RWGW[ RQFQR
 RQFRGRR RRG[G R[G[R RZG[F\G\R RRL[L RRQ[Q RQV\V[UZV RP[][[ZZ[
 2943 77D_GGPGOFNG RKGKV RLGLU RHNONNMMN RGVPU RGVIWPU RTGRFRS RSGSS RSG
ZG RYGZF\G[I RZGZS R[G[S RSKZK RSOZO RRS[S RTSSVQYN[ RUSTVRYN[ RWSWZX[\[
]Z\Y RXSXYYZ[Z\Y]W
 2973 58D_MIKHKPJUIXG[ RLILPKUJXG[ RMISHWGYFZG RLIMIUHZG RWHWLXRYVZX\[]Z
 RXRYU[X]Z RQIQX RRIRX RLYUX RLYMZUX RTUUWVZWZWYVWTU
 2977 52D_GH]H[FYH RYH\G RMHJZ RNHKZ RMMVM RUMVLXMWO RVMVZW[\[]Z\Y RWMWY
XZ[Z\Y]V RNQPSQURURTQSNQLP RGZTY RGZH[TY
 2988 30D_MGNFLFL\ RMGM\ RWGXFVFV\ RWGW\ RGL]L[JYL RYL\K RMSVS RM[V[
 2991 44D_SHTGRFR[ RSHS[ RLHKLJOIQGU RLHMILLJPGU RLL[LYJWL RWLZK RKSZSXQ
VS RVSYR RG[][[YY[ RY[\Z
 2993 48D_LGJFJTIYH[ RKGKTJXIZG\ RKGZG RYGZF\G[I RZGZXYZX[ RZYZZY[ R[G[Z
Z\Y\X[VZ RRGR[ RSGS[ RKMZM RKSZS
 2994 33D_QIQY RRIRY RKIIHI[ RJIJ[ RJIYI RXIYH[IZK RYIY[ RZIZ[ RJQYQ RJY
YY
 2996 74D_RGRO RSGSO RMGKFKP RLGLP RLGYG RXGYF[GZI RYGYP RZGZP RLKYK RLO
YO RSRTQRPRQQUOXMZK[H\ RSRRUPXNZL[H\ RGT[T RZT[S]T[V R[TZXYZX[ RZYZZY[ R
\T[ZZ\Y\X[VZ
 2998 76D_QGQO RRGRO RLGJFJP RKGKP RKGXG RWGXFZGYI RXGXP RYGYP RKKXK RKO
XO RQOORKUGW RQORPOSLUJVGW RRPVTYV[W]V RRPVSZU]V RNSNVMYK[I\ RNSOSOVNYL[
I\ RTST\ RTSUSU\
SHAR_EOF
if test 27782 -ne "`wc -c 'hersh.or2'`"
then
	echo shar: error transmitting "'hersh.or2'" '(should have been 27782 characters)'
fi
#	End of shell archive
exit 0

