#!/bin/sh
# This is a shell archive, meaning:
# 1. Remove everything above the #!/bin/sh line.
# 2. Save the resulting text in a file.
# 3. Execute the file with /bin/sh (not csh) to create the files:
#	hersh.oc3
#	hersh.oc4
# This archive created: Tue Mar 25 22:19:03 1986
export PATH; PATH=/bin:$PATH
echo shar: extracting "'hersh.oc3'" '(28258 characters)'
if test -f 'hersh.oc3'
then
	echo shar: over-writing existing file "'hersh.oc3'"
fi
cat << \SHAR_EOF > 'hersh.oc3'
 2501 20H\RFJ[ RRIK[J[ RRIY[Z[ RRFZ[ RMUWU RLVXV
 2502 44H\LFL[ RMGMZ RLFTFWGXHYJYMXOWPTQ RMGTGWHXJXMWOTP RMPTPWQXRYTYWXY
WZT[L[ RMQTQWRXTXWWYTZMZ
 2503 38H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZV RZKYKXIWHUGQGOHMKLNLSMVOY
QZUZWYXXYVZV
 2504 32H]LFL[ RMGMZ RLFSFVGXIYKZNZSYVXXVZS[L[ RMGSGVHWIXKYNYSXVWXVYSZMZ

 2505 27I\MFM[ RNGNZ RMFYF RNGYGYF RNPTPTQ RNQTQ RNZYZY[ RM[Y[
 2506 21I[MFM[ RNGN[M[ RMFYF RNGYGYF RNPTPTQ RNQTQ
 2507 44H]ZKYIWGUFQFOGMILKKNKSLVMXOZQ[U[WZYXZVZRUR RZKYKXIWHUGQGOHNIMKLN
LSMVNXOYQZUZWYXXYVYSUSUR
 2508 22G]KFK[ RKFLFL[K[ RYFXFX[Y[ RYFY[ RLPXP RLQXQ
 2509  8NWRFR[S[ RRFSFS[
 2510 20J[VFVVUYSZQZOYNVMV RVFWFWVVYUZS[Q[OZNYMV
 2511 22H]LFL[M[ RLFMFM[ RZFYFMR RZFMS RPOY[Z[ RQOZ[
 2512 14IZMFM[ RMFNFNZ RNZYZY[ RM[Y[
 2513 26F^JFJ[ RKKK[J[ RKKR[ RJFRX RZFRX RYKR[ RYKY[Z[ RZFZ[
 2514 20G]KFK[ RLIL[K[ RLIY[ RKFXX RXFXX RXFYFY[
 2515 40G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZ
VYXVYSYNXKVHSGQG
 2516 27H\LFL[ RMGM[L[ RLFUFWGXHYJYMXOWPUQMQ RMGUGWHXJXMWOUPMP
 2517 48G]PFNGLIKKJNJSKVLXNZP[T[VZXXYVZSZNYKXIVGTFPF RQGNHLKKNKSLVNYQZSZ
VYXVYSYNXKVHSGQG RSXX]Y] RSXTXY]
 2518 34H\LFL[ RMGM[L[ RLFTFWGXHYJYMXOWPTQMQ RMGTGWHXJXMWOTPMP RRQX[Y[ R
SQY[
 2519 43H\YIWGTFPFMGKIKKLMMNOOTQVRWSXUXXWYTZPZNYMXKX RYIWIVHTGPGMHLILKMM
ONTPVQXSYUYXWZT[P[MZKX
 2520 15J[RGR[ RSGS[R[ RLFYFYG RLFLGYG
 2521 24G]KFKULXNZQ[S[VZXXYUYF RKFLFLUMXNYQZSZVYWXXUXFYF
 2522 14H\JFR[ RJFKFRX RZFYFRX RZFR[
 2523 26E_GFM[ RGFHFMX RRFMX RRIM[ RRIW[ RRFWX R]F\FWX R]FW[
 2524 16H\KFX[Y[ RKFLFY[ RYFXFK[ RYFL[K[
 2525 17I\KFRPR[S[ RKFLFSP RZFYFRP RZFSPS[
 2526 20H\XFK[ RYFL[ RKFYF RKFKGXG RLZYZY[ RK[Y[
 2551 38E\XFVHTKQPOSLWIZG[E[DZDXEWFXEY RXFWJUTT[ RXFU[ RT[TYSVRTPRNQLQKR
KTLWOZR[V[XZ
 2552 70F^UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMH
OGRFXFZG[I[KZMXNTORO RXFYGZIZKYMXN RTOWPXQYSYVXYWZU[S[RZRXSU RTOVPWQXSXV
WYU[
 2553 41H]KHJJJLKNNOQOUNWMYKZIZGYFWFTGQJOMMQLULXMZP[R[UZWXXVXTWRURSSRU R
WFUGRJPMNQMUMXNZP[
 2554 43F]UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWJWLXNZP[S[UZWXYTZOZLYI
WGUFPFMGKIJKJMKNMNNMOK
 2555 49I\WIVJVLWMYMZKZIYGWFTFRGQHPJPLQNSO RTFRHQJQMSO RSOQONPLRKTKWLYMZ
O[R[UZWXXVXTWRURSSRU RQOOPMRLTLXMZ
 2556 46G\WHVJTORUQWOZM[ RQLPNNOLOKMKKLINGQF[FXGWHVKTSSVRXPZM[K[IZHYHXIW
JXIY RSFWGXG ROSPRRQVQXPZMXT
 2557 53G]JIIKIMJOLPOPROTNWKXHXGWFVFTGRIQKPNPQQSSTUTWSYQZO RWFUGSIRKQNQR
ST RZOYSWWUYSZO[L[JZIXIWJVKWJX RYSWVUXRZO[
 2558 55F^LLKKKILGOFRFOQMWLYKZI[G[FZFXGWHXGY RRFOONRLWKYI[ RJTKSMRVOXN[L
]J^H^G]F\FZGXJWLURTVTYV[W[YZ[X R\FZHXLVRUVUYV[
 2559 33IYWHUKSPQUPWNZL[ RYLWNTOQOONNLNJOHQGUFYFWHVJTPRVQXOZL[J[IZIXJWKX
JY
 2560 34IZYFWHUKSPPYN] RYMWOTPQPOONMNKOIQGUFYFWIVKSTQXPZN]M^K_J^J\KZMXOW
RVVU
 2561 59F^LLKKKIMGPFRFOQMWLYKZI[G[FZFXGWHXGY RRFOONRLWKYI[ RZGWKUMSNPO R
]G\H]I^H^G]F\FZGWLVMTNPO RPOSPTRUYV[ RPORPSRTYV[W[YZ[X
 2562 40I[MILKLMMOOPRPUOWNZK[H[GZFYFWGVHTKPUOWMZK[ RVHTLRSQVPXNZK[I[HZHX
IWKWMXPZR[U[WZYX
 2563 49D`RFNOKUIXGZE[C[BZBXCWDXCY RRFPMOQNVNZP[ RRFQJPOOVOZP[ R[FWORXP[
 R[FYMXQWVWZY[Z[\Z^X R[FZJYOXVXZY[
 2564 38G^RFQJOPMULWJZH[F[EZEXFWGXFY RRFRKSVT[ RRFSKTVT[ R`G_H`IaHaG`F^F
\GZJYLWQUWT[
 2565 34H]SFQGOIMLLNKRKVLYMZO[Q[TZVXXUYSZOZKYHXGWGUHSJQNPSPV RQGOJMNLRLV
MYO[
 2566 53F]UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMH
OGRFVFYGZH[J[MZOYPVQTQRP RVFXGYHZJZMYOXPVQ
 2567 43H]UJULTNSOQPOPNNNLOIQGTFWFYGZIZMYPWSSWPYNZK[I[HZHXIWKWMXPZS[V[XZ
ZX RWFXGYIYMXPVSSVOYK[
 2568 65F^UGTHSJQOOUNWLZJ[ RTHSKQSPVOXMZJ[H[GZGXHWIXHY ROLNNMOKOJNJLKJMH
OGRFWFZG[I[KZMYNVORO RWFYGZIZKYMXNVO RROUPVRWYX[ RROTPURVYX[Y[[Z]X
 2569 36H\NIMKMMNOPPSPVOXN[K\H\G[FZFXGWHVJUMSTRWPZN[ RVJUNTUSXQZN[K[IZHX
HWIVJWIX
 2570 38I[YHXJVOTUSWQZO[ RSLRNPONOMMMKNIPGSF\FZGYHXKVSUVTXRZO[M[KZJYJXKW
LXKY RUFYGZG
 2571 39G]HJJGLFMFOHOKNNKVKYL[ RMFNHNKKSJVJYL[N[PZSWUTVR RZFVRUVUYW[X[ZZ
\X R[FWRVVVYW[
 2572 36G\HJJGLFMFOHOKNOLVLYM[ RMFNHNKLRKVKYM[N[QZTWVTXPYMZIZGYFXFWGVIVL
WNYP[Q]Q
 2573 41F]ILHLGKGIHGJFNFMHLLKUJ[ RLLLUK[ RVFTHRLOUMYK[ RVFUHTLSUR[ RTLTU
S[ R`F^G\IZLWUUYS[
 2574 52H\PKOLMLLKLIMGOFQFSGTITLSPQUOXMZJ[H[GZGXHWIXHY RQFRGSISLRPPUNXLZ
J[ R]G\H]I^H^G]F[FYGWIULSPRURXSZT[U[WZYX
 2575 42G]JJLGNFOFQGQIOOORPT ROFPGPINONRPTRTUSWQYNZL R\FZLWTUX R]F[LYQWU
UXSZP[L[JZIXIWJVKWJX
 2576 44G\ZHYJWOVRUTSWQYOZL[ RSLRNPONOMMMKNIPGSF]F[GZHYKXOVUTXQZL[H[GZGX
HWJWLXOZQ[T[WZYX RVFZG[G
 2601 36H\WMW[X[ RWMXMX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMX
NYPZSZWX
 2602 36H\LFL[M[ RLFMFM[ RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWX
VYTZQZMX
 2603 32I[XPVNTMQMONMPLSLUMXOZQ[T[VZXX RXPWQVOTNQNOONPMSMUNXOYQZTZVYWWXX

 2604 36H\WFW[X[ RWFXFX[ RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMX
NYPZSZWX
 2605 36I[MTXTXQWOVNTMQMONMPLSLUMXOZQ[T[VZXX RMSWSWQVOTNQNOONPMSMUNXOYQZ
TZVYWWXX
 2606 24LZWFUFSGRJR[S[ RWFWGUGSH RTGSJS[ ROMVMVN ROMONVN
 2607 48H\XMWMW\V_U`SaQaO`N_L_ RXMX\W_UaSbPbNaL_ RWPUNSMPMNNLPKSKULXNZP[
S[UZWX RWPSNPNNOMPLSLUMXNYPZSZWX
 2608 25H\LFL[M[ RLFMFM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[
 2609 24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMR[S[ RRMSMS[
 2610 24NWRFQGQHRISITHTGSFRF RRGRHSHSGRG RRMRbSb RRMSMSb
 2611 22H[LFL[M[ RLFMFM[ RXMWMMW RXMMX RPTV[X[ RQSX[
 2612  8NWRFR[S[ RRFSFS[
 2613 42CbGMG[H[ RGMHMH[ RHQKNMMPMRNSQS[ RHQKOMNONQORQR[S[ RSQVNXM[M]N^Q
^[ RSQVOXNZN\O]Q][^[
 2614 25H\LML[M[ RLMMMM[ RMQPNRMUMWNXQX[ RMQPORNTNVOWQW[X[
 2615 36I\QMONMPLSLUMXOZQ[T[VZXXYUYSXPVNTMQM RQNOONPMSMUNXOYQZTZVYWXXUXS
WPVOTNQN
 2616 36H\LMLbMb RLMMMMb RMPONQMTMVNXPYSYUXXVZT[Q[OZMX RMPQNTNVOWPXSXUWX
VYTZQZMX
 2617 36H\WMWbXb RWMXMXb RWPUNSMPMNNLPKSKULXNZP[S[UZWX RWPSNPNNOMPLSLUMX
NYPZSZWX
 2618 21KYOMO[P[ ROMPMP[ RPSQPSNUMXM RPSQQSOUNXNXM
 2619 50J[XPWNTMQMNNMPNRPSUUWV RVUWWWXVZ RWYTZQZNY ROZNXMX RXPWPVN RWOTN
QNNO RONNPOR RNQPRUTWUXWXXWZT[Q[NZMX
 2620 16MXRFR[S[ RRFSFS[ ROMVMVN ROMONVN
 2621 25H\LMLWMZO[R[TZWW RLMMMMWNYPZRZTYWW RWMW[X[ RWMXMX[
 2622 14JZLMR[ RLMMMRY RXMWMRY RXMR[
 2623 26F^IMN[ RIMJMNX RRMNX RRPN[ RRPV[ RRMVX R[MZMVX R[MV[
 2624 16I[LMW[X[ RLMMMX[ RXMWML[ RXMM[L[
 2625 17JZLMR[ RLMMMRY RXMWMRYNb RXMR[ObNb
 2626 20I[VNL[ RXMNZ RLMXM RLMLNVN RNZXZX[ RL[X[
 2651 33K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RVRTXTZV[XZYY[V RWRUXUZ
V[
 2652 23LZLVNSPO RSFMXMZO[P[RZTXUUURVVWWXWZV RTFNXNZO[
 2653 22LXTSSTTTTSSRQROSNTMVMXNZP[S[VYXV RQROTNVNYP[
 2654 33K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RZFTXTZV[XZYY[V R[FUXUZ
V[
 2655 23LXOYQXRWSUSSRRQROSNTMVMXNZP[S[VYXV RQROTNVNYP[
 2656 27OXRRUOWLXIXGWFUGTIKdKfLgNfOcPZQ[S[UZVYXV RTISNRRO[M`Kd
 2657 38K[UUTSRRPRNSMTLVLXMZO[Q[SZTX RPRNTMVMYO[ RVRPd RWRT[R`PdOfMgLfLd
MaO_R]V[YY[V
 2658 30L[LVNSPO RSFL[ RTFM[ ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V
 2659 19NVSLRMSNTMSL RQROXOZQ[SZTYVV RRRPXPZQ[
 2660 24NVSLRMSNTMSL RQRKd RRRO[M`KdJfHgGfGdHaJ_M]Q[TYVV
 2661 31LZLVNSPO RSFL[ RTFM[ RURUSVSURTRRTOU ROURVSZT[ ROUQVRZT[U[XYZV
 2662 17NVNVPSRO RUFOXOZQ[SZTYVV RVFPXPZQ[
 2663 45E^EVGSIRKSKUI[ RIRJSJUH[ RKUMSORPRRSRUP[ RPRQSQUO[ RRUTSVRWRYSYU
XXXZY[ RWRXSXUWXWZY[[Z\Y^V
 2664 32I[IVKSMROSOUM[ RMRNSNUL[ ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V

 2665 29KYRRPRNSMTLVLXMZO[Q[SZTYUWUUTSRRQSQURWTXVXXWYV RPRNTMVMYO[
 2666 30L[LVNSPO RQLHg RRLIg ROUQSSRTRVSVUUXUZV[ RTRUSUUTXTZV[XZYY[V
 2667 35K[UUTSRRPRNSMTLVLXMZO[Q[SZ RPRNTMVMYO[ RVRPdPfQgSfTcT[V[YY[V RWR
T[R`Pd
 2668 24LZLVNSPRRSRUP[ RPRQSQUO[ RRUTSVRWRVU RVRVUWWXWZV
 2669 22NZNVPSQQQSTUUWUYTZR[ RQSSUTWTYR[ RNZP[U[XYZV
 2670 20NVNVPSRO RUFOXOZQ[SZTYVV RVFPXPZQ[ RPNVN
 2671 27K[NRLXLZN[O[QZSXUU RORMXMZN[ RVRTXTZV[XZYY[V RWRUXUZV[
 2672 23KZNRMTLWLZN[O[RZTXUUUR RORNTMWMZN[ RURVVWWXWZV
 2673 36H]LRJTIWIZK[L[NZPX RMRKTJWJZK[ RRRPXPZR[S[UZWXXUXR RSRQXQZR[ RXR
YVZW[W]V
 2674 42JZJVLSNRPRQSQUPXOZM[L[KZKYLYKZ RWSVTWTWSVRURSSRUQXQZR[U[XYZV RQS
RU RSSQU RPXQZ RQXOZ
 2675 32K[NRLXLZN[O[QZSXUU RORMXMZN[ RVRPd RWRT[R`PdOfMgLfLdMaO_R]V[YY[V

 2676 38LYLVNSPRRRTSTVSXPZN[ RRRSSSVRXPZ RN[P\Q^QaPdNfLgKfKdLaO^R\VYYV R
N[O\P^PaOdNf
 2697  1RR
 2698  1NV
 2699  1JZ
 2700 42H\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF ROGMJLOLRMWOZ RNYQZSZVY RUZ
WWXRXOWJUG RVHSGQGNH
 2701 12H\NJPISFS[ RNJNKPJRHR[S[
 2702 34H\LKLJMHNGPFTFVGWHXJXLWNUQL[ RLKMKMJNHPGTGVHWJWLVNTQK[ RLZYZY[ R
K[Y[
 2703 48H\MFXFQO RMFMGWG RWFPO RQNSNVOXQYTYUXXVZS[P[MZLYKWLW RPOSOVPXS R
TOWQXTXUWXTZ RXVVYSZPZMYLW ROZLX
 2704 18H\UIU[V[ RVFV[ RVFKVZV RUILV RLUZUZV
 2705 53H\MFLO RNGMN RMFWFWG RNGWG RMNPMSMVNXPYSYUXXVZS[P[MZLYKWLW RLOMO
ONSNVOXR RTNWPXSXUWXTZ RXVVYSZPZMYLW ROZLX
 2706 62H\VGWIXIWGTFRFOGMJLOLTMXOZR[S[VZXXYUYTXQVOSNRNOOMQ RWHTGRGOH RPG
NJMOMTNXQZ RMVOYRZSZVYXV RTZWXXUXTWQTO RXSVPSOROOPMS RQONQMT
 2707 12H\KFYFO[ RKFKGXG RXFN[O[
 2708 68H\PFMGLILKMMNNPOTPVQWRXTXWWYTZPZMYLWLTMRNQPPTOVNWMXKXIWGTFPF RNG
MIMKNMPNTOVPXRYTYWXYWZT[P[MZLYKWKTLRNPPOTNVMWKWIVG RWHTGPGMH RLXOZ RUZXX
 2709 62H\WPURRSQSNRLPKMKLLINGQFRFUGWIXMXRWWUZR[P[MZLXMXNZ RWMVPSR RWNUQ
RRQRNQLN RPRMPLMLLMIPG RLKNHQGRGUHWK RSGVIWMWRVWTZ RUYRZPZMY
 2710 16MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY
 2711 24MXTZS[R[QZQYRXSXTYT\S^Q_ RRYRZSZSYRY RS[T\ RTZS^
 2712 32MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY

 2713 40MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\S^Q_ RRYRZSZ
SYRY RS[T\ RTZS^
 2714 24MXRFRTST RRFSFST RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY
 2715 58I\LKLJMHNGQFTFWGXHYJYLXNWOUPRQ RLKMKMJNHQGTGWHXJXLWNUORP RMIPG R
UGXI RXMTP RRPRTSTSP RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY
 2716 24MXTFRGQIQLRMSMTLTKSJRJQK RRKRLSLSKRK RRGQK RQIRJ
 2717 24MXTHSIRIQHQGRFSFTGTJSLQM RRGRHSHSGRG RSITJ RTHSL
 2718 71F_\MZMXNWPUVTXSYQZMZKYJWJUKSLRQOSMTKTISGQFPFNGMIMKNNPQUWXZZ[\[ R
\M\NZNXO RYNXPVVUXSZQ[M[KZJYIWIUJSLQQNRMSKSIRG RSHQGPGNH ROGNINKONQQVWXY
ZZ\Z\[
 2719 51I\RBR_S_ RRBSBS_ RWIYIWGTFQFNGLILKMMNNVRWSXUXWWYTZQZOYNX RWIVHTG
QGNHMIMKNMVQXSYUYWXYWZT[Q[NZLXNX RXXUZ
 2720  8G^[BIbJb R[B\BJb
 2721 24KYUBSDQGOKNPNTOYQ]S`UbVb RUBVBTDRGPKOPOTPYR]T`Vb
 2722 24KYNBPDRGTKUPUTTYR]P`NbOb RNBOBQDSGUKVPVTUYS]Q`Ob
 2723 39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO R
WIMO RWIWJMNMO
 2724  8F_JQ[Q[R RJQJR[R
 2725 16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R
 2726 16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V
 2727 11NWSFRGRM RSGRM RSFTGRM
 2728 22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM
 2729 30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF
 2747  1RR
 2748  1NV
 2749  1JZ
 2750 42H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RTFRGPINLMOLSLVMYO[
 RQ[SZUXWUXRYNYKXHVF
 2751 15H]TJO[ RVFP[ RVFSIPKNL RUIQKNL
 2752 42H]OJPKOLNKNJOHPGSFVFYGZIZKYMWOTQPSMUKWI[ RVFXGYIYKXMVOPS RJYKXMX
RZUZWYXW RMXR[U[WZXW
 2753 50H]OJPKOLNKNJOHPGSFVFYGZIZKYMVOSP RVFXGYIYKXMVO RQPSPVQWRXTXWWYVZ
S[O[LZKYJWJVKULVKW RSPUQVRWTWWVYUZS[
 2754 10H]XGR[ RYFS[ RYFJUZU
 2755 39H]QFLP RQF[F RQGVG[F RLPMOPNSNVOWPXRXUWXUZR[O[LZKYJWJVKULVKW RSN
UOVPWRWUVXTZR[
 2756 46H]YIXJYKZJZIYGWFTFQGOIMLLOKSKWLYMZO[R[UZWXXVXSWQVPTOQOOPMRLT RTF
RGPINLMOLSLXMZ RR[TZVXWVWRVP
 2757 30H]NFLL R[FZIXLSRQUPWO[ RXLRRPUOWN[ RMIPFRFWI RNHPGRGWIYIZH[F
 2758 63H]SFPGOHNJNMOOQPTPXOYNZLZIYGVFSF RSFQGPHOJOMPOQP RTPWOXNYLYIXGVF
 RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP RQPNQLSKUKXLZN[ RR[UZVYWWWSVQ
 2759 46H]YMXOVQTRQROQNPMNMKNIPGSFVFXGYHZJZNYRXUVXTZQ[N[LZKXKWLVMWLX ROQ
NONKOIQGSF RXGYIYNXRWUUXSZQ[
 2760  6MXPYOZP[QZPY
 2761  8MXP[OZPYQZQ[P]N_
 2762 11MXSMRNSOTNSM RPYOZP[QZ
 2763 14MXSMRNSOTNSM RP[OZPYQZQ[P]N_
 2764 17MXUFTGRS RUGRS RUFVGRS RPYOZP[QZPY
 2765 34H]OJPKOLNKNJOHPGSFWFZG[I[KZMYNSPQQQSRTTT RWFYGZIZKYMXNVO RPYOZP[
QZPY
 2766  8MXVFTHSJSKTLUKTJ
 2767  8MXUHTGUFVGVHUJSL
 2768 55E_\N[O\P]O]N\M[MYNWPRXPZN[K[HZGXGVHTISKRPPROTMUKUITGRFPGOIOLPRQU
SXUZW[Y[ZYZX RK[IZHXHVITJSPP ROLPQQTSWUYWZYZZY
 2769 41H]TBL_ RYBQ_ RZJYKZL[K[JZHYGVFRFOGMIMKNMONVRXT RMKOMVQWRXTXWWYVZ
S[O[LZKYJWJVKULVKW
 2770  3G]_BEb
 2771 20KZZBVESHQKOONTNXO]P`Qb RVESIQMPPOUOZP_Qb
 2772 20JYSBTDUGVLVPUUSYQ\N_Jb RSBTEUJUOTTSWQ[N_
 2773  9J[TFTR ROIYO RYIOO
 2774  3E_IR[R
 2775  6E_RIR[ RIR[R
 2776  6E_IO[O RIU[U
 2777  6NWUFSM RVFSM
 2778 12I[PFNM RQFNM RYFWM RZFWM
 2779 14KZSFQGPIPKQMSNUNWMXKXIWGUFSF
 2801 18H\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[
 2802 31G]LFL[ RMFM[ RIFYFYLXF RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[
 2803 45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUP RUFWGXHYJYLXNWOUP RMPUPXQYRZTZW
YYXZU[I[ RUPWQXRYTYWXYWZU[
 2804 14I[NFN[ ROFO[ RKFZFZLYF RK[R[
 2805 31F^NFNLMTLXKZJ[ RXFX[ RYFY[ RKF\F RG[\[ RG[Gb RH[Gb R[[\b R\[\b
 2806 22G\LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[Y[YUX[
 2807 71CbRFR[ RSFS[ ROFVF RGGHHGIFHFGGFHFIGJIKMLONPWPYOZM[I\G]F^F_G_H^I
]H^G RNPLQKSJXIZH[ RNPMQLSKXJZI[G[FZEX RWPYQZS[X\Z][ RWPXQYSZX[Z\[^[_Z`X
 RO[V[
 2808 45H\LIKFKLLINGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[O[MZ
LYKWKVLUMVLW RWQXTXWWYVZT[
 2809 27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\F RXHLY RH[O[ RU[\[
 2810 37F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\F RXHLY RH[O[ RU[\[ RN@N?M?M@
NBPCTCVBW@
 2811 43F^KFK[ RLFL[ RHFOF RLPSPUOVMWIXGYFZF[G[HZIYHZG RSPUQVSWXXZY[ RSP
TQUSVXWZX[Z[[Z\X RH[O[
 2812 25E^MFMLLTKXJZI[H[GZGYHXIYHZ RXFX[ RYFY[ RJF\F RU[\[
 2813 30F_KFK[ RLFRX RKFR[ RYFR[ RYFY[ RZFZ[ RHFLF RYF]F RH[N[ RV[][
 2814 27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\F RLPXP RH[O[ RU[\[
 2815 44G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZ
Q[ RS[UZWXXVYRYOXKWIUGSF
 2816 21F^KFK[ RLFL[ RXFX[ RYFY[ RHF\F RH[O[ RU[\[
 2817 29G]LFL[ RMFM[ RIFUFXGYHZJZMYOXPUQMQ RUFWGXHYJYMXOWPUQ RI[P[
 2818 32G\XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXXYV RQFOGMILKKNKSLVMXOZQ[

 2819 16I\RFR[ RSFS[ RLFKLKFZFZLYF RO[V[
 2820 24H]KFRV RLFSV RZFSVQYPZN[M[LZLYMXNYMZ RIFOF RVF\F
 2821 48F_RFR[ RSFS[ ROFVF RPILJJLIOIRJULWPXUXYW[U\R\O[LYJUIPI RPIMJKLJO
JRKUMWPX RUXXWZU[R[OZLXJUI RO[V[
 2822 21H\KFX[ RLFY[ RYFK[ RIFOF RUF[F RI[O[ RU[[[
 2823 27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\F RH[\[ R[[\b R\[\b
 2824 28F]KFKQLSOTRTUSWQ RLFLQMSOT RWFW[ RXFX[ RHFOF RTF[F RT[[[
 2825 30BcGFG[ RHFH[ RRFR[ RSFS[ R]F][ R^F^[ RDFKF ROFVF RZFaF RD[a[
 2826 36BcGFG[ RHFH[ RRFR[ RSFS[ R]F][ R^F^[ RDFKF ROFVF RZFaF RD[a[ R`[
ab Ra[ab
 2827 31F`PFP[ RQFQ[ RIFHLHFTF RQPXP[Q\R]T]W\Y[ZX[M[ RXPZQ[R\T\W[YZZX[
 2828 41CaHFH[ RIFI[ REFLF RIPPPSQTRUTUWTYSZP[E[ RPPRQSRTTTWSYRZP[ R[F[[
 R\F\[ RXF_F RX[_[
 2829 29H]MFM[ RNFN[ RJFQF RNPUPXQYRZTZWYYXZU[J[ RUPWQXRYTYWXYWZU[
 2830 39H]LIKFKLLINGQFSFVGXIYKZNZSYVXXVZS[P[MZLYKWKVLUMVLW RSFUGWIXKYNYS
XVWXUZS[ RPPYP
 2831 59CbHFH[ RIFI[ REFLF RE[L[ RVFSGQIPKOOORPVQXSZV[X[[Z]X^V_R_O^K]I[G
XFVF RVFTGRIQKPOPRQVRXTZV[ RX[ZZ\X]V^R^O]K\IZGXF RIPOP
 2832 45G]WFW[ RXFX[ R[FOFLGKHJJJLKNLOOPWP ROFMGLHKJKLLNMOOP RRPPQORLYKZ
JZIY RPQOSMZL[J[IYIX RT[[[
 2901 39I]NONPMPMONNPMTMVNWOXQXXYZZ[ RWOWXXZZ[[[ RWQVRPSMTLVLXMZP[S[UZWX
 RPSNTMVMXNZP[
 2902 48H\XFWGQINKLNKQKULXNZQ[S[VZXXYUYSXPVNSMQMNNLPKS RXFWHUIQJNLLN RQM
ONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM
 2903 37H\MMM[ RNMN[ RJMUMXNYPYQXSUT RUMWNXPXQWSUT RNTUTXUYWYXXZU[J[ RUT
WUXWXXWZU[
 2904 14HZMMM[ RNMN[ RJMXMXRWM RJ[Q[
 2905 22F]NMNQMWLZK[ RWMW[ RXMX[ RKM[M RI[H`H[[[[`Z[
 2906 31H[LSXSXQWOVNTMQMNNLPKSKULXNZQ[S[VZXX RWSWPVN RQMONMPLSLUMXOZQ[
 2907 59E`RMR[ RSMS[ ROMVM RJNIOHNIMJMKNMRNSPTUTWSXRZN[M\M]N\O[N RPTNUMV
KZJ[ RPTNVLZK[I[HZGX RUTWUXVZZ[[ RUTWVYZZ[\[]Z^X RO[V[
 2908 42I[MOLMLQMONNPMTMWNXPXQWSTT RTMVNWPWQVSTT RQTTTWUXWXXWZT[P[MZLXLW
MVNWMX RTTVUWWWXVZT[
 2909 27G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[P[ RT[[[ RWNMZ
 2910 37G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[P[ RT[[[ RWNMZ ROGOFNFNG
OIQJSJUIVG
 2911 38H\MMM[ RNMN[ RJMQM RNTPTSSTRVNWMXMYNXOWN RPTSUTVVZW[ RPTRUSVUZV[
X[YZZX RJ[Q[
 2912 22G]NMNQMWLZK[J[IZJYKZ RWMW[ RXMX[ RKM[M RT[[[
 2913 30G^LML[ RLMR[ RMMRY RXMR[ RXMX[ RYMY[ RIMMM RXM\M RI[O[ RU[\[
 2914 27G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RMTWT RI[P[ RT[[[
 2915 36H\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RQMONMPLSLUMXOZQ[ RS[UZWXXU
XSWPUNSM
 2916 21G]LML[ RMMM[ RWMW[ RXMX[ RIM[M RI[P[ RT[[[
 2917 36G\LMLb RMMMb RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIM
MM RIbPb
 2918 28H[WPVQWRXQXPVNTMQMNNLPKSKULXNZQ[S[VZXX RQMONMPLSLUMXOZQ[
 2919 16I\RMR[ RSMS[ RMMLRLMYMYRXM RO[V[
 2920 22I[LMR[ RMMRY RXMR[P_NaLbKbJaK`La RJMPM RTMZM
 2921 52H]RFRb RSFSb ROFSF RRPQNPMNMLNKQKWLZN[P[QZRX RNMMNLQLWMZN[ RWMXN
YQYWXZW[ RSPTNUMWMYNZQZWYZW[U[TZSX RObVb
 2922 21H\LMW[ RMMX[ RXML[ RJMPM RTMZM RJ[P[ RT[Z[
 2923 23G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[[[[`Z[
 2924 28G]LMLTMVPWRWUVWT RMMMTNVPW RWMW[ RXMX[ RIMPM RTM[M RT[[[
 2925 30CbHMH[ RIMI[ RRMR[ RSMS[ R\M\[ R]M][ REMLM ROMVM RYM`M RE[`[
 2926 32CbHMH[ RIMI[ RRMR[ RSMS[ R\M\[ R]M][ REMLM ROMVM RYM`M RE[`[``_[

 2927 27H]QMQ[ RRMR[ RLMKRKMUM RRTVTYUZWZXYZV[N[ RVTXUYWYXXZV[
 2928 37E_JMJ[ RKMK[ RGMNM RKTOTRUSWSXRZO[G[ ROTQURWRXQZO[ RYMY[ RZMZ[ R
VM]M RV[][
 2929 25J[OMO[ RPMP[ RLMSM RPTTTWUXWXXWZT[L[ RTTVUWWWXVZT[
 2930 34I\MOLMLQMONNPMSMVNXPYSYUXXVZS[P[NZLXLWMVNWMX RSMUNWPXSXUWXUZS[ R
RTXT
 2931 51DaIMI[ RJMJ[ RFMMM RF[M[ RVMSNQPPSPUQXSZV[X[[Z]X^U^S]P[NXMVM RVM
TNRPQSQURXTZV[ RX[ZZ\X]U]S\PZNXM RJTPT
 2932 40G\VMV[ RWMW[ RZMOMLNKPKQLSOTVT ROMMNLPLQMSOT RTTQUPVNZM[ RTTRUQV
OZN[L[KZJX RS[Z[
 3001 36H\RFKZ RQIW[ RRIX[ RRFY[ RMUVU RI[O[ RT[[[ RKZJ[ RKZM[ RWZU[ RWY
V[ RXYZ[
 3002 78G]LFL[ RMGMZ RNFN[ RIFUFXGYHZJZLYNXOUP RXHYJYLXN RUFWGXIXMWOUP R
NPUPXQYRZTZWYYXZU[I[ RXRYTYWXY RUPWQXSXXWZU[ RJFLG RKFLH ROFNH RPFNG RLZ
J[ RLYK[ RNYO[ RNZP[
 3003 37G\XIYFYLXIVGTFQFNGLIKKJNJSKVLXNZQ[T[VZXXYV RMILKKNKSLVMX RQFOGMJ
LNLSMWOZQ[
 3004 62G]LFL[ RMGMZ RNFN[ RIFSFVGXIYKZNZSYVXXVZS[I[ RWIXKYNYSXVWX RSFUG
WJXNXSWWUZS[ RJFLG RKFLH ROFNH RPFNG RLZJ[ RLYK[ RNYO[ RNZP[
 3005 83G\LFL[ RMGMZ RNFN[ RIFYFYL RNPTP RTLTT RI[Y[YU RJFLG RKFLH ROFNH
 RPFNG RTFYG RVFYH RWFYI RXFYL RTLSPTT RTNRPTR RTOPPTQ RLZJ[ RLYK[ RNYO[
 RNZP[ RT[YZ RV[YY RW[YX RX[YU
 3006 70G[LFL[ RMGMZ RNFN[ RIFYFYL RNPTP RTLTT RI[Q[ RJFLG RKFLH ROFNH R
PFNG RTFYG RVFYH RWFYI RXFYL RTLSPTT RTNRPTR RTOPPTQ RLZJ[ RLYK[ RNYO[ R
NZP[
 3007 60G^XIYFYLXIVGTFQFNGLIKKJNJSKVLXNZQ[T[VZXZY[YS RMILKKNKSLVMX RQFOG
MJLNLSMWOZQ[ RXTXY RWSWYVZ RTS\S RUSWT RVSWU RZSYU R[SYT
 3008 81F^KFK[ RLGLZ RMFM[ RWFW[ RXGXZ RYFY[ RHFPF RTF\F RMPWP RH[P[ RT[
\[ RIFKG RJFKH RNFMH ROFMG RUFWG RVFWH RZFYH R[FYG RKZI[ RKYJ[ RMYN[ RMZ
O[ RWZU[ RWYV[ RYYZ[ RYZ[[
 3009 39LXQFQ[ RRGRZ RSFS[ RNFVF RN[V[ ROFQG RPFQH RTFSH RUFSG RQZO[ RQY
P[ RSYT[ RSZU[
 3010 45JJSFSWRZQ[ RTGTWSZ RUFUWTZQ[O[MZLXLVMUNUOVOWNXMX RMVMWNWNVMV RPF
XF RQFSG RRFSH RVFUH RWFUG
 3011 69F\KFK[ RLGLZ RMFM[ RXGMR RPPW[ RQPX[ RQNY[ RHFPF RUF[F RH[P[ RT[
[[ RIFKG RJFKH RNFMH ROFMG RWFXG RZFXG RKZI[ RKYJ[ RMYN[ RMZO[ RWYU[ RWY
Z[
 3012 52I[NFN[ ROGOZ RPFP[ RKFSF RK[Z[ZU RLFNG RMFNH RQFPH RRFPG RNZL[ R
NYM[ RPYQ[ RPZR[ RU[ZZ RW[ZY RX[ZX RY[ZU
 3013 63E_JFJZ RJFQ[ RKFQX RLFRX RXFQ[ RXFX[ RYGYZ RZFZ[ RGFLF RXF]F RG[
M[ RU[][ RHFJG R[FZH R\FZG RJZH[ RJZL[ RXZV[ RXYW[ RZY[[ RZZ\[
 3014 39F^KFKZ RKFY[ RLFXX RMFYX RYGY[ RHFMF RVF\F RH[N[ RIFKG RWFYG R[F
YG RKZI[ RKZM[
 3015 54G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RMILKKNKSLVMX RWXXV
YSYNXKWI RQFOGMJLNLSMWOZQ[ RS[UZWWXSXNWJUGSF
 3016 59G]LFL[ RMGMZ RNFN[ RIFUFXGYHZJZMYOXPUQNQ RXHYJYMXO RUFWGXIXNWPUQ
 RI[Q[ RJFLG RKFLH ROFNH RPFNG RLZJ[ RLYK[ RNYO[ RNZP[
 3017 77G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RMILKKNKSLVMX RWXXV
YSYNXKWI RQFOGMJLNLSMWOZQ[ RS[UZWWXSXNWJUGSF RNXOVQURUTVUXV^W`Y`Z^Z\ RV\
W^X_Y_ RUXW]X^Y^Z]
 3018 80G]LFL[ RMGMZ RNFN[ RIFUFXGYHZJZLYNXOUPNP RXHYJYLXN RUFWGXIXMWOUP
 RRPTQUSWYX[Z[[Y[W RWWXYYZZZ RTQURXXYYZY[X RI[Q[ RJFLG RKFLH ROFNH RPFNG
 RLZJ[ RLYK[ RNYO[ RNZP[
 3019 44H\XIYFYLXIVGSFPFMGKIKLLNOPURWSXUXXWZ RLLMNOOUQWRXT RMGLILKMMONUP
XRYTYWXYWZT[Q[NZLXKUK[LX
 3020 57H\JFJL RQFQ[ RRGRZ RSFS[ RZFZL RJFZF RN[V[ RKFJL RLFJI RMFJH ROF
JG RUFZG RWFZH RXFZI RYFZL RQZO[ RQYP[ RSYT[ RSZU[
 3021 45F^KFKULXNZQ[S[VZXXYUYG RLGLVMX RMFMVNYOZQ[ RHFPF RVF\F RIFKG RJF
KH RNFMH ROFMG RWFYG R[FYG
 3022 34H\KFR[ RLFRXR[ RMFSX RYGR[ RIFPF RUF[F RJFLH RNFMH ROFMG RWFYG R
ZFYG
 3023 55F^JFN[ RKFNVN[ RLFOV RRFOVN[ RRFV[ RSFVVV[ RTFWV RZGWVV[ RGFOF R
RFTF RWF]F RHFKG RIFKH RMFLH RNFLG RXFZG R\FZG
 3024 54H\KFW[ RLFX[ RMFY[ RXGLZ RIFPF RUF[F RI[O[ RT[[[ RJFMH RNFMH ROF
MG RVFXG RZFXG RLZJ[ RLZN[ RWZU[ RWYV[ RWYZ[
 3025 48G]JFQQQ[ RKFRQRZ RLFSQS[ RYGSQ RHFOF RVF\F RN[V[ RIFKG RNFLG RWF
YG R[FYG RQZO[ RQYP[ RSYT[ RSZU[
 3026 41H\YFKFKL RWFK[ RXFL[ RYFM[ RK[Y[YU RLFKL RMFKI RNFKH RPFKG RT[YZ
 RV[YY RW[YX RX[YU
 3051 38H\UFIZ RSJT[ RTHUZ RUFUHVYV[ RLUTU RF[L[ RQ[X[ RIZG[ RIZK[ RTZR[
 RTYS[ RVYW[
 3052 78F^OFI[ RPFJ[ RQFK[ RLFWFZG[I[KZNYOVP RYGZIZKYNXO RWFXGYIYKXNVP R
NPVPXQYSYUXXVZR[F[ RWQXSXUWXUZ RVPWRWUVXTZR[ RMFPG RNFOH RRFPH RSFPG RJZ
G[ RJYH[ RKYL[ RJZM[
 3053 41H]ZH[H\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[S[UZWXXV RQHOJNLMOLSLWMY R
TFRGPJOLNOMSMXNZP[
 3054 63F]OFI[ RPFJ[ RQFK[ RLFUFXGYHZKZOYSWWUYSZO[F[ RWGXHYKYOXSVWTY RUF
WHXKXOWSUWRZO[ RMFPG RNFOH RRFPH RSFPG RJZG[ RJYH[ RKYL[ RJZM[
 3055 80F]OFI[ RPFJ[ RQFK[ RULST RLF[FZL RNPTP RF[U[WV RMFPG RNFOH RRFPH
 RSFPG RWFZG RXFZH RYFZI RZFZL RULSPST RTNRPSR RTOQPSQ RJZG[ RJYH[ RKYL[
 RJZM[ RP[UZ RR[UY RUYWV
 3056 70F\OFI[ RPFJ[ RQFK[ RULST RLF[FZL RNPTP RF[N[ RMFPG RNFOH RRFPH R
SFPG RWFZG RXFZH RYFZI RZFZL RULSPST RTNRPSR RTOQPSQ RJZG[ RJYH[ RKYL[ R
JZM[
 3057 65H^ZH[H\F[L[JZHYGWFTFQGOIMLLOKSKVLYMZP[R[UZWXYT RQHOJNLMOLSLWMY R
VXWWXT RTFRGPJOLNOMSMXNZP[ RR[TZVWWT RTT\T RUTWU RVTWW RZTXV R[TXU
 3058 81E_NFH[ ROFI[ RPFJ[ RZFT[ R[FU[ R\FV[ RKFSF RWF_F RLPXP RE[M[ RQ[
Y[ RLFOG RMFNH RQFOH RRFOG RXF[G RYFZH R]F[H R^F[G RIZF[ RIYG[ RJYK[ RIZ
L[ RUZR[ RUYS[ RVYW[ RUZX[
 3059 39KYTFN[ RUFO[ RVFP[ RQFYF RK[S[ RRFUG RSFTH RWFUH RXFUG ROZL[ ROY
M[ RPYQ[ ROZR[
 3060 47I\WFRWQYO[ RXFTSSVRX RYFUSSXQZO[M[KZJXJVKULUMVMWLXKX RKVKWLWLVKV
 RTF\F RUFXG RVFWH RZFXH R[FXG
 3061 72F]OFI[ RPFJ[ RQFK[ R\GMR RQOU[ RROV[ RSNWZ RLFTF RYF_F RF[N[ RR[
Y[ RMFPG RNFOH RRFPH RSFPG RZF\G R^F\G RJZG[ RJYH[ RKYL[ RJZM[ RUZS[ RUY
T[ RVYX[
 3062 49H\QFK[ RRFL[ RSFM[ RNFVF RH[W[YU ROFRG RPFQH RTFRH RUFRG RLZI[ R
LYJ[ RMYN[ RLZO[ RR[WZ RT[XX RV[YU
 3063 68D`MFGZ RMGNYN[ RNFOY ROFPX R[FPXN[ R[FU[ R\FV[ R]FW[ RJFOF R[F`F
 RD[J[ RR[Z[ RKFMG RLFMH R^F\H R_F\G RGZE[ RGZI[ RVZS[ RVYT[ RWYX[ RVZY[
 3064 43F_OFIZ ROFV[ RPFVX RQFWX R\GWXV[ RLFQF RYF_F RF[L[ RMFPG RNFPH R
ZF\G R^F\G RIZG[ RIZK[
 3065 56G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF ROIMLLOKSKWLY RUXWU
XRYNYJXH RSFQGOJNLMOLSLXMZN[ RQ[SZUWVUWRXNXIWGVF
 3066 60F]OFI[ RPFJ[ RQFK[ RLFXF[G\I\K[NYPUQMQ RZG[I[KZNXP RXFYGZIZKYNWP
UQ RF[N[ RMFPG RNFOH RRFPH RSFPG RJZG[ RJYH[ RKYL[ RJZM[
 3067 78G]SFPGNILLKOJSJVKYLZN[Q[TZVXXUYRZNZKYHXGVFSF ROIMLLOKSKWLY RUXWU
XRYNYJXH RSFQGOJNLMOLSLXMZN[ RQ[SZUWVUWRXNXIWGVF RLXMVOUPURVSXT]U^V^W] R
T^U_V_ RSXS_T`V`W]W\
 3068 78F^OFI[ RPFJ[ RQFK[ RLFWFZG[I[KZNYOVPNP RYGZIZKYNXO RWFXGYIYKXNVP
 RRPTQURWXXYYYZX RWYXZYZ RURVZW[Y[ZXZW RF[N[ RMFPG RNFOH RRFPH RSFPG RJZ
G[ RJYH[ RKYL[ RJZM[
 3069 44G^ZH[H\F[L[JZHYGVFRFOGMIMLNNPPVSWUWXVZ RNLONVRWT ROGNINKOMUPWRXT
XWWYVZS[O[LZKYJWJUI[JYKY
 3070 54G]TFN[ RUFO[ RVFP[ RMFKL R]F\L RMF]F RK[S[ RNFKL RPFLI RRFMG RYF
\G RZF\H R[F\I R\F\L ROZL[ ROYM[ RPYQ[ ROZR[
 3071 48F_NFKQJUJXKZN[R[UZWXXU\G ROFLQKUKYLZ RPFMQLULYN[ RKFSF RYF_F RLF
OG RMFNH RQFOH RRFOG RZF\G R^F\G
 3072 35H\NFNHOYO[ ROGPX RPFQW R[GO[ RLFSF RXF^F RMFNH RQFPH RRFOG RYF[G
 R]F[G
 3073 57E_MFMHKYK[ RNGLX ROFMW RUFMWK[ RUFUHSYS[ RVGTX RWFUW R]GUWS[ RJF
RF RUFWF RZF`F RKFNG RLFMH RPFNI RQFNG R[F]G R_F]G
 3074 54G]NFT[ ROFU[ RPFV[ R[GIZ RLFSF RXF^F RF[L[ RQ[X[ RMFOH RQFPH RRF
PG RYF[G R]F[G RIZG[ RIZK[ RTZR[ RTYS[ RUYW[
 3075 51G]MFQPN[ RNFRPO[ ROFSPP[ R\GSP RKFRF RYF_F RK[S[ RLFNG RPFOH RQF
NG RZF\G R^F\G ROZL[ ROYM[ RPYQ[ ROZR[
 3076 35G]ZFH[ R[FI[ R\FJ[ R\FNFLL RH[V[XU ROFLL RPFMI RRFNG RR[VZ RT[WX
 RU[XU
 3101 54I]NPNOOOOQMQMONNPMTMVNWOXQXXYZZ[ RVOWQWXXZ RTMUNVPVXWZZ[[[ RVRUS
PTMULWLXMZP[S[UZVX RNUMWMXNZ RUSQTOUNWNXOZP[
 3102 47G\LFL[MZOZ RMGMY RIFNFNZ RNPONQMSMVNXPYSYUXXVZS[Q[OZNX RWPXRXVWX
 RSMUNVOWRWVVYUZS[ RJFLG RKFLH
 3103 34H[WQWPVPVRXRXPVNTMQMNNLPKSKULXNZQ[S[VZXX RMPLRLVMX RQMONNOMRMVNY
OZQ[
 3104 52H]VFV[[[ RWGWZ RSFXFX[ RVPUNSMQMNNLPKSKULXNZQ[S[UZVX RMPLRLVMX R
QMONNOMRMVNYOZQ[ RTFVG RUFVH RXYY[ RXZZ[
 3105 41H[MSXSXQWOVNSMQMNNLPKSKULXNZQ[S[VZXX RWRWQVO RMPLRLVMX RVSVPUNSM
 RQMONNOMRMVNYOZQ[
 3106 40KYWHWGVGVIXIXGWFTFRGQHPKP[ RRHQKQZ RTFSGRIR[ RMMVM RM[U[ RPZN[ R
PYO[ RRYS[ RRZT[
 3107 89I\XNYOZNYMXMVNUO RQMONNOMQMSNUOVQWSWUVVUWSWQVOUNSMQM ROONQNSOU R
UUVSVQUO RQMPNOPOTPVQW RSWTVUTUPTNSM RNUMVLXLYM[N\Q]U]X^Y_ RN[Q\U\X] RLY
MZP[U[X\Y^Y_XaUbObLaK_K^L\O[ RObMaL_L^M\O[
 3108 65G^LFL[ RMGMZ RIFNFN[ RNQOOPNRMUMWNXOYRY[ RWOXRXZ RUMVNWQW[ RI[Q[
 RT[\[ RJFLG RKFLH RLZJ[ RLYK[ RNYO[ RNZP[ RWZU[ RWYV[ RYYZ[ RYZ[[
 3109 43LXQFQHSHSFQF RRFRH RQGSG RQMQ[ RRNRZ RNMSMS[ RN[V[ ROMQN RPMQO R
QZO[ RQYP[ RSYT[ RSZU[
 3110 41KXRFRHTHTFRF RSFSH RRGTG RRMR^QaPb RSNS]R` ROMTMT]S`RaPbMbLaL_N_
NaMaM` RPMRN RQMRO
 3111 61G]LFL[ RMGMZ RIFNFN[ RWNNW RRSY[ RRTX[ RQTW[ RTM[M RI[Q[ RT[[[ R
JFLG RKFLH RUMWN RZMWN RLZJ[ RLYK[ RNYO[ RNZP[ RWYU[ RVYZ[
 3112 31LXQFQ[ RRGRZ RNFSFS[ RN[V[ ROFQG RPFQH RQZO[ RQYP[ RSYT[ RSZU[
 3113 99AcFMF[ RGNGZ RCMHMH[ RHQIOJNLMOMQNROSRS[ RQORRRZ ROMPNQQQ[ RSQTO
UNWMZM\N]O^R^[ R\O]R]Z RZM[N\Q\[ RC[K[ RN[V[ RY[a[ RDMFN REMFO RFZD[ RFY
E[ RHYI[ RHZJ[ RQZO[ RQYP[ RSYT[ RSZU[ R\ZZ[ R\Y[[ R^Y_[ R^Z`[
 3114 65G^LML[ RMNMZ RIMNMN[ RNQOOPNRMUMWNXOYRY[ RWOXRXZ RUMVNWQW[ RI[Q[
 RT[\[ RJMLN RKMLO RLZJ[ RLYK[ RNYO[ RNZP[ RWZU[ RWYV[ RYYZ[ RYZ[[
 3115 46H\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RMPLRLVMX RWXXVXRWP RQMONNO
MRMVNYOZQ[ RS[UZVYWVWRVOUNSM
 3116 60G\LMLb RMNMa RIMNMNb RNPONQMSMVNXPYSYUXXVZS[Q[OZNX RWPXRXVWX RSM
UNVOWRWVVYUZS[ RIbQb RJMLN RKMLO RLaJb RL`Kb RN`Ob RNaPb
 3117 55H\VNVb RWOWa RUNWNXMXb RVPUNSMQMNNLPKSKULXNZQ[S[UZVX RMPLRLVMX R
QMONNOMRMVNYOZQ[ RSb[b RVaTb RV`Ub RX`Yb RXaZb
 3118 43IZNMN[ RONOZ RKMPMP[ RWOWNVNVPXPXNWMUMSNQPPS RK[S[ RLMNN RMMNO R
NZL[ RNYM[ RPYQ[ RPZR[
 3119 43J[WOXMXQWOVNTMPMNNMOMQNSPTUUWVXY RNNMQ RNRPSUTWU RXVWZ RMONQPRUS
WTXVXYWZU[Q[OZNYMWM[NY
 3120 22KZPHPVQYRZT[V[XZYX RQHQWRY RPHRFRWSZT[ RMMVM
 3121 43G^LMLVMYNZP[S[UZVYWW RMNMWNY RIMNMNWOZP[ RWMW[\[ RXNXZ RTMYMY[ R
JMLN RKMLO RYYZ[ RYZ[[
 3122 31I[LMR[ RMMRY RNMSY RXNSYR[ RJMQM RTMZM RKMNO RPMNN RVMXN RYMXN
 3123 45F^JMN[ RKMNX RLMOX RRMOXN[ RRMV[ RSMVX RRMTMWX RZNWXV[ RGMOM RWM
]M RHMKN RNMLN RXMZN R\MZN
 3124 48H\LMV[ RMMW[ RNMX[ RWNMZ RJMQM RTMZM RJ[P[ RS[Z[ RKMMN RPMNN RUM
WN RYMWN RMZK[ RMZO[ RVZT[ RWZY[
 3125 40H[LMR[ RMMRY RNMSY RXNSYP_NaLbJbIaI_K_KaJaJ` RJMQM RTMZM RKMNO R
PMNN RVMXN RYMXN
 3126 41I[VML[ RWMM[ RXMN[ RXMLMLQ RL[X[XW RMMLQ RNMLP ROMLO RQMLN RS[XZ
 RU[XY RV[XX RW[XW
 3151 50G]WMUTUXVZW[Y[[Y\W RXMVTVZ RWMYMWTVX RUTUQTNRMPMMNKQJTJVKYLZN[P[
RZSYTWUT RNNLQKTKWLY RPMNOMQLTLWMZN[
 3152 52I\PFNMMSMWNYOZQ[S[VZXWYTYRXOWNUMSMQNPOOQNT RQFOMNQNWOZ RVYWWXTXQ
WO RMFRFPMNT RS[UYVWWTWQVNUM RNFQG ROFPH
 3153 34I[WQWPVPVRXRXPWNUMRMONMQLTLVMYNZP[R[UZWW ROONQMTMWNY RRMPOOQNTNW
OZP[
 3154 58G]YFVQUUUXVZW[Y[[Y\W RZFWQVUVZ RVF[FWTVX RUTUQTNRMPMMNKQJTJVKYLZ
N[P[RZSYTWUT RMOLQKTKWLY RPMNOMQLTLWMZN[ RWFZG RXFYH
 3155 33I[MVQUTTWRXPWNUMRMONMQLTLVMYNZP[R[UZWX ROONQMTMWNY RRMPOOQNTNWOZ
P[
 3156 45JZZHZGYGYI[I[GZFXFVGTISKRNQRO[N^M`Kb RTJSMRRP[O^ RXFVHUJTMSRQZP]
O_MaKbIbHaH_J_JaIaI` RNMYM
 3157 57H]XMT[S^QaOb RYMU[S_ RXMZMV[T_RaObLbJaI`I^K^K`J`J_ RVTVQUNSMQMNN
LQKTKVLYMZO[Q[SZTYUWVT RNOMQLTLWMY RQMOONQMTMWNZO[
 3158 41G]OFI[K[ RPFJ[ RLFQFK[ RMTOPQNSMUMWNXPXSVX RWNWRVVVZ RWPUUUXVZW[
Y[[Y\W RMFPG RNFOH
 3159 35KXSFSHUHUFSF RTFTH RSGUG RLQMOOMQMRNSPSSQX RRNRRQVQZ RRPPUPXQZR[
T[VYWW
 3160 45KXUFUHWHWFUF RVFVH RUGWG RMQNOPMRMSNTPTSRZQ]P_NaLbJbIaI_K_KaJaJ`
 RSNSSQZP]O_ RSPRTP[O^N`Lb
 3161 49G]OFI[K[ RPFJ[ RLFQFK[ RYOYNXNXPZPZNYMWMUNQROS RMSOSQTRUTYUZWZ R
QUSYTZ ROSPTRZS[U[WZYW RMFPG RNFOH
 3162 26LXTFQQPUPXQZR[T[VYWW RUFRQQUQZ RQFVFRTQX RRFUG RSFTH
 3163 61@cAQBODMFMGNHPHSF[ RGNGSE[ RGPFTD[F[ RHSJPLNNMPMRNSPSSQ[ RRNRSP[
 RRPQTO[Q[ RSSUPWNYM[M]N^P^S\X R]N]R\V\Z R]P[U[X\Z][_[aYbW
 3164 42F^GQHOJMLMMNNPNSL[ RMNMSK[ RMPLTJ[L[ RNSPPRNTMVMXNYPYSWX RXNXRWV
WZ RXPVUVXWZX[Z[\Y]W
 3165 46H\QMNNLQKTKVLYMZP[S[VZXWYTYRXOWNTMQM RNOMQLTLWMY RVYWWXTXQWO RQM
OONQMTMWNZP[ RS[UYVWWTWQVNTM
 3166 66G]HQIOKMMMNNOPOSNWKb RNNNSMWJb RNPMTIb ROTPQQORNTMVMXNYOZRZTYWWZ
T[R[PZOWOT RXOYQYTXWWY RVMWNXQXTWWVYT[ RFbNb RJaGb RJ`Hb RK`Lb RJaMb
 3167 57G\WMQb RXMRb RWMYMSb RUTUQTNRMPMMNKQJTJVKYLZN[P[RZSYTWUT RMOLQKT
KWLY RPMNOMQLTLWMZN[ RNbVb RRaOb RR`Pb RS`Tb RRaUb
 3168 30I[JQKOMMOMPNQPQTO[ RPNPTN[ RPPOTM[O[ RYOYNXNXPZPZNYMWMUNSPQT
 3169 47J[XPXOWOWQYQYOXNUMRMONNONQOSQTTUVVWX RONNQ RORQSTTVU RWVVZ RNOOQ
QRTSVTWVWXVZS[P[MZLYLWNWNYMYMX
 3170 23KYTFQQPUPXQZR[T[VYWW RUFRQQUQZ RTFVFRTQX RNMXM
 3171 42F^GQHOJMLMMNNPNSLX RMNMRLVLZ RMPKUKXLZN[P[RZTXVU RXMVUVXWZX[Z[\Y
]W RYMWUWZ RXMZMXTWX
 3172 29H\IQJOLMNMONPPPSNX RONORNVNZ ROPMUMXNZP[R[TZVXXUYQYMXMXNYP
 3173 48CaDQEOGMIMJNKPKSIX RJNJRIVIZ RJPHUHXIZK[M[OZQXRU RTMRURXSZU[W[YZ
[X]U^Q^M]M]N^P RUMSUSZ RTMVMTTSX
 3174 51G]JQLNNMPMRNSPSR RPMQNQRPVOXMZK[I[HZHXJXJZIZIY RRORRQVQY RZOZNYN
YP[P[NZMXMVNTPSRRVRZS[ RPVPXQZS[U[WZYW
 3175 49G]HQIOKMMMNNOPOSMX RNNNRMVMZ RNPLULXMZO[Q[SZUXWT RYMU[T^RaPb RZM
V[T_ RYM[MW[U_SaPbMbKaJ`J^L^L`K`K_
 3176 39H\YMXOVQNWLYK[ RXOOOMPLR RVORNONNO RVORMOMMOLR RLYUYWXXV RNYRZUZ
VY RNYR[U[WYXV
 3197  1RR
 3198  1NV
 3199  1JZ

SHAR_EOF
if test 28258 -ne "`wc -c 'hersh.oc3'`"
then
	echo shar: error transmitting "'hersh.oc3'" '(should have been 28258 characters)'
fi
echo shar: extracting "'hersh.oc4'" '(28235 characters)'
if test -f 'hersh.oc4'
then
	echo shar: over-writing existing file "'hersh.oc4'"
fi
cat << \SHAR_EOF > 'hersh.oc4'
 3200 50H\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RNHMJLNLSMWNY RVYWWXSXNWJVH
 RQFOGNIMNMSNXOZQ[ RS[UZVXWSWNVIUGSF
 3201 28H\QHQ[ RRHRZ RSFS[ RSFPINJ RM[W[ RQZO[ RQYP[ RSYT[ RSZU[
 3202 62H\LJLKMKMJLJ RLIMINJNKMLLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RWH
XJXLWN RTFVGWJWLVNTPPR RKYLXNXSYWYYX RNXSZWZXY RNXS[W[XZYXYV
 3203 76H\LJLKMKMJLJ RLIMINJNKMLLLKKKJLHMGPFTFWGXIXLWNTO RVGWIWLVN RSFUG
VIVLUNSO RQOTOVPXRYTYWXYWZT[P[MZLYKWKVLUMUNVNWMXLX RWRXTXWWY RSOUPVQWTWW
VZT[ RLVLWMWMVLV
 3204 28H\SIS[ RTHTZ RUFU[ RUFJUZU RP[X[ RSZQ[ RSYR[ RUYV[ RUZW[
 3205 55H\MFKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMUNVNWMXLX RWPXRXVWX RSMUN
VOWRWVVYUZS[ RLVLWMWMVLV RMFWF RMGUG RMHQHUGWF
 3206 69H\VIVJWJWIVI RWHVHUIUJVKWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQ
VOSNQNOONPMR RNIMKLOLUMXNY RWXXVXSWQ RRFPGOHNJMNMUNXOZQ[ RS[UZVYWVWSVPUO
SN
 3207 43H\KFKL RYFYIXLTQSSRWR[ RSRRTQWQ[ RXLSQQTPWP[R[ RKJLHNFPFUIWIXHYF
 RMHNGPGRH RKJLINHPHUI
 3208 79H\PFMGLILLMNPOTOWNXLXIWGTFPF RNGMIMLNN RVNWLWIVG RPFOGNINLONPO R
TOUNVLVIUGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RMQLSLWMY RWYXWXSWQ RPONP
MSMWNZP[ RT[VZWWWSVPTO
 3209 69H\MWMXNXNWMW RWOVQURSSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLW
MVNVOWOXNYMY RMPLNLKMI RVHWIXLXRWVVX RQSORNQMNMKNHOGQF RSFUGVIWLWSVWUYTZ
R[
 3210 16MXRXQYQZR[S[TZTYSXRX RRYRZSZSYRY
 3211 24MXTZS[R[QZQYRXSXTYT\S^Q_ RRYRZSZSYRY RS[T\ RTZS^
 3212 32MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY

 3213 40MXRMQNQORPSPTOTNSMRM RRNROSOSNRN RTZS[R[QZQYRXSXTYT\S^Q_ RRYRZSZ
SYRY RS[T\ RTZS^
 3214 34MXRFQGQIRQ RRFRTST RRFSFST RSFTGTISQ RRXQYQZR[S[TZTYSXRX RRYRZSZ
SYRY
 3215 52I\MKMJNJNLLLLJMHNGPFTFWGXHYJYLXNWOSQ RWHXIXMWN RTFVGWIWMVOUP RRQ
RTSTSQRQ RRXQYQZR[S[TZTYSXRX RRYRZSZSYRY
 3216 24MXTFRGQIQLRMSMTLTKSJRJQK RRKRLSLSKRK RRGQK RQIRJ
 3217 24MXTHSIRIQHQGRFSFTGTJSLQM RRGRHSHSGRG RSITJ RTHSL
 3218 74E_[O[NZNZP\P\N[MZMYNXPVUTXRZP[L[JZIXIUJSPORMSKSIRGPFNGMIMLNOPRTW
WZY[[[\Y\X RKZJXJUKSLR RRMSI RSKRG RNGMK RNNPQTVWYYZ RN[LZKXKULSPO RMINM
QQUVXYZZ[Z\Y
 3219 56H\PBP_ RTBT_ RXKXJWJWLYLYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RLLMNOOUQ
WRXT RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWKUMUMWLWLV
 3220  8G^[BIbJb R[B\BJb
 3221 27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\ RSDRFQIPOPUQ[R^S`
 3222 27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\ RQDRFSITOTUS[R^Q`
 3223 39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO R
WIMO RWIWJMNMO
 3224  8F_JQ[Q[R RJQJR[R
 3225 16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R
 3226 16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V
 3227 11NWSFRGRM RSGRM RSFTGRM
 3228 22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM
 3229 30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF
 3247  1RR
 3248  1NV
 3249  1JZ
 3250 58H]TFQGOIMLLOKSKVLYMZO[Q[TZVXXUYRZNZKYHXGVFTF RQHOJNLMOLSLWMY RTY
VWWUXRYNYJXH RTFRGPJOLNOMSMXNZO[ RQ[SZUWVUWRXNXIWGVF
 3251 20H]TJO[Q[ RWFUJP[ RWFQ[ RWFTIQKOL RTJRKOL
 3252 52H]OKOJPJPLNLNJOHPGSFVFYGZIZKYMWOMUKWI[ RXGYIYKXMVOSQ RVFWGXIXKWM
UOMU RJYKXMXRYWYXX RMXRZWZ RMXR[U[WZXXXW
 3253 64H]OKOJPJPLNLNJOHPGSFVFYGZIZKYMXNVOSP RXGYIYKXMWN RVFWGXIXKWMUOSP
 RQPSPVQWRXTXWWYUZR[O[LZKYJWJULULWKWKV RVRWTWWVY RSPUQVSVWUYTZR[
 3254 15H]WJR[T[ RZFXJS[ RZFT[ RZFJUZU
 3255 49H]QFLP RQF[F RQGYG RPHUHYG[F RLPMOPNSNVOWPXRXUWXUZQ[N[LZKYJWJULU
LWKWKV RVPWRWUVXTZ RSNUOVQVUUXSZQ[
 3256 61H]YJYIXIXKZKZIYGWFTFQGOIMLLOKSKVLYMZO[R[UZWXXVXSWQVPTOQOOPNQMS R
PINLMOLSLWMY RVXWVWSVQ RTFRGPJOLNOMSMXNZO[ RR[TZUYVVVRUPTO
 3257 39H]NFLL R[FZIXLTQRTQWP[ RRSPWO[ RXLRRPUOWN[P[ RMIPFRFWI ROGRGWI R
MIOHRHWIYIZH[F
 3258104H]SFPGOHNJNMOOQPTPWOYNZLZIYGWFSF RUFPG RPHOJONPO ROORP RSPWO RXN
YLYIXG RYGUF RSFQHPJPNQP RTPVOWNXLXHWF RQPMQKSJUJXKZN[R[VZWYXWXTWRVQTP R
RPMQ RNQLSKUKXLZ RKZP[VZ RVYWWWTVR RVQSP RQPOQMSLULXMZN[ RR[TZUYVWVSUQTP
 3259 61H]XNWPVQTRQROQNPMNMKNIPGSFVFXGYHZKZNYRXUVXTZQ[N[LZKXKVMVMXLXLW R
OPNNNKOI RXHYJYNXRWUUX RQRPQOOOKPHQGSF RVFWGXIXNWRVUUWSZQ[
 3260 16MXPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY
 3261 22MXQ[P[OZOYPXQXRYR[Q]P^N_ RPYPZQZQYPY RQ[Q\P^
 3262 32MXSMRNROSPTPUOUNTMSM RSNSOTOTNSN RPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY

 3263 38MXSMRNROSPTPUOUNTMSM RSNSOTOTNSN RQ[P[OZOYPXQXRYR[Q]P^N_ RPYPZQZ
QYPY RQ[Q\P^
 3264 34MXVFUFTGRT RVGUGRT RVGVHRT RVFWGWHRT RPXOYOZP[Q[RZRYQXPX RPYPZQZ
QYPY
 3265 59H]OKOJPJPLNLNJOHPGSFWFZG[I[KZMYNWOSPQQQSSTTT RUFZG RYGZIZKYMXNVO
 RWFXGYIYKXMWNSPRQRSST RPXOYOZP[Q[RZRYQXPX RPYPZQZQYPY
 3266 22MXWFUGTHSJSLTMUMVLVKUJTJ RUGTITJ RTKTLULUKTK
 3267 22MXVIUITHTGUFVFWGWIVKULSM RUGUHVHVGUG RVIVJUL
 3268 72E_\O\N[N[P]P]N\M[MYNWPRXPZN[K[HZGXGVHTISKRPPROTMUKUITGRFPGOIOLPR
QURWTZV[X[YYYX RL[HZ RIZHXHVITJSLR RPPQSTYVZ RK[JZIXIVJTKSMRRO ROLPOQRSV
UYWZXZYY
 3269 52H]TBL_ RYBQ_ RZKZJYJYL[L[JZHYGVFRFOGMIMLNNPPVSWUWXVZ RNLONVRWT R
OGNINKOMUPWRXTXWWYVZS[O[LZKYJWJULULWKWKV
 3270  8G^_BEbFb R_B`BFb
 3271 32JZZBXCUERHPKNOMSMXN\O_Qb RSHQKOONTN\ RZBWDTGRJQLPOOSN\ RNTO]P`Qb

 3272 32JZSBUEVHWLWQVUTYR\O_LaJb RVHVPUUSYQ\ RSBTDUGVP RVHUQTUSXRZP]M`Jb

 3273 39J[TFSGUQTR RTFTR RTFUGSQTR ROIPIXOYO ROIYO ROIOJYNYO RYIXIPOOO R
YIOO RYIYJONOO
 3274  8F_JQ[Q[R RJQJR[R
 3275 16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R
 3276 16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V
 3277 11MWUFTGRM RUGRM RUFVGRM
 3278 22H\PFOGMM RPGMM RPFQGMM RZFYGWM RZGWM RZF[GWM
 3279 30KZSFQGPIPKQMSNUNWMXKXIWGUFSF RSFPIQMUNXKWGSF RUFQGPKSNWMXIUF
 3301 62F^IHJIIJHIIGKFMFOGPHQKQOPRNTLUIV ROHPKPPOR RMFNGOJOPNSLU RLVOY R
KVOZ RIVN[UV R\G[H\H\G[FYFWGVHUJUYW[[W RWHVJVXXZ RYFXGWJWWYY
 3302101E_GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGQHRJRRQUOW RPH
QJQT RNFOGPJPUOW RRISGUFWFYGZH[J\K RYHZJ RWFXGYJZK\K R\KRP RYM[O\R\U[XYZ
V[S[PZJWIWHX RXNYN[P RVNYO[Q\S RTZRZLWKW RZYXZUZRYNWKVIVHXHZI[JZIY
 3303 79F^RHPFNFLGJJINIRJVLYNZQ[T[WZYY[W RLHKJJMJRKVMYPZ RNFMGLIKMKQLUMW
OYRZUZXY[W RUFRHQIPKPLQNTPURUT RQKQLUPUQ RQIQJRLUNVPVRUTSURUPTOR RUFVGXH
ZH RUGVHWH RTGVIXIZH[G
 3304 79E_HLHKIIKGNFRFUGWHYJ[M\Q\U[XYZV[S[PZJWIWHX RKHMGRGUHWIYK[N RTZRZ
LWKW RHKJIMHRHUIWJYL[O\R RZYXZUZRYNWKVIVHXHZI[JZIY RPHMKLMLONSNU RMNMONQ
NR RMKMMOQOSNUMVKVJUJT
 3305 95F^RHPFNFLGJJINIRJVLYNZQ[T[WZYY[W RLHKJJMJRKVMYPZ RNFMGLIKMKQLUMW
OYRZUZXY[W RUFRHQIPKPLQNTPURUT RQKQLUPUQ RQIQJRLUNVPVRUTSURUPTOR RUFVGXH
ZH RUGVHWH RTGVIXIZH[G RUNYK RYKZL\L RXLYMZM RWMXNZN\L
 3306 94F^MNKMJKJIKGNFQFTGXI RKHMGRGUH RJKKIMHRHXIZI[H[GZFYF RSHRIQKQMRO
VSWVWYV\U]S^ RTPWSXVXYW[ RQMSOVQXSYVYYX[V]S^O^L]K\JZJWLTLRKQ RL\K[KWLU R
O^M]L[LWMTMRLQJQIRIS RUPYL RYLZM\M RXMYNZN RWNXOZO\M
 3307 99E_UJTHSGQFNFKGIJHNHRIUJWLYNZQ[T[WZYY[W\T\Q[NYL RKHJJIMIRJUKW RZW
[U[QZNYM RNFLGKIJMJRKVLXNZ RWZYXZUZQYOWM RUFRHPJOLOMPOSQTSTU RPLPMTQTR R
PJPKQMTOUQUSTURVQVOUNS RTOYLZJ R\FZJ RYG]I R\F[GYGZHZJ[I]I\H\F
 3308 92F_RFPGNIMKMMNOPQQSQU RNLNMQQQR RNINKOMQORQRSQUPVNWLWJVIUHSHQIPJQ
IR RRFTHVHXG RQGSH RPGQHSIUIXG RRPYK RYK[N\Q\T[WYYVZR[ RXLZN[Q[UZW RVMWM
YOZRZVYXXYVZ RVZTZRYPYNZM\N^P_R_T^ RSZQZ RR[PZNZ
 3309 83F_PPNPLOKNJLJJKHLGOFQFTGWJYK RLHNGRGTHUI RJJKIMHQHTIVJYK[K\J\H[G
YG RJXKYJZIYIWJVLVNWPYR\T^ RNXOYQ\R] RLVMWNYP\Q]S^V^X]Y\ZZZWYUWRVPVO RYX
YWVRVQ RX]Y[YYXWVTURUPWNYNZOZP
 3310 83F_PPNPLOKNJLJJKHLGOFQFTGWJYK RLHNGRGTHUI RJJKIMHQHTIVJYK[K\J\H[G
YG RJXKYJZIYIWJVLVNWPYR\T^ RNXOYQ\R] RLVMWNYP\Q]S^V^X]Y\ZZZWYUWRVPVO RYX
YWVRVQ RX]Y[YYXWVTURUPWNYNZOZP
 3311 81E_[KZIXGUFRFOGMILKLNMQPWPYN[ RMNMOPUPV RNHMJMMNOPSQVQXPZN[L[JZ R
HVJZ RGYKW RHVHXGYIYJZJXKWIWHV RNONMOKQJTJVKXMYM RUKWM RRJTKULVN RYMPQ R
UOYXZY[Y RTPXXZZ RSPWYY[\X
 3312 73G^ZSYTVTUSUQVOXLYJYH RVQVPYLYK RWTVSVRWPYNZLZJYHXGUFPFMGLHKJKLLN
NQOSOTNV RLKLLOQOR RLHLJMLOOPQPSOUMWJY RMWOWRYUZXZZY RNXOXSZTZ RJYLXMXQZ
T[V[YZZY[W
 3313128BbEQERFSHSJRJOIMGJGHIF RIOGK RHSIRIPGMFKFIGGIFKFMGOIPLPROUNWLYI[
HZGZ RNIOLORNUMW RJZIYHY RKFMHNKNRMVLXKYJXIXF[ RNGPFRFTGVIWLWRVUUWSYQ[PZ
OZ RUIVLVRUV RRZQYPY RRFTHUKUSTWSYRXQXN[ RUHVGXFZF\G]H^J_K R\H]J RZF[G\J
]K_K R_K\M[NZQZT[X][`X R\N[P[T\W^Z R_K]M\O\S]W_Y
 3314 96D`GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGRISLSRRUQWOYL[
KZIZG[ RQIRKRRQUPWOX RMZKYIY RNFPHQKQRPVNYLXJXG[ RRHSGUFWFYGZH[J\K RYHZJ
 RWFXGYJZK\K R\KYMXNWQWTXXZ[]X RYNXPXTYW[Z R\KZMYOYSZW\Y
 3315 72D`PFNGLIKKKMMQMS RLLLMMOMP RLILKNONQMSLTJTISIR RPFQGWIZK[M\P\S[V
ZXXZU[R[OZIWHWGX RPGQHWJYKZL RPFPHQIWKYL[N\P RSZQZKWJW RYYWZTZQYMWJVHVGX
GZH[IZHY
 3316100E`HQHRISKSMRMOLMJJJHLF RLOJK RKSLRLPJMIKIIJGLFOFQGRHSJSU RSWS\R^
P_M_L^L\M[N\M] RQHRJR\Q^ ROFPGQJQU RQWQ\P^O_ RSJXF RXFZI[K\O\R[UYXV[ RWG
ZK[N[O RVHXJZM[P[SZVYX RWYUVSU RQUOVMX RWZUWSVPV RV[TXSW RQWOWMX
 3317 88D`PFNGLIKKKMMQMS RLLLMMOMP RLILKNONQMSLTJTISIR RPFQGWIZK[M\P\S[V
ZX RXZU[R[OZIWHWGX RPGQHWJYKZL RPFPHQIWKYL[N\P RSZQZKWJW RXZTZQYMWJVHVGX
GZH[IZHY RTXVVXV\Z]Z RWWXW[Z RUWVWZ[\[^Y
 3318 96D`GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGQHRJRVQXOZM[K[
IZ RPHQJQVPX RNFOGPJPVOYM[ RGVIZ RFYJW RGVGXFYHYIZIXJWHWGV RRISGUFWFYGZH
[J\K RYHZJ RWFXGYJZK\K R\KRP RTOXYZ[]X RUOYX[Z RVNZX[Y\Y
 3319 83E`\H[G\F]G]I\KZKVISHOHKIIK RYJVHSGOGLH R]I\JZJVGSFOFLGJIIKHNHRIU
JWLYNZQ[U[XZZY\W]T]Q\OZNWNUOSRQSOS RLXNYQZUZYY RIUKWMXPYUYYX[W\V]T RXOWO
SSRS R]Q[OYOWPUSSTQTOSNQNOOMQL
 3320 81F_LNJMIKIIJGMFRFUGYJ[J\I RJHLGRGUHXJ RIKJILHRHUIYK[K\I\G[FZG[H R
UIRLQNQPSTSV RRORPSRSS RRLRNTRTTSVRWPWOVOT RJYKZJ[IZIXJVLVOWSYVZYZ[Y RLW
MWSZUZ RIXJWKWMXQZT[W[ZZ\X
 3321 45G]JHKHLILWJX RKGMHMXPZ RIILFNHNWPYRY RJXKXMYO[RYVV RTHUHVIVYX[[X
 RUGWHWYYZ RSIVFYHXIXXYYZY
 3322100D`GQGRHSJSLRLOKMIJIHKF RKOIK RJSKRKPIMHKHIIGKFNFPGQHRJRRQUOW RPH
QJQT RNFOGPJPUOW RRISGUFWFYG[J\K RYHZJ RWFXGYJZK\K RZKXKWLWNXP[R\T RXO[Q
 RWMXN[P\R\V[XYZW[S[PZJWIWHX RTZRZLWKW RZYXZUZRYNWKVIVHXHZI[JZIY
 3323143BcEQERFSHSJRJOIMGJGHIF RIOGK RHSIRIPGMFKFIGGIFLFNGOHPJPNOQMTKV R
NHOJOONR RLFMGNJNOMSKV RNGPFSFUG RWFTGSISMTPVSWUWWVY RTMTNWSWT RWFUGTITL
UNWQXTXVWXUZS[O[MZKXIWGWFX RNZKWJW RQ[OZLWJVGVFXFZG[HZGY RWFZF\G^J_K R\H
]J RZF[G\J]K_K R]K[KZLZN[P^R_T R[O^Q RZM[N^P_R_W^Y]Z[[X[UZ RYZXZVY R^Y\Z
ZZXYWX
 3324 86F^KHMHOIPJQMQO RQQQUPXM[KZI[ RNZLYKY ROYNYLXI[ RMGPHQIRLRUSWUYWZ
 RIINFPGRISLSO RSQSTTWUXWYYY RQURXTZV[[X RSLTIWFYG[F RVGXHYH RUHVHXI[F R
KSMOQO RSOWOYM RMPWP RKSMQQQ RSQWQYM
 3325 74E_HQHRISKSMRMOLMJJJHLF RLOJK RKSLRLPJMIKIIJGLFOFQGRHSJSORRQTQUSW
TW RQHRJRPQSPUSX ROFPGQJQPPTOVRYUV RSJ[F RYGYZX] RZGZXY[ R[F[VZZY\W^T_P_
M^K\JZKYLZK[
 3326 74F^NIOGQFTFVGWHXJXMWOVPTQ RQQOPNN RVHWIWNVO RTFUGVIVNUPTQ RMUNSOR
QQTQWRYTZVZZY\W^T_P_N^KZJY RXTYVYZX\ RTQWSXUX[W]V^T_ RO^N]LZKY RR_P^O]MZ
LYIYHZH\I]J]
 3401 46J[TMQNOONPMSMVNYO[UX RNVOYPZ RQNOPNSNUOXQZ RRNSOUPUYW[ZX RSNVPVX
XZ RTMUNWOXO RWPXO RWPWXXYYY
 3402 50J[LHMINK RTFQGOINKNXMY RPIOKOXRZ RTFRGQHPKPXRYSZ RMYNYPZQ[TZ RPP
VMWOXRXUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ
 3403 27KXRNTPVOTMRNOPNRNWOYQ[UY RSNUO RPPOROWPYQZ RQOPQPVQXSZ
 3404 47J[QFNINKOLSNVPWRWUVXTZ ROJOKSMVOWP ROHOIPJUMWOXRXUWXTZQ[ RRNNPNX
MY ROPOXRZ RPOPXRYSZ RMYNYPZQ[
 3405 27KXPUVQSMOPNRNWOYQ[UY RUQRN RPPOROWPYQZ RTRROQOPQPVQXSZ
 3406 49LYXFWGUGSFQFPHPMOONP RVHTHRGQG RXFWHVITIRHQHPI RPKQMRNTOVOVP RNP
PP RRPVP RPPPTQ` RSOPOQNQ[ RRPRTQ`
 3407 53J[TMQNOONPMSMVNYO[UX RNWOYPZ RQNOPNSNUOXQZ RRNSOUPUXV[V]U_ RSNVP
VZ RTMUNWOXO RWPXO RWPW\V^U_S`P`N_M^M]N]N^
 3408 50J[LHMINK RTFQGOINKNXMY RPIOKOYPZ RTFRGQHPKPXQYRY RMYOZP[SX RPPVM
WOXSXWWZV\T^Q` RUNVOWR RTNVQWTWWV[T^
 3409 39MWRFQGQHRISHSGRF RQGSH RQHSG ROOPOQPQYS[VX RPNRORXTZ RNPQMRNTO R
SPTO RSPSXTYUY
 3410 45MWRFQGQHRISHSGRF RQGSH RQHSG ROOPOQPQ[P^O_M` RPNROR[Q] RNPQMRNTO
 RSPTO RSPS[R]P_M` RS[T]U^
 3411 63KYNHOIPK RUFSGQIPKPMOONP RPPPXOY RRIQKQM RQOPOQMQXSZ RUFSHRKRO R
RPRXSYTY ROYQZR[UX RRLVIWJWLUNSO RUJVKVLUN RROWOWP RNPPP RRPWP
 3412 29MWOHPIQK RWFTGRIQKQXPY RSIRKRYTZ RWFUGTHSKSXTYUY RPYRZS[VX
 3413 74E_GOHOIPIXHYJ[ RHNJPJXIYJZKYJX RFPIMKOKXLYJ[ RNNPOQQQXPYR[ RPNQO
RQRXQYRZSYRX RKPNNPMRNSPSXTYR[ RVNWOYPYY[[^X RWNZPZX\Z RSPVNXMYN[O\O R[P
\O R[P[X\Y]Y
 3414 49I[KOLOMPMXLYN[ RLNNPNXMYNZOYNX RJPMMOOOXPYN[ RRNSOUPUYW[ZX RSNVP
VXXZ ROPRNTMUNWOXO RWPXO RWPWXXYYY
 3415 41J[NPNXMY ROPOXRZ RQOPPPXRYSZ RMYNYPZQ[TZ RNPQOVMWOXRXUWXVYTZ RUN
VOWQ RTNVPWSWUVXTZ
 3416 57J[OJMLMNNQNXLZ RNYO` RNMNNOQO[ RNKNLONPQPXQXSYTZ RPYO` RSZQY RTZ
R[PY RNYLZ RPPVMWOXRXUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ
 3417 43J[TMQNOONPMSMVNYO[UX RNWOYPZ RQNOPNSNUOXQZ RRNSOUPUXV` RSNVPV[ R
TMUNWOXO RWPXO RWPWXV`
 3418 32KYNOOOPPPXOY RONQPQYSZ RMPPMRORXSYTY ROYQZR[UX RTNUPWOVMRO RUNVO

 3419 42LWXFWGUGSFQFPHPMOONP RVHTHRGQG RXFWHVITIRHQHPI RPKRP RPPPTQ` RQO
POQNQ[ RRPRTQ` RNPPP
 3420 37LXSIRLQNPONP RSISOVOVP RNPQP RSPVP RQPQXPY RROQORMRXTZ RSPSXTYUY
 RPYRZS[VX
 3421 47I[KOLOMPMXLY RLNNPNXPZ RJPMMOOOXQYRZ RLYMYOZP[RZUX RVMTOUPUYW[ZX
 RVPWOVNUOVPVXXZ RVMXOWPWXXYYY
 3422 47J[OKMMMONRNXMY RNNNOOROXRZ RNLNMOOPRPXRYSZ RMYNYPZQ[TZ RPPVMWOXR
XUWXVYTZ RUNVOWQ RTNVPWSWUVXTZ
 3423 72F_KKIMIOJRJXIYK[ RJNJOKRKXJYKZLYKX RJLJMKOLRLXMYK[ RONQORQRXQY R
QNROSQSXVZ RLPONQMSNTPTXVYWZ RQYRYTZU[XZ RTPZM[O\R\T[XZYXZ RYNZO[Q RXNZP
[S[UZXXZ
 3424 44KZOOPOQPQXPXNYM[M]N_P`S`V_V^U^U_ RPNRPRXUZ RNPQMSOSXUYVZ RXYT[SZ
QYOYM[ RUNVPXOWMSO RVNWO
 3425 47J[OKMMMONRNXMY RNNNOOROYQZ RNLNMOOPRPXQYRY RMYOZP[SX RPPVMWOXSXW
WZV\T^Q` RUNVOWR RTNVQWTWWV[T^
 3426 43KYNPSMUNVPVRUTQV RSNUO RRNTOUQURTTSU RSUUWVYV]U_S`Q`O_N]N[OYQXWV
 RRVTWUY RQVTXUZU]T_S`
 3427 61JZRMPNMPMRNU RNPNROT RPNOOORPT RPNROTOVNWMWKVJTJ RQNSN RRMTNVN R
NUVRWUWWVYR[ RUSVUVXUY RTSUUUXTZ RTZRYOYL[ RSZQZ RR[PZNZL[
 3428 78J[VFUGSGQFOFNHNMMOLP RTHRHPGOG RVFUHTIRIPHOHNI RNKPP RNPNTO` ROO
NOONO[ RPPPTO` RLPNP RPPUMWNXPXRWTSV RUNWO RTNVOWQWRVTUU RUUWVXXX[W]U_R`
 RUVWW RSVTVVWWYW\V^
 3429 62J[PIOLNNMOKP RPIPXQYO[ ROONOONOXNYOZPYOX RKPNPNXMYO[ RPPUMWNXPXR
WTSV RUNWO RTNVOWQWRVTUU RUUWVXXX[W]U_R` RUVWW RSVTVVWWYW\V^
 3501 60G]LINGPFRFSGZW[X]X RQGRHYXZZ[YYX RNGPGQHXXYZZ[[[]X RLMMLOKPKQL R
PLPM RMLOLPN RG[IYKXNXPY RJYNYOZ RG[JZMZN[PY RRJLX RNSVS
 3502110F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP
 RMKMTLVKW RRIQJPLPU RQKQS RRIRRQTPU RRIXFZG[I[KYMUO RXGZIZK RVGXHYIYLWN
 RWNZP[R[X RYPZRZW RWNXOYQYX RJ[MYPXTXWY RLZOYTYVZ RJ[NZSZU[WYYX[X RUOUX
 RURYR RUUYU
 3503 69E]NGLHJJILHOHSIVJXMZP[S[VZXYZW[U RJKINISKWNYQZTZWY RNGLIKKJNJRKU
NXQYTYWXYW[U RPJPV RQJQT RRIRSQUPV RPJRIUFWGYGZF RTGVHXH RSHUIWIYHZF RWI
WX
 3504 72G^IFWFYGZIZX RKGWGYIYW RIFJGLHWHXIXX ROKNLMNMOKOJPJRKQMQMV RNMNT
 RKPNP ROKOSNUMV RI[LYOXSXVY RKZNYSYUZ RI[MZRZT[VYXXZX RRHRX RRMTNVNXM R
RSTRVRXS
 3505 94G]IHKFMFOGQF RLGNG RIHKGMHOHQF RNKMLLNLOJOIPIRJQLQLW RMMMU RJPMP
 RNKNTMVLW RQMRJSHTGVFXF[G RTHVGXGZH RRJSIUHWHYI[G RQURRSPTOVOXP RTPVPWQ
 RRRSQUQVRXP RK[NYRXWX[Y RMZPYWYZZ RK[OZVZY[[Y RQMQX
 3506 91F]JHLFOFQGSF RMGPG RJHLGNHQHSF RPKOLNNNOLOKPKRLQNQNV ROMOT RLPOP
 RPKPSOUNV RSJSYRZQZMXKXIYG[ RTJTX RTPXP RPZOZMYJY RUIUOXO RXQUQUWTYP[N[
LZJZG[ RSJUIXFZG\G]F RWGYH[H RVHXIZI\H]F RXIXW
 3507 87E^NGLHJJILHOHRIUJWLYNZQ[U[XZZX[V[SZQYPWOUO RJKINISJV RNGLIKKJNJS
KVLXNZ RYXZWZSYQ RU[WZXYYWYSXQWPUO RPJPW RQJQU RRIRTQVPW RPJRIUFWGYGZF R
TGVHXH RSHUIWIYHZF RYHUOU[ RUSYS RUVYV
 3508112F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP
 RMKMTLVKW RJ[MYPXSXUY RLZOYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU R
RITGVFXFZG RWGXGYH RTGVGXIZG RUOWNYLZM[P[TZXX[ RXMYNZPZUYX RWNXNYPYUX[ R
UOUY RURYR RUUYU
 3509 67I\LHNFQFTGVF ROGSG RLHNGQHTHVF RSKRLQNQOOONPNROQQQQV RRMRT ROPRP
 RSKSSRUQV RYHWJVMVXUZSZOXMXKYI[ RWKWW RRZQZOYLY RYHXJXVWXUZS[P[NZKZI[
 3510 65H\LHNFQFTGVF ROGSG RLHNGQHTHVF RSKRLQNQOOONPNROQQQQV RRMRT ROPRP
 RSKSSRUQV RYHWJVMVXUZ RWKWW RYHXJXVWXUZR[O[LZJXJVKULUMVLWKW RJVMV
 3511115F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP
 RMKMTLVKW RJ[MYPXSXUY RLZNYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU R
RITGVFXFZG RWGXGYH RTGVGXIZG RUOXLYM[N RWMYN[N R[NYQWSUU RWSYTZX[Z\Z RYV
ZZ RWSXTYZZ[[[\Z RUOUY
 3512 85G]IHKFNFPGRF RLGOG RIHKGMHPHRF RNKMLLNLOJOIPIRJQLQLW RMMMU RJPMP
 RNKNTMVLW RK[NYRXWX[Y RMZPYWYZZ RK[OZVZY[[Y RSIRJQLQU RRKRS RSISRRTQU R
SIUGWFYF[G RXGYGZH RUGWGYI[G RWGWX
 3513107D`LJKKJMJOHOGPGRHQJQJU RKLKS RHPKP RLJLRKTJU RE[GYIXKXMYNYOX RHY
KYMZ RE[GZJZL[M[NZOX RLJPFTJTWUYVY RPGSJSXRYSZTYSX RPPSP RNHOHRKROOO ROQ
RQRXQYS[VYWX RTJXF\J\W]Y^Y RXG[J[X]Z RXP[P RVHWHZKZOWO RWQZQZY\[^Y ROHOX
 RWHWX
 3514 84E^GIIGKFMFOGQJVUXXYY RMGOIPKVWYZ RIGKGMHOKTVVYWZY[ RVHXIZI\H]F R
WGYH[H RVHXFZG\G]F RKOIOHPHRIQKQ RIPKP RG[IYKXNXPY RJYMYOZ RG[JZMZN[PY R
KGKX RYIY[ RRLSMUNWNYM RKTMSQSST
 3515 79E_NFLGJIIKHNHRIUJWLYNZQ[S[VZXYZW[U\R\N[KZIXGVFUGRIOJ RJJIMISJV R
NFLHKJJMJSKVLXNZ RZV[S[MYIXH RVZXXYVZSZMYKWHUG ROJOW RPJPU RQJQTPVOW RUG
UZ RUMWNXNZM RUSWRXRZS
 3516 70H^KFLGMIMOKOJPJRKQMQMYJ[MZMbO` RMHNJN` RKPNP RKFMGNHOJO` ROKRIVF
ZJZX RVGYJYX RTHUHXKXY RRXUXXY RSYUYWZ RRZTZV[XYZX RRIR_ RRMTNVNXM RRSTR
VRXS
 3517 99E_NFLGJIIKHNHRIUJWLYNZP[T[VZXYZW[U\R\N[KZIXGVFUGRIOJ RJJIMISJV R
NFLHKJJMJSKVLXNZ RZV[S[MYIXH RVZXXYVZSZMYKWHUG ROJOW RPJPU RQJQTPVOW RUG
UZ RUMWNXNZM RUSWRXRZS RP[QZRZT[X`Za[a RT\V_XaYa RRZS[VaXbZb[a
 3518108F^HHJFMFOGQF RKGNG RHHJGLHOHQF RMKLLKNKOIOHPHRIQKQKW RLMLU RIPLP
 RMKMTLVKW RJ[MYPXRXUY RLZNYRYTZ RJ[NZQZS[UY RRIQJPLPU RQKQS RRIRRQTPU R
RIUGWFYGZIZLYNXOTQRR RWGXGYIYMXN RUGWHXJXMWOTQ RTQVRWSZX[Y\Y RWTYX[Z RTQ
VSXYZ[\Y
 3519 94G^UITHRGOF RVHTG RWGSFOFLGKHJJKLLMONWNYOZPZRYU RKKLLOMXMZN[O[QZS
 RKHKJLKOLYL[M\O\QYUU[ RIOJPLQUQVRVSUU RJQLRTRUS RIOIPJRLSSSUTUU RI[LYPX
SXVY RKZNYRYUZ RI[MZRZU[ RWGUISL RRNPQ ROSMUKVJVJUKV
 3520 71E]JJILHOHSIVKYMZP[S[VZXYZW[U RISJVLXNYQZTZWY RJJIMIQJTLWNXQYTYWX
YW[U RHIIGKFOFUGYG[F RPGTHXH RHIIHKGNGTIWIYH[F RSIRJPKPV RQKQT RRJRSQUPV
 RWIWX
 3521 89F^HHJFLFOGQF RKGNG RHHJGMHOHQF RKJJLIOISJVKXMZP[S[VZXYZ[\Y RJSKV
NYQZTZ RKJJNJQKTLVNXQYUYXX RUIQJPLPV RQKQT RRJRSQUPV RUIWHYFZG\HZIZW[Y\Y
 RYIZHYGXHYIYX[Z RWHXIXX RUIUY RUNXN RURXR
 3522 72G^JFKGLILOJOIPIRJQLQLXJY RLHMJMX RJPMP RNYQYSZ RJFLGMHNJNXRXUY R
JYMYPZR[UYXXZX RRJUIWHYFZG\HZIZX RYIZHYGXHYIYW RWHXIXX RRJRX RRMTNVNXM R
RSTRVRXS
 3523 95E`HFIGJIJOHOGPGRHQJQJXHY RJHKJKX RHPKP RLYNYPZ RHFJGKHLJLXOXQY R
HYKYNZO[QYTXVYW[YY\X ROHRFTHTXWXYY RRGSHSX ROHQHRIRXQY RWYXZ RWHZF\H\X R
ZG[H[X RWHYHZIZXYY ROHOX RWHWX RONRN RORRR RWNZN RWRZR
 3524 65G]HIJGLFNFOGWYXZZZ RMGNHVYWZ RJGLGMHUZV[X[ZZ\X RWFYG[G\F RWGXHZH
 RVHWIYI[H\F RH[IYKXMXNY RJYLYMZ RH[IZKZM[ RWFSO RQRM[ RLPPP RSPXP
 3525 86G^JFKGLILOJOIPIRJQLQLXJY RLHMJMX RJPMP RNYQYSZ RJFLGMHNJNXRXUY R
JYMYPZR[UYXX RRJUIWHYFZG\HZIZ^Y`WbUaQ`L` RYIZHYGXHYIYY RWHXIXXZ[ RXaV`S`
 RY`V_P_L` RRJRX RRMTNVNXM RRSTRVRXS
 3526 57H\XGWIROOSMWJ[ RVKNV RZFWJUNRRMXLZ RJHLFOGUGZF RKGOHSHWG RJHNIRI
VHXG RLZNYRXVXZY RMZQYUYYZ RJ[OZUZX[ZY RMPQP RTPXP
 3601 53J[PRNTMVMXNZP[RYUX RMVNXOYQZ RNTNVOXQYRY RNPPPSOUNVMXOWPWXXYYY R
ONNOQO RTOWOVNVYWZ RMOOMPNROUPUYW[YY RMORT
 3602 44I[LHMJMXKY RNJMHNGNXQZ RLHOFOXQYRZ RKYMYOZP[RZUYWY ROPROTNUMVNXO
YOWPWY RTNVOVX RROSOUPUY
 3603 35JXNONXLYMYOZP[ ROOOYQZ RPOPXRYSYQZP[ RNORNTMUNWOXO RSNTOVO RPORN
TPVPXO
 3604 41IZRMPNMOMXKY RNONXQZ RRMOOOXQYRZ RKYMYOZP[RZUYWY RMHPFQIWOWY RPI
NHOGPIVOVX RMHUPUY
 3605 32JXNONXLYMYOZP[ ROOOYQZ RPOPXRYSYQZP[ RNORNTMWQURPU RSNVQ RPORNUR

 3606 41JWNHNXLYMYOZP[ ROHOYQZ RPHPXRYSYQZP[ RNHQGSFTGVHWH RRGSHUH RPHQG
SIUIWH RKMNM RPMTM
 3607 56I[MOMXKYLYNZO[PZRYUX RNPNYPZ ROOOXQYRY RMOOORNTMUNWOYOWPW\V_TaRb
QaO`M` RSNVPV\ RSaQ`P` RRNSOUPUZV]V_ RTaS`Q_O_M`
 3608 47I[LHMJMXKYLYNZO[ RNJMHNGNYPZ RLHOFOXQYO[ ROPROTNUMVNXOYOWPWYU[T]
 RTNVOVYU[ RROSOUPUYT]T`UbVbT`
 3609 35MWRFPHRITHRF RRGQHSHRG RRMQNOOQPQYS[UY RRPSORNQORPRYSZ RRMSNUOSP
SXTYUY
 3610 39MWRFPHRITHRF RRGQHSHRG RRMQNOOQPQYS[T] RRPSORNQORPRYS[ RRMSNUOSP
SYT]T`RbPbPaRb
 3611 50IZLHMJMXKYLYNZO[ RNJMHNGNYPZ RLHOFOXQYO[ ROPRNTMVPSROU RSNUP RRN
TQ RSRTSVXWYXY RSSTTUYVZ RRSSTTYV[XY
 3612 22MWPHQJQXOYPYRZS[ RRJQHRGRYTZ RPHSFSXUYVYTZS[
 3613 67E_GOHOIPIXGYHYJZK[ RINJOJYLZ RGOIMKOKXMYK[ RKPNOPNQMSOSXUYS[ RPN
RORYTZ RNOOOQPQXPYRZS[ RSPVOXNYMZN\O]O[P[X\Y]Y RXNZOZY[Z RVOWOYPYY[[]Y
 3614 45I[KOLOMPMXKYLYNZO[ RMNNONYPZ RKOMMOOOXQYO[ ROPROTNUMVNXOYOWPWXXY
YY RTNVOVYWZ RROSOUPUYW[YY
 3615 40I[MOMXKY RNPNXQZ ROOOXQYRZ RKYMYOZP[RZUYWY RMOOORNTMUNWOYOWPWY R
SNVPVX RRNSOUPUY
 3616 54I[LMMOMXKYMYMb RMNNONaO`N^ RNYOYQZ RLMNNOOOXQYRZ ROZP[RZUYWY ROZ
O^P`Mb ROPROTNUMVNXOYOWPWY RTNVOVX RROSOUPUY
 3617 44I[MOMXKY RNPNYPZ ROOOXQYRY RKYLYNZO[PZRYUX RMOOORNTMUNWOYOWPWb R
SNVPVaU`V^ RRNSOUPU^T`Wb
 3618 38JXLOMONPNXLYMYOZP[ RMNOOOYQZ RLONMPOPXRYSYQZP[ RPOTMUNWOXO RSNTO
VO RRNTPVPXO
 3619 59JZMOMSOTUTWUWY RNONS RVUVY RPNOOOSQT RSTUUUYTZ RMOPNRMTNVNWM RQN
SN RPNROTOVN RWYTZR[PZNZL[ RSZQZ RTZRYOYL[ RWMVOTROWL[
 3620 28MWPHQJQXOYPYRZS[ RRJQHRGRYTZ RPHSFSXUYVYTZS[ RNMQM RSMVM
 3621 47I[KOLOMPMXKY RLNNONYPZ RKOMMOOOXQYRY RKYLYNZO[PZRYUX RUMVNXOYOWP
WXXYYY RTNVOVYWZ RUMSOUPUYW[YY
 3622 36I[LMMOMXP[RYUXWX RMNNONXQZ RLMNNOOOWPXRY RUMVNXOYOWPWX RTNVOVW R
UMSOUPUX
 3623 57E_HMIOIXL[NYQX RINJOJXMZ RHMJNKOKWLXNY RQMOOQPQXT[VYYX[X RPNRORX
UZ RQMRNTOSPSWTXVY RYMZN\O]O[P[X RXNZOZW RYMWOYPYX
 3624 59H[KOLONPOQSYTZV[XY RMNOOTYVZ RKOMMONPOTWUXWYXY RRSUMVNXNYM RUNVO
WO RTOVPXOYM RQUN[MZKZJ[ RNZMYLY ROYMXKYJ[ RMTPT RSTVT
 3625 60I[KOLOMPMXKY RLNNONYPZ RKOMMOOOXQYRY RKYLYNZO[PZRYUX RUMVNXOYOWP
W\V_TaRbQaO`M` RTNVOV\ RSaQ`P` RUMSOUPUZV]V_ RTaS`Q_O_M`
 3626 38I[XML[ RLONPQPTOXM RMNOOSO RLONMPNTNXM RL[PYSXVXXY RQYUYWZ RL[PZ
TZV[XY RNTVT
 3697  1RR
 3698  1NV
 3699  1JZ
 3700 42H\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZH
XIXY RJYLYNZO[QZVYXY
 3701 27H\OHPIQKQXOY RQIPHQGRIRYTZ ROHRFSHSXUYVY ROYPYRZS[TZVY
 3702 48H\LHNHPGQFSGVHXH RPHRG RLHNIPIRHSG RVHVP RWIWO RXHXPQPNQLSKVK[ R
K[OYSXVXZY RNZQYVYYZ RK[PZUZX[ZY
 3703 57H\LHMHOGPFRGVHXH ROHQG RLHNIPIRG RVHVO RWIWN RXHXOVOSPQQ RQPSQVR
XRXY RWSWX RVRVY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY
 3704 41H\UFKPKUTU RVUZU[V[TZU RLPLT RMNMU RTGTXRY RUJVHUGUYWZ RUFWHVJVX
XYYY RRYSYUZV[WZYY
 3705 53H\LFLO RLFXF RMGVG RLHUHWGXF RVLUMSNOOLO RSNTNVOVY RUMWNWX RVLWM
YNZNXOXY RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY
 3706 59H\LHLXJY RMIMXPZ RNHNXPYQZ RLHNHRGTFUGWHXH RSGUH RRGTIVIXH RNPOP
SOUNVM RSOTOVPVY RUNWPWX RVMWNYOZOXPXY RJYLYNZO[QZVYXY
 3707 38H\KHMFPGUGZF RLGOHTHWG RKHOIRIVHZF RZFYHWKSOQRPUPXQ[ RRQQTQWRZ R
UMSPRSRVSYQ[
 3708 71H\LILO RMJMN RNINO RLINISHUGVF RSHTHVIVO RUGWHWN RVFWGYHZHXIXO R
LONOVRXR RXOVONRLR RLRLXJY RMSMXPZ RNRNXPYQZ RVRVY RWSWX RXRXY RJYLYNZO[
QZVYXY
 3709 60H\LHLQJR RMIMROS RNHNQPRQR RLHNHSGUF RSGTHVIVY RTGWIWX RUFVGXHZH
XIXY RJRKRMSNTOSQRUQVQ RKYMXOXQYRZ ROYQZ RKYMYOZP[RZVYXY
 3710 11LXRXPZR[TZRX RRYQZSZRY
 3711 14LXR^R\PZRXSZS\R^P_ RRYQZR[RY
 3712 22LXRMPORPTORM RRNQOSORN RRXPZR[TZRX RRYQZSZRY
 3713 25LXRMPORPTORM RRNQOSORN RR^R\PZRXSZS\R^P_ RRYQZR[RY
 3714 30LXRFQGOHQIRT RRISHRGQHRIRT RRFSGUHSIRT RRXPZR[TZRX RRYQZSZRY
 3715 51I[LJMHNGQFSFVGWHXJXLWNUPSQ RMJNH RVHWIWMVN RLJNKNIOGQF RSFUGVIVM
UOSQ RRQRTSQQQRT RRXPZR[TZRX RRYQZSZRY
 3716 14LXTFRGQIQKRMTKRIRG RRJRLSKRJ
 3717 14LXRLRJPHRFSHSJRLPM RRGQHRIRG
 3718 62E_YNZO[O\N RXOYP[P RXPYQZQ[P\N RYNST RRUL[HVNP ROOSKOFJLPRTXVZX[
Z[[Z\X RLZIV RRKOG RKLPQTWVYXZ[Z RMZIU RRLNG RKKQQUWVXXY[Y\X
 3719 60H\PBP_ RTBT_ RTFVGWIWKYJXHWGTFPFMGKIKLLNOPURWSXUXXWZ RXJWH RLLMN
OOUQWRXT RMYLW RMGLILKMMONUPXRYTYWXYWZT[P[MZLYKWMVMXNZP[
 3720  8G^[BIbJb R[B\BJb
 3721 27KYUBSDQGOKNPNTOYQ]S`Ub RQHPKOOOUPYQ\ RSDRFQIPOPUQ[R^S`
 3722 27KYOBQDSGUKVPVTUYS]Q`Ob RSHTKUOUUTYS\ RQDRFSITOTUS[R^Q`
 3723 39JZRFQGSQRR RRFRR RRFSGQQRR RMINIVOWO RMIWO RMIMJWNWO RWIVINOMO R
WIMO RWIWJMNMO
 3724  8F_JQ[Q[R RJQJR[R
 3725 16F_RIRZSZ RRISISZ RJQ[Q[R RJQJR[R
 3726 16F_JM[M[N RJMJN[N RJU[U[V RJUJV[V
 3727 11NWSFRGRM RSGRM RSFTGRM
 3728 22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM
 3729 30KYQFOGNINKOMQNSNUMVKVIUGSFQF RQFNIOMSNVKUGQF RSFOGNKQNUMVISF
 3801 52E_NHLIJKIMHPHSIUKV RJLIOISJU RNHLJKLJOJRKVKXJZH[ RVHXHXYVY RYHYY
 RZGZZ RHFKGQHVHZG\F RJPXP RH[KZQYVYZZ\[
 3802 65E_LGLZ RMGMZ RPFNGNZP[ RHJJHLGPFUFXGZIZKYM RXHYIYKXM RUFWGXIXKWL
 RQUOTNRNPONPMSLVLYM[O\Q\T[WYYWZT[P[LZJYHW RZO[Q[UZW RVLYNZQZUYXWZ
 3803 60E_\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\[ R[HZMZT[Y RZK
YJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS
 3804 46E_KGKZ RLGLZ RNFMGMZN[ RHKIIKGNFSFVGXHZJ[L\O\R[UZWXYVZS[N[KZIXHV
 RZK[N[SZV RVGXIYKZNZSYVXXVZ
 3805 86E_\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[Y\[ R[HZMZT[Y RZK
YJ RZMXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RYWZV RVZXXYVZS RJPKONOUQXQZP RPP
RQURWRYQ RMORRUSWSYRZP RZMYLXLWMXNYM
 3806 69E_JHJZ RMGKHKY ROFMGLILYNY RHJJHLGOFSFVGXHYI\F R\F[HZLZO[S\U RZI
YK RVGXIYLZO RLPMOOOTPWPYO RQPTQVQXP RNOTRVRXQYOYLXKWKVLWMXL RH[JZNYSYYZ
\[
 3807 90E_\F[HZJXHVGSFQFNGLHJJILHOHRIUJWLYNZQ[T[VZXYYXZV[Y\[ R[HZMZT[Y R
ZKYJ RZNYKXIVG RJKINISJV RNGLIKKJNJSKVLXNZ RXXYVYR RVZWYXVXQ RKSLRMSLTKT
JS RJPKNMMOMRNUPWQ RKOMNONROTP RJPLOOOUQYQZP
 3808 50E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\F RLPMNOLRKVKYL[N\Q\T[UYV RZN
[P[SZU RVKXLYMZOZSYVYXZZ\[ RH[LZPZU[
 3809 23E_QIQY RRJRX RSISY RHFLHPITIXH\F RH[KZOYUYYZ\[
 3810 42E_TIVIVXUZS[ RWIWXVY RXHXY RHFLHPITIXH\F RIOHQHUIXKZN[S[VZXYZW\T
 RIUJXKY RHSJUKXLZN[
 3811 70E_JGJZH[ RKHKZ RNHLHLZ RHFJGNHSHYG\F RLPMNOLRKUKXLYMYOXPSRQSPTPU
QVRUQT RWLXMXOWP RUKWMWOVPSR RSRVRYSZUZWYX RWSYUYW RSRVSXUYXZZ[[\[ RH[LZ
PZU[
 3812 45E_JGJZ RKHKY RNHLHLYNY R\KZNYPXSXUYW[X RZOYRYUZW R\K[MZQZT[X\[ R
HFJGNHSHYG\F RH[JZNYSYYZ\[
 3813 68E_QIQY RRJRX RSISY RNYLWJVIUHRHMIJKHMGPFTFWGYH[J\M\R[UZVXWVY RJU
IRIMJJ RLWKUJRJLKIMG RZJ[M[RZU RWGYIZLZRYUXW RHFLHPITIXH\F RH[KZOYUYYZ\[
 3814 48E_JHJZH[ RLHKIKZ ROFMGLILZ RHJJHLGOFSFVGXHZJ[L\O\S[UYV RZK[N[RZU
 RVGXIYKZNZRYVYXZZ[[\[ RH[LZPZU[
 3815 54E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\R\O[LZJXHVGSFQF RJKINISJV R
NGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG
 3816 51E_JIJZ RMHKJKY RQFOGMILKLYNY RHKJINGQFTFWGYH[J\M\O[RYTVURUOTMRLO
 RZJ[L[PZR RWGYIZLZPYSVU RH[JZNYSYYZ\[
 3817 74E_QFNGLHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\R\O[LZJXHVGSFQF RJKINISJV R
NGLIKKJNJSKVLXNZ RZV[S[NZK RVZXXYVZSZNYKXIVG RJSKUNVTW[W\X\Z[[[Z\Y RPWRW
 RKUNWQXSXTW
 3818 69E_JIJZH[ RKIKZ RLHLZ RHKJILHNGQFUFYG[I\K\N[PZQ RYHZI[K[NZP RUFWG
YIZKZOYQ RXRUSRSPRPPROUOXPZR\U\W[XZX RXQYR[V[WZT RTOVPXRYTZX[Z\[ RH[LZPZ
U[
 3819 94E_TFZG\F[H[JYHWGTFPFMGJJIMIOJRLTOURUTTUSVQVP R[GZH[J RJPKRLSOTRT
TS RKIJKJNKPMRPSRSTRVPWOXO RLQMQNPPNRMUMWNYPZRZUYXWZ RPMRLULXMZO[R[UZW R
IWJYIZ RNPNOOMPLRKUKXL[O\R\T[WYYWZT[P[MZKYIWIYH[JZP[
 3820 66E_QHMHKIJJILHOHSIVJXKYMZP[S[VZXYZW[U\R\N[KYIWH RUHTITKULVKUJ RIS
JVLXNYQZTZWY RJJINIQJTLWNXQYTYWXYW[T\R RHFKI RKHLG RIGJGKFMGQHWHZG\F
 3821 51E_LHJJILHOHRIUJWLYNZQ[U[XZZY RKJJLIOISJV RKILJLKKMJPJSKVLXNZ RVH
XHXXWZU[ RYHYXXY RZGZY\[ RHFKGQHVHZG\F
 3822 31E_HFR[ RIGJHQWRY RJGKHRWSX R\FR[ RWNUS RYLUQTTTV RHFJGOHUHZG\F
 3823 67E_LHJJILHOHRIUJWLYNZQ[S[VZXYZW[U\R\O[LZJXH RJLIOIRJUKW RJJKKKLJO
JRKVLXNZ RYWZU[R[OZL RVZXXYVZRZOYLYKZJ RQIQ[ RRJRZ RSIS[ RHFLHPITIXH\F
 3824 41E_HFXYYZ RIGKHZZ RLH\[ R\FSP RQRJZ RPSMULW RQRMTLUKWKY RHFLHPITI
XH\F RH[JZNYSYYZ\[
 3825 47E_XHXZ RYHYY RZGZY RKHIJHMHPISKUMVPWSWVVXU RLUOVUV RHPIRKTNUTUVV
 RHFLHPITIXH\F RHWJYLZP[T[XZ\X
 3826 73E_HFIGKHNHSFVFYGZIZKYM RXGYIYKXM RVFWGXIXL RXNTOROPNPLRKTKXL RTK
VLWMVNTO RYM[O\R\T[WYYWZT[P[MZKYIWHTHRIOJNLMNMPNPPOQNPOO RXMZO[Q[UZW RXN
YOZQZUYXWZ
 3901 42J[PQMTMXP[TY RNTNXPZ ROROWRZ RRSMNNMONNO RONSNUMWOWXXY RUNVOVXUY
VZWYVX RSNUPUXTYV[XY
 3902 31IZNHLFMJMXP[UYWX RNHNXPZ RNHPFOJOWRZ ROOTMWPWX RTNVPVX RRNUQUY
 3903 23KWNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMVOTPRN RSNUO
 3904 32JZRMMPMXP[RZUYWY RNPNXPZ ROOOWRZ RPIPFQIWPWY RPIVPVX RPIMIPJUPUY

 3905 25KXNPNYP[RY ROPOYPZ RPOPXQYRY RNPTMWQPU RSNVQ RRNUR
 3906 32KWOIOXNYP[ RPIPXOYPZQYPX RQHQXRYP[ ROIUFWHUISG RTGVH RLMOM RQMUM

 3907 41J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW]V_U`SaQaO`MaObQa RTNVPV]U_
 RPaNa RRNUQU^T`Sa
 3908 42I[NHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROORNTMWPWYT]T`UbVbT`
 RTNVPVYU[ RRNUQUZT]
 3909 37MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQXPYR[ RRPSORNQORPRXQYRZSYRX RRM
TOSPSXTYR[
 3910 37MWRFPHRJTHRF RRGQHRISHRG RRMPOQPQYT] RRPSORNQORPRYS[ RRMTOSPSZT]
T`RbPaPbRb
 3911 51IZNHLFMJMXLYN[ RNHNXMYNZOYNX RNHPFOJOXPYN[ ROPRNTMVPSROU RSNUP R
RNTQ RRSSTTYV[XY RSSTUUYVZ RSRTSVXWYXY
 3912 21MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[
 3913 66E_GOHOIPIXHYJ[ RINJOJXIYJZKYJX RGOIMKOKXLYJ[ RKONNPMSOSXTYR[ RPN
RORXQYRZSYRX RNNQPQXPYR[ RSOVNXM[O[X\YZ[ RXNZOZXYYZZ[YZX RVNYPYXXYZ[
 3914 44I[KOLOMPMXLYN[ RMNNONXMYNZOYNX RKOMMOOOXPYN[ ROORNTMWOWXXYV[ RTN
VOVXUYVZWYVX RRNUPUXTYV[
 3915 28JZMPMXP[UYWX RNPNXPZ ROOOWRZ RMPOOTMWPWX RTNVPVX RRNUQUY
 3916 47IZLMMOMXKYMYM_LbN` RNON` RLMNNOOOXQYRZ RNYOYQZ ROZP[UYWX ROZO_Pb
N` ROORNTMWPWX RTNVPVX RRNUQUY
 3917 31J[MPMXP[UY RNPNXPZ ROOOWRZ RMPOOTMWPW_XbV` RTNVPV` RRNUQU_TbV`
 3918 31KXMONOOPOXNYP[ RONPOPXOYPZQYPX RMOOMQOQXRYP[ RQOUMWOUPSN RTNVO
 3919 41JZMPMSOUURWTWX RNPNSOT ROOOSPT RUSVTVX RTSUTUY RMPSMVNTOQN RRNUN
 RWXQ[MYOXSZ ROYQZ
 3920 27MWRHPFQJQXPYR[ RRHRXQYRZSYRX RRHTFSJSXTYR[ RNMQM RSMVM
 3921 40I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPWXXYYY RVPWOVNUOVPVY
WZ RVMTOUPUYW[YY
 3922 36I[LMMOMXQ[SYWW RMNNONXQZ RLMNNOOOWRYSY RVMXOWPWW RVPWOVNUOVPVW R
VMTOUPUX
 3923 59E_HMIOIXM[OYQX RINJOJXMZ RHMJNKOKWNYOY RRMPOQPQXU[WY[W RRPSORNQO
RPRXUZ RRMTOSPSWVYWY RZM\O[P[W RZP[OZNYOZPZW RZMXOYPYX
 3924 39I[LONPUZV[XY RMNOOUYWZ RLONMONVXXY RXMVMVOXOXMVOSS RQUNYL[N[NYLY
L[ RNTQT RSTVT
 3925 49I[KOLOMPMYP[UY RMNNONYPZ RKOMMOOOXRZ RVMXOWPW]V_U`SaQaO`MaObQa R
VPWOVNUOVPV^U_ RPaNa RVMTOUPU^T`Sa
 3926 43L[RNOPOORNTMWOWSRU RTNVOVS RRNUPUSTT RRUWWW]V_U`SaQaO`MaObQa RVW
V^U_ RPaNa RTVUWU^T`Sa

SHAR_EOF
if test 28235 -ne "`wc -c 'hersh.oc4'`"
then
	echo shar: error transmitting "'hersh.oc4'" '(should have been 28235 characters)'
fi
#	End of shell archive
exit 0

